### DISCUSSION TITLE
Permissions / Docker / Can't write

### DISCUSSION THREAD

**Discussion by Magsybaby** [filebrowser/filebrowser#1159] [Q&A]
I have a fresh docker deployment of Filebrowser on Ubuntu. The /myfiles volume is an SMB/CIFS share on Windows (via Docker with RW credentials)

Filebrowser can read from it but cannot write. I am logged in as admin. At the console for FB in Docker I can create files and directories without issue on this volume.

time="21-11-2020 21:22:09" level=error msg="fb.http.handle: path: [/test2], status:403 172.16.0.10:43852 open /myfiles/test2: permission denied"

If I use a volume on the Ubuntu host it can write. I've also run FB on Windows and it is able to write (irrelevant I know)

I'm a Windows guy so apologies, this is probably something stupid...? :)

**Comment by o1egl** [comment]
I think you have some issues with file system permissions. Can you please share the command how you run filebrowser?

**Comment by mrsharps** [comment]
I'm having a similar issue. I can read, but not write a file on a SMB share.  And sadly, I'm a bit of a windows guy trying to get this to run on Ubuntu Server.  

Here is the error I am seeing when I try to move a file:
`2021/12/10 05:47:16 /cool.file: 403<ip address> open /srv/subDir/cool.file: permission denied`

I set it up through portainer.  Here is my docker compose
```

---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 49153:80
    volumes:
      - /media/coolDirectory/:/srv
      - /home/mrsharps/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

Thankful for any suggestions?
