### DISCUSSION TITLE
Share Management and Rules when running in a docker container

### DISCUSSION THREAD

**Discussion by sneekee** [filebrowser/filebrowser#1670] [Q&A]
How can I properly setup my docker container so that I can use Share Management and Rules? When I try to use the terminal in the browser to do filebrowser things I just get `exec: "filebrowser": executable file not found in $PATH`.

Here is my docker-compose file 
```
version: "2.1"
services:
  radarr:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1001
    volumes:
      - /storage/media:/srv
      - /etc/filebrowser/filebrowser.db:/database.db
      - /etc/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 8081:8081
    restart: unless-stopped
```
