### DISCUSSION TITLE
Filebrowser: Directory Listing is too slow!!

### DISCUSSION THREAD

**Discussion by banchchuoi** [filebrowser/filebrowser#1963] [Q&A]
I used file browser version 2.21.1 but it get stuck very long time to browse files in a directory that has 10K++ video files despite configured with --disable-type-detection-by-header option, but no effect, here is my configuration:

/etc/filebrowser.json
{
"port": 8080,
"baseURL": "",
"address": "x.x.x.x",
"log": "stdout",
"database": "/etc/filebrowser.db",
"root": "/u01/camera"
}
/etc/systemd/system/filebrowser.service
[Unit]
Description=File Browser
After=network.target
[Service]
ExecStart=/usr/local/bin/filebrowser -c /etc/filebrowser.json --disable-preview-resize --disable-type-detection-by-header --cache-dir /u01/cache
[Install]
WantedBy=multi-user.target
Can somebody help me?

**Comment by uudecode** [comment]
Bruh, I know that question is outdated, but this is answer for docker:

```
# cat docker-compose.yml 
version: "2.3"


services:
  filebrowser:
    container_name: DS-Video-Archive--filebrowser
    restart: always
    image: filebrowser/filebrowser:latest
    command: --disable-preview-resize --disable-thumbnails  --disable-type-detection-by-header
    user: 1009:1010
    ports:
      - 41281:80
    volumes:
      - /opt/storage:/srv
      - ./filebrowser/filebrowser.db:/database/filebrowser.db
      - ./filebrowser/filebrowser.db.TMP:/database/filebrowser.db.TMP
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
```
