### DISCUSSION TITLE
Is there a config file reference?

### DISCUSSION THREAD

**Discussion by MateusAmin** [filebrowser/filebrowser#1964] [Q&A] [answered]
First off, really awesome software :). I have been looking for something like it since 2020 but only stumbled upon it now. Thanks to hacdais, o1egl, and the rest of the contributors. Sincerely appreciate it. 

To the point, I am putting file-browser on k8s and there have been a few bumps:

- The linuxserver based Docker attempts to set UID/GUI at startup. In k8s the kublet will take care of file permission so you can force the container to run as a certain user for security. But I cannot do this with the container attempting to change file permissions itself. I am using the vanilla docker image now and it is fine.

- Personally, I really want a config reference that I could edit then pass to the container at startup. Seems like you need to filebrowser config init the db locally then export the config from the db then pass that config to k8s. But then things are moved around when compared with the docker defaults. As if it will expect "server" as root or root -> server. It also has a key now, which I guess I should delete since I have the DB in a volume. Overall, I feel like a blind man that has to run the 100 meter hurdles and then put together a puzzle with square pieces asking someone else if it is correct each time. Still working on the config.

EDIT: I am going to give up on the config file and override the entry point to run the cli for setup. See how that goes.

EDIT 2: Could not get it to work with CLI. Only thing not working is the noauth. Returning to config file method. This is the config I tried.
```  
  {
      "port": 4756,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv",
      "signup": false,
      "authMethod": "noauth",
      "settings": {
        "authMethod": "noauth"
      },
      "auth": {
        "authMethod": "noauth"
      }
    }
```

I can attach a mostly working k8s yaml if anyone wants.

Edit 3: Got it working. See below.

**Comment by MateusAmin** [comment, marked as answer]
Example of a working k8s config with no auth set behind a nginx ingress with basic auth. I had to use a mix of overriding the entrypoint to add an argument to run command and overriding the default config. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config-json
data:
  config-json: |-
    {
      "port": 4756,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: filebrowser
  labels:
    app: filebrowser
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: 6518
        runAsGroup: 6518
        fsGroup: 6518
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: fileshare-v1
        - name: config-json # To access this volume, this name must be used inside volumeMounts of the container
          configMap:
            name: config-json # Name of the configMap
            items:
              - key: config-json  # Name of the item we had used inside our ConfigMap (under data:)
                path: .filebrowser.json # Name of the file to be placed inside /etc
        - name: filebrowser-v1
          persistentVolumeClaim:
            claimName: filebrowser-v1
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser
          command: ["/filebrowser", "--noauth"]
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 4756
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "6518"
            - name: PGID
              value: "6518"
          ports:
            - name: filebrowser
              containerPort: 4756
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - mountPath: /database
              name: filebrowser-v1
            - name: files
              mountPath: /srv
            - name: config-json
              mountPath: /.filebrowser.json # This should be your final destination
              subPath: .filebrowser.json # The name of the file to be placed inside /etc, the filename used here and in mountPath should be same.

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: filebrowser
  labels:
    app: filebrowser
spec:
  type: ClusterIP
  ports:
    - port: 4756
      name: filebrowser
      targetPort: 4756
      protocol: TCP
  selector:
    app: filebrowser

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: filebrowser-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lets-encrypt-cluster-issuer
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Auth required"
spec:
  tls:
    - hosts:
        - filebrowser.example.com
      secretName: filebrowser-ingress-tls
  rules:
    - host: filebrowser.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port: 
                  number: 4756
```
