### DISCUSSION TITLE
Multiple directories

### DISCUSSION THREAD

**Discussion by dreg35** [filebrowser/filebrowser#2023] [Q&A]
Is there a way to add multiple directories?

**Comment by ramiresviana** [comment]
The application root and user scope are limited to a single path. Additional items can be added as subdirectories.

**Reply by dreg35** [reply]
How would one do that? I'm using Docker on a Raspeberry Pi?

**Reply by ramiresviana** [reply]
The user scope can be changed on the settings page. Application root must be set using the options listed on documentation: https://filebrowser.org/cli/filebrowser

**Reply by dreg35** [reply]
Ok... So I guess it's not clear. I have set my root which is the data folder, but I would like to also be able to access the appdata folder. Am I missing something?
```
version: "2.1"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
        - PUID=998
        - PGID=100
        - TZ=America/Los_Angeles
    volumes:
      - /srv/dev-disk-by-uuid-10a22804-a844-45d9-a67f-00865d572352/databases/filebrowser/filebrowser.db:/database/filebrowser.db
      - /srv/dev-disk-by-uuid-10a22804-a844-45d9-a67f-00865d572352/appdata/filebrowser/settings.json:/config/settings.json
      - /srv/dev-disk-by-uuid-dfc1e235-4bf2-48f9-bebf-a6a717bf4825/data:/srv
      - /srv/dev-disk-by-uuid-10a22804-a844-45d9-a67f-00865d572352/appdata:/srv
    ports:
      - 8888:80
```
