### DISCUSSION TITLE
Caddyfile example

### DISCUSSION THREAD

**Discussion by oz117** [filebrowser/filebrowser#2214] [General]
Hello,
I have been trying to access my file browser instance behind a caddy instance, but it is not working.
Do you have any Caddyfile example ?
Here is what I have currently:
settings.json:
```json
{
  "port": 48080,
  "baseURL": "/",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/share"
}
```

Caddyfile:
```
domain_name {
        reverse_proxy /* 10.0.0.3:48080
}
```

And in caddy logs I have the following:
```json
{
  "level": "error",
  "ts": 1667737707.9069085,
  "logger": "http.log.error",
  "msg": "dial tcp 10.0.0.3:48080: i/o timeout",
  "request": {
    "remote_ip": "XXX.XXX.XXX",
    "remote_port": "XXXXX",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "domain_name",
    "uri": "/",
    "headers": {
      "Sec-Fetch-Site": [
        "none"
      ],
      "Sec-Fetch-User": [
        "?1"
      ],
      "Te": [
        "trailers"
      ],
      "User-Agent": [
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"
      ],
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      ],
      "Accept-Language": [
        "fr-FR,en-US;q=0.7,en;q=0.3"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "Sec-Fetch-Dest": [
        "document"
      ],
      "Sec-Fetch-Mode": [
        "navigate"
      ]
    },
    "tls": {
      "resumed": true,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "domain_name"
    }
  },
  "duration": 3.002765534,
  "status": 502,
  "err_id": "44g0wfyk2",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:1196)"
}
```

Do you have any idea of what I am doing wrong here ?

Thanks for the help :)

**Comment by oz117** [comment]
Ok I found the issue, it was my fault!
In the end here is my docker file for filebrowser:
```yaml
version: '3.7'
services:
  app:
    container_name: filebrowser
    hostname: filebrowser
    image: filebrowser/filebrowser:s6
    restart: always
    volumes:
     - "./database/filebrowser.db:/database/filebrowser.db"
     - "./settings.json:/config/settings.json"
    environment:
     - PUID=
     - PGID=
    ports:
    - "48080:48080"

networks:
  default:
    external:
      name: name_of_caddy_network
```

It is the last part with the `networks` that does the magic trick to connect filebrowser to caddy 😄 .

Also, my Caddyfile config is as follow:
```
domain_name {
        reverse_proxy /* 10.0.0.3:48080
}
```

Hope it helps someone 😄
