### DISCUSSION TITLE
FileBrowser behind NPM not reachable from outside over HTTPS

### DISCUSSION THREAD

**Discussion by dkman123** [filebrowser/filebrowser#2388] [Q&A]
nginx proxy file nginx/proxy_host/9.conf
```
# ------------------------------------------------------------
# filebrowser.MYDOMAIN
# ------------------------------------------------------------

server {
  set $forward_scheme http;
  set $server         "filebrowser";
  set $port           82;

  listen 80;
#listen [::]:80;

listen 443 ssl http2;
#listen [::]:443;

  server_name filebrowser.MYDOMAIN;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-2/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-2/privkey.pem;

  # Block Exploits
  include conf.d/include/block-exploits.conf;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;

    # Force SSL
    include conf.d/include/force-ssl.conf;

  access_log /data/logs/proxy-host-9_access.log proxy;
  error_log /data/logs/proxy-host-9_error.log warn;

  location /filebrowser {

    ## Special for FileBrowser
    # prevents 502 bad gateway error
    proxy_buffers 8 32k;
    proxy_buffer_size 64k;

    ## Special for FileBrowser

    client_max_body_size 75M;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
    #proxy_read_timeout 999999999;

    #proxy_set_header X-NginX-Proxy true;

    # enables WS support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect off;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000;includeSubDomains; preload" always;

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

filebrowser config filebrowser/settings.json
```
{
  "port": 80,
  "baseURL": "/filebrowser",
  "address": "0.0.0.0",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

If I have location /filebrowser {
and "baseURL": "/filebrowser",
I can get:
https://filebrowser.MYDOMAIN/ gives an OpenResty page
https://filebrowser.MYDOMAIN/login gives a 404
http://127.0.0.1:82/login loads the login page
http://127.0.0.1:82/test redirects to the login page
So I feel like that is very close to working.
Putting an ending / on the end of baseURL doesn't change anything.

So I though maybe the filebrowser web page is trying to redirect me, so maybe it needs the full URL... 
If I have location /filebrowser {
and "baseURL": "https://filebrowser.MYDOMAIN/filebrowser",
I can get:
https://filebrowser.MYDOMAIN/ gives an OpenResty page
https://filebrowser.MYDOMAIN/login gives a 404
http://127.0.0.1:82/login gives the 3 dots "stuck" page
So that's clearly not right since I can't get in at all.

Just showing what I had originally using the defaults...
If I have location / {
and "baseURL": "",
I can get:
https://filebrowser.MYDOMAIN/ gives a 502 bad gateway
https://filebrowser.MYDOMAIN/login gives a 502 bad gateway
http://127.0.0.1:82/login loads the login page
http://127.0.0.1:82/test redirects to the login page
This is where I was stuck for a long time, but eventually found that entering a custom baseURL gets me close.
BTW: Entering just "/" for baseURL doesn't change anything, you need a name, and sync that with the npm config.

NPM has a LetsEncrypt certificate, and trying http from outside will pisss off cloudflare with a "bad cert" message.
I also want everything coming through https.  But can anyone get me past that last little step to get the loading page.

My docker-compose.yml just in case it's significant:
```
...

  # File Browser - Explorer
  # default admin / admin
  filebrowser:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.177
    ports:
      - "82:80" # 80 and 81 are used by Nginx Proxy Manager
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $DOCKERDIR/filebrowser:/srv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
      VIRTUAL_HOST: "filebrowser.MYDOMAIN"
      VIRTUAL_PROTO: "http"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: "0"
```
I didn't have the VIRTUAL_HOST and PROTO orignally, that was something I found along the way.
I can include other bits if necessary.

Nothing is showing up in either docker log to indicate why I can't reach the login page.

The most helpful link I found is https://github.com/filebrowser/filebrowser/issues/400 which is what got me close.
