### DISCUSSION TITLE
filebrowser + apache-reverse-proxy + docker-compose

### DISCUSSION THREAD

**Discussion by mqu** [filebrowser/filebrowser#2437] [General]
here is an example of using Filebrowser with a little bit strengthened docker-compose.yml, Apache reverse-proxy.

apache2 site configuration with redirect, reverse-proxy and Websocket.
```
<VirtualHost *:80>
        ServerName filebrowser.domain.local
        ServerAdmin admin@domain.local

        ErrorLog ${APACHE_LOG_DIR}/glacier-error.log
        CustomLog ${APACHE_LOG_DIR}/glacier.log combined

        # Enforce HTTPS:
        RewriteEngine On
        RewriteCond %{HTTPS} !=on
        RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
	ServerName filebrowser.domain.local
	ServerAdmin admin@domain.local
	# ...

	RewriteEngine On
	ProxyPass / http://localhost:8080/
	ProxyPassReverse / http://localhost:8080/
	ProxyPreserveHost On

	RewriteCond %{HTTP:Upgrade} =websocket
	RewriteRule /(.*) ws://localhost:8080/$1 [P,L]

</VirtualHost>
```
filebrowser.json
```
{
  "port": 8080,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/srv/fb/filebrowser.db",
  "root": "/srv/fb/data",
  "username": "admin"
}
```
docker-compose.yml
```
version: '3.7'

# doc: https://filebrowser.org/installation
x-defaults-std:
    &default-settings-std
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "5"
    tmpfs:
      - /tmp
      - /run
    networks:
     - private

x-defaults-ress-limit:
    &defaults-ress-limit
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          memory: 25M
    ulimits:
      nproc: 128
      nofile:
        soft: 1024
        hard: 2048
    mem_swappiness: 0
    memswap_limit: '200M'
    cap_drop:
     - ALL

x-defaults-healthcheck:
   &defaults-healthcheck
   healthcheck:
      test: "curl -f http://localhost:8080/health || exit 1"
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 15s

services:
  app:
    <<: *default-settings-std
    <<: *defaults-ress-limit
    <<: *defaults-healthcheck
    image: filebrowser/filebrowser
    read_only: true
    user: 1000:1000
    ports:
      - "8080:8080"
    volumes: 
      - ./filebrowser.json:/srv/fb/filebrowser.json
      - ./data/fb:/srv/fb/
    entrypoint: /filebrowser --config /srv/fb/filebrowser.json

networks:
  private:

```

install
```
mkdir -p ./data/fb ; sudo chown 1000:1000 ./data/fb
```
