### DISCUSSION TITLE
filebrowser:v2.28.0 issue while deploying in eks using efs

### DISCUSSION THREAD

**Discussion by nikhil60961** [filebrowser/filebrowser#3121] [General]
Getting the below error when deploying in aws eks using efs. 

i have attached the yaml file too.

It would be very helpful if someone could solve this [issue]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-cluster-deploy
  namespace: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: filebrowser-volume
        persistentVolumeClaim:
          claimName: filebrowser-pvc
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.28.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: filebrowser-volume
          mountPath: /var/filebrowser
          subPath: poc/fb_setup
        - name: filebrowser-volume
          mountPath: /etc/filebrowser-conf/database.db
          subPath: poc/filebrowser-conf
      initContainers:
      - name: filebrowser-deployment-init
        image: alpine:latest
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: filebrowser-volume
          mountPath: /srv
        - name: filebrowser-volume
          mountPath: /database.db
        - name: filebrowser-volume
          mountPath: /etc/filebrowser-conf
        command:
        - sh
        - -c
        - ([ -d /var/filebrowser ] || mkdir -p /var/filebrowser; [ -d /etc/filebrowser-conf ] || mkdir -p /etc/filebrowser-conf)
        - (chmod -R 0777 /var/filebrowser ; chmod -R 0777 /etc/filebrowser-conf)
        # ; chgrp 1001 /var/filebrowser; chmod -R 0777 /etc/filebrowser-conf; chgrp 1001 /etc/filebrowser-conf)
        - ([ -f /etc/filebrowser-conf/filebrowser.db] || touch /etc/filebrowser-conf/filebrowser.db)`

efaulted container "filebrowser" out of: filebrowser, filebrowser-deployment-init (init)
2024/04/15 07:26:28 Warning: filebrowser.db can't be found. Initialing in /database.db
2024/04/15 07:26:28 Using database: /database.db
2024/04/15 07:26:28 open /database.db: permission denied

**Comment by ahoehma** [comment]
I have the same :-)

**Comment by nikhil60961** [comment]
The init container should run as root and it got fixed for me

**Reply by ahoehma** [reply]
Can u share you working yaml please? 👍

**Reply by ahoehma** [reply]
And 2nd question ... do you know if its possible to put the "db" somewhere else - separated from the mounted efs which I like to browse via filebrowser webapp?

**Reply by ahoehma** [reply]
Btw: the yaml here in the issue is not well formatted.

**Comment by ahoehma** [comment]
I got it now running without a init-container at all.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: efs-browser
spec: 
    replicas: 1 
    selector: 
      matchLabels: 
        app: filebrowser 
    template: 
      metadata: 
        labels: 
          app: filebrowser 
      spec: 
        volumes: 
        - name: efs-volume-customizing-cc
          persistentVolumeClaim:
            claimName: efs-customizing-cc-pvc # <<<<<<<<<<<<<<<< this is the efs pvc
        containers: 
        - name: filebrowser 
          image: filebrowser/filebrowser:v2.31.2
          imagePullPolicy: IfNotPresent 
          resources: 
            requests: 
              memory: "256Mi" 
              cpu: "500m" 
            limits: 
              memory: "256Mi" 
              cpu: "500m" 
          ports: 
          - containerPort: 80
          volumeMounts: 
          - name: efs-volume-customizing-cc 
            mountPath: /srv    
```
