### DISCUSSION TITLE
Container unhealthy and unable to reach webUI

### DISCUSSION THREAD

**Discussion by mgrimace** [filebrowser/filebrowser#3168] [Q&A]
Hello, I'm running a docker server as a non-root user. When I deploy the container it starts, but reports 'unhealthy' and I cannot reach the webui at IP:8095 (my designated port below) I created the .db and config.json as the user. Any advice?

Here is my compose snippet (of just this service):
```yaml
  filebrowser:
    #description: browse and manage files on server via webui
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKERDIR}:/srv #what you want filebrowser to have access to
      - ${DOCKERDIR}/appdata/filebrowser/filebrowser.db:/database/filebrowser.db #make these files before you deploy
      - ${DOCKERDIR}/appdata/filebrowser/settings.json:/config/settings.json #download sample one from their github
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FB_BASEURL=/
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined    
    ports:
      - 8095:80    
    labels: 
      com.centurylinklabs.watchtower.enable: "true"
```
