### DISCUSSION TITLE
Multible folders 📂 with different ownership 👤

### DISCUSSION THREAD

**Discussion by SuitDeer** [filebrowser/filebrowser#3699] [Show and tell]
1. Create `filebrowser.db` and `.filebrowser.json` for filebrowser docker container

    ```bash
    sudo touch /path/to/filebrowserstack/filebrowser.db

    sudo tee /path/to/filebrowserstack/.filebrowser.json <<EOF
    {
        "port": 80,
        "baseURL": "",
        "address": "",
        "log": "stdout",
        "database": "/database/filebrowser.db",
        "root": "/srv"
    }
    EOF
    ```

2. Create a custom script for `chmod` operations

    - All files in `myfolder1` sould have ownership `1001:1001`
    - All files in `myfolder2` sould have ownership `82:82`
    - All files in `myfolder3` sould have ownership `1000:1000`

    ```bash
    sudo tee /path/to/filebrowserstack/chown-scripts.sh <<EOF
    #!/bin/sh
    FILE=\$1
    if [[ "\$FILE" == *"myfolder1"* ]]; then
        chown 1001:1001 "\$FILE"
    elif [[ "\$FILE" == *"myfolder2"* ]]; then
        chown 82:82 "\$FILE"
    elif [[ "\$FILE" == *"myfolder3"* ]]; then
        chown 1000:1000 "\$FILE"
    fi
    EOF
    sudo chmod +x /path/to/filebrowserstack/chown-script.sh
    ```

3. Setup filebrowser container via `docker-compose.yml`. In my example I mount the folder `myfolder1`, `myfolder2` and `myfolder3` into the `/srv` directory into the `filebrowser` docker container.

    ```YML
    services:
    filebrowser:
        volumes:
        - /path/to/myfolder1:/srv/myfolder1
        - /path/to/myfolder2:/srv/myfolder2
        - /path/to/myfolder3:/srv/myfolder3
        
        - /path/to/filebrowserstack/filebrowser.db:/database/filebrowser.db
        - /path/to/filebrowserstack/.filebrowser.json:/.filebrowser.json
        - /path/to/filebrowserstack/chown-script.sh:/chown-script.sh
        user: 0:0
        ports:
        - 8080:80
        image: filebrowser/filebrowser
    ```

4. Now login into the webinterface: `https://....:8080` and go to `Settings -> Global Settings -> Command Runner`.

    Put the following code intor `After Copy`, `After Rename`, `After Save` and `After Upload` text area:

    ```bash
    ./chown-script.sh "$FILE"
    ```

    At the end of the site click on `UPDATE` Button to save.
