### DISCUSSION TITLE
Add LDAP 🛜 authentication to docker container

### DISCUSSION THREAD

**Discussion by SuitDeer** [filebrowser/filebrowser#3702] [Show and tell]
Tutorial based on the following github ticket: [https://github.com/filebrowser/filebrowser/pull/1554](https://github.com/filebrowser/filebrowser/pull/1554)

1. Download `filebrowser.db` and create `.filebrowser.json` for filebrowser docker container

    Unfortunately the filebrowser.db can not be edited inside the docker container itself. I had to modify the filebrowser.db on a plain linux installation to modify the authentication method:

    ```bash
    curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
    filebrowser -d filebrowser.db config set --auth.method=hook --auth.command="/ldap.sh arg"
    filebrowser -d filebrowser.db config set --address=
    filebrowser -d filebrowser.db config set --port=80
    filebrowser -d filebrowser.db config set --root=/srv
    ```
    
    For easy download I have uploaded the modified filebrowser.db to a public accessable github repo [https://github.com/SuitDeer/filebrowser-ldap-db](https://github.com/SuitDeer/filebrowser-ldap-db)

    ```bash
    wget https://raw.githubusercontent.com/SuitDeer/filebrowser-ldap-db/refs/heads/main/filebrowser.db -O /path/to/filebrowserstack/filebrowser.db

    sudo tee /path/to/filebrowserstack/.filebrowser.json <<EOF
    {
        "port": 80,
        "baseURL": "",
        "address": "",
        "log": "stdout",
        "database": "/database/filebrowser.db",
        "root": "/srv"
    }
    EOF
    ```

2. Create docker-compose.yml. `nano docker-compose.yml` and paste the following content into it:
   
   ```YML
   services:
     filebrowser:
       build:
         context: .
         dockerfile_inline: "FROM filebrowser/filebrowser\nRUN apk update && apk add openldap-clients;"
       volumes:
         - /path/to/myfolder:/srv
        
         - /path/to/filebrowserstack/filebrowser.db:/database/filebrowser.db
         - /path/to/filebrowserstack/.filebrowser.json:/.filebrowser.json
         - /path/to/filebrowserstack/ldap.sh:/ldap.sh
       user: 0:0
       ports:
         - 8080:80
   ```

3. Create a custom script for `ldap` auth

    - Please edit the following LDAP-Server address: `ldap://172.17.0.2:389`
    - Please edit the base DN path: `,ou=users,dc=example,dc=org`

    ```bash
    sudo tee /path/to/filebrowserstack/ldap.sh <<EOF
    #!/bin/sh

    # Runs ldapwhoami with provided password and username appended to the base DN
    ldapwhoami -H ldap://172.17.0.2:389 -D cn=\$USERNAME,ou=users,dc=example,dc=org -w \$PASSWORD > /dev/null 2>&1

    # Authenticate only when ldapwhoami exit without errors (code 0)
    if [[ \$? -eq 0 ]]; then
        echo "hook.action=auth"
    elif [[ \$USERNAME == "admin" ]]; then
        echo "hook.action=pass"
    else
        echo "hook.action=block"
    fi
    EOF
    sudo chmod +x /path/to/filebrowserstack/ldap.sh
    ```

4. Deploy via docker compose (File created in step 2):

   ```bash
   sudo docker compose up -d
