### DISCUSSION TITLE
First start of filebrowser stuck on spinner page

### DISCUSSION THREAD

**Discussion by stenrock** [filebrowser/filebrowser#3821] [Q&A] [answered]
Docker compose on a raspberry pi. No errors when starting up and other containers run without problem.
Nginx proxy to containers ip:port.

docker-compose.yml
```
filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - "/data/myfiles/:/srv"
      - "./filebrowser/filebrowser.db:/database/filebrowser.db"
      - "./filebrowser/settings.json:/config/settings.json"
    ports:
      - "8084:8084"
    restart: unless-stopped

```
settings.json
```
{
  "port": 8084,
  "baseURL": "[my-server-address]",
  "address": "0.0.0.0",
  "log": "stdout",
  "root": "/srv"
}
```
I have no problem to reach the page, no nginx error, but it is just stuck on the spinner icon.

Searched all discussions and bugs etc on github without finding anything that solves my problem.

I hope someone can help me, must be a configuration issue.
