### DISCUSSION TITLE
Docker: Permission Denied / Forbidden After v2.33.0

### DISCUSSION THREAD

**Discussion by somnifex** [filebrowser/filebrowser#5251] [Q&A] [answered]
### Checklist

- [x] This is a bug report, not a question.
- [x] I have searched on the [issue tracker](https://github.com/filebrowser/filebrowser/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [FileBrowser version](https://github.com/filebrowser/filebrowser/releases) or have an issue updating.

### Version

```Text
v2.33
```

### Description

When deploying with Docker, the logs from the latest version 2.33 are reporting errors:

cp: can't preserve ownership of '/config/settings.json': Operation not permitted
/init.sh: exec: line 41: illegal option -d

The command is as follows:
```
docker run
  -d
  --name='FileBrowser'
  --net='bridge'
  -p '8081:80/tcp'
  -v '/mnt/hdd/appdata/filebrowser/':'/db/':'rw'
  --user 1000:100 filebrowser/filebrowser:v2.32.3
  -d /db/database.db
```

My initial, unverified suspicion is that this might be related to permission mapping – user 1000:100 potentially causing the issue (though I haven’t confirmed this yet).

### What did you expect to happen?

Normal operation

**Comment by hululu75** [comment]
hi, I have the same issue: I am using rootless Docker mode, and files created inside the container (e.g., filebrowser.db) by root appear on the host with a different UID—such as 100999. While permission issues for these files can sometimes be resolved on the host by changing their mode with chmod, the directory mounted at /srv inside the container still cannot be properly loaded or accessed.

**Comment by fayeinmay** [comment]
Same issue. Can't start the container,

**Comment by dsxcsman** [comment]
Exactly the same problem here too. Rolled back to v2.32.3.

**Comment by gujiangjiang** [comment]
![Image](https://github.com/user-attachments/assets/315cf722-d7fe-473d-8e58-a35326623f35)
same with me cant start docker

**Comment by mmartial** [comment]
With the shift to the `s6`-based methodology (for the `alpine` base, see https://github.com/filebrowser/filebrowser/releases/tag/v2.33.0), the default UID/GID within the container is now `1000:1000` ~~(this may be changed using the `PUID/PGID` parameters, although this has not been tested)~~.

The following is what worked for me, adapt as needed

## File renaming

With your previous files in the `files` folder, named `config.json` and `filebrowser.db`

```bash
mkdir config database
cp files/config.json config/settings.json
cp database/filebrowser.db database/
```

## DB location

You need to edit the `config/settings.json` file to replace the `"database"` line to reflect the new location of the file:
```text
   "database": "/database/filebrowser.db",
```

## Permission denied

The `permission denied` issue appears to be that the user within the container is `1000:1000`

```bash
❯ sudo docker run --rm -it filebrowser/filebrowser /bin/sh
/ $ whoami
user
/ $ id
uid=1000(user) gid=1000(user) groups=1000(user)
```

I got the `permission denied` error solved by doing a `chmod` on the config/db

```bash
chown 1000:1000 config/settings.json database/filebrowser.db
```

This means file permissions on stored files as well:
```test
> docker compose logs
[...] test/test: 403 <IP> open /srv/test/test: permission denied
```

You must `chown` your mounted `/srv` folder (below as  `filebrowser`):
```bash
sudo chown -R 1000:1000 filebrowser
```
, to be able to create files within again.

**Comment by djarbz** [comment]
@mmartial PUID/PGID does not seem to be taking effect. My container user is still `1000` and I need it to be `568` for TrueNAS.

**Comment by mmartial** [comment]
Confirmed from the `Dockerfile` 
https://github.com/filebrowser/filebrowser/blob/e9bb3dc243eb64b2a7da1bd17feb26bd83e06216/Dockerfile#L6

Hard-set as `1000:1000`

**Comment by djarbz** [comment]
This is to be expected, typically there is logic in s6 or the entrypoint to adjust the user IDs.

**Comment by mmartial** [comment]
@djarbz You may need to create a new stack with the `s6` overlay version to enable the `PUID`/`PGID` option for changing file ownership.

Or try to do `docker run -u 567:567` ?
https://docs.docker.com/reference/cli/docker/container/run/

**Comment by dsxcsman** [comment]
> With the shift to the `s6`-based methodology (for the `alpine` base, see https://github.com/filebrowser/filebrowser/releases/tag/v2.33.0), the default UID/GID within the container is now `1000:1000` ~(this may be changed using the `PUID/PGID` parameters, although this has not been tested)~.
> 
> The following is what worked for me, adapt as needed
> 
> ## File renaming
> With your previous files in the `files` folder, named `config.json` and `filebrowser.db`
> 
> mkdir config database
> cp files/config.json config/settings.json
> cp database/filebrowser.db database/
> ## DB location
> You need to edit the `config/settings.json` file to replace the `"database"` line to reflect the new location of the file:
> 
> ```
>    "database": "/database/filebrowser.db",
> ```
> 
> ## Permission denied
> The `permission denied` issue appears to be that the user within the container is `1000:1000`
> 
> ❯ sudo docker run --rm -it filebrowser/filebrowser /bin/sh
> / $ whoami
> user
> / $ id
> uid=1000(user) gid=1000(user) groups=1000(user)
> I got the `permission denied` error solved by doing a `chmod` on the config/db
> 
> chown 1000:1000 config/settings.json database/filebrowser.db
> This means file permissions on stored files as well:
> 
> ```
> > docker compose logs
> [...] test/test: 403 <IP> open /srv/test/test: permission denied
> ```
> 
> You must `chown` your mounted `/srv` folder (below as `filebrowser`):
> 
> sudo chown -R 1000:1000 filebrowser
> , to be able to create files within again.

Thanks working perfectly

**Comment by flammable** [comment]
I'd very much like a method to set the UID/GID via env vars in the alpine image - 1000:1000 isn't correct on my OS, either. I'll give the s6 one a try in the meantime, thanks for the pointer.

EDIT: The s6 image works great, I'll stick with that for now.

**Comment by Guiorgy** [comment]
AFAIK, containers that allow setting UID/GUID through environmental variables run as root and change the user in the entry script. In case of s6, from their [README](https://github.com/just-containers/s6-overlay):

> As of version 3.2.1.0, s6-overlay has limited support for running as a user other than root:
>
>    Tools like fix-attrs and logutil-service are unlikely to work (they rely on being able to change UIDs).
>    The syslogd emulation will not work.

So as I mentioned, the container is actually running as root, so if s6-overlay hapens to have an exploit, the attacker could gain root.

Either way, probably not something that will be done while the project is in maintainance mode, I'm pretty happy with the current changes as is. Besides, you can simply run the container using the Docker `user` option, for example:

```yaml
filebrowser:
  image: filebrowser/filebrowser:latest
  user: '10000:10000'
  ...
```

Just make sure the files in the `/database` and `/config` (`/database/filebrowser.db` and `/config/settings.json`) are owned by that `UID:GUID`. I'm running the container like that.

**Comment by hacdias** [comment]
Thanks @Guiorgy @mmartial  for giving more information.

Just like @Guiorgy mentioned, you can customize the PID/GID using the `--user` flag. If you mount volumes owned by the same user, it should work as intended.

Please always read release notes before upgrading.

**Comment by charl3y15** [comment]
Having this issue too, rolling back to [v2.32.3](https://github.com/filebrowser/filebrowser/releases/tag/v2.32.3) fixed it

**Comment by Guiorgy** [comment]
> Having this issue too, rolling back to [v2.32.3](https://github.com/filebrowser/filebrowser/releases/tag/v2.32.3) fixed it

Did you try the steps [mmartial](https://github.com/filebrowser/filebrowser/issues/5162#issuecomment-2988227443) mentioned above?

**Comment by flammable** [comment]
Oh cool, thanks for the pointer about `user`. I haven't done that for an image for a while. If I need to switch away from s6, that's a great option.

For my setup, I'd prefer to run File Browser as root, as I have it behind a reverse proxy (with Authentik and MFA). I've disabled File Browser's auth as it's not needed for my setup.

**Reply by Guiorgy** [reply]
Then the normal (non-s6) image with the `user: 0:0` should also do the trick, no need for extra init steps like s6

**Comment by hululu75** [comment]
the method [mmartial ](https://github.com/filebrowser/filebrowser/issues/5162#issuecomment-2988227443) does not work in Rootless mode

LOG
```
2025/06/20 15:33:13 Using database: /database/filebrowser.db
2025/06/20 15:33:13 Using config file: /config/settings.json
2025/06/20 15:33:13 Listening on [::]:80
2025/06/20 15:33:21 /: 403 172.20.0.1 open /srv: permission denied

```
on the host , i need use mode 766 or 777

```
$ ll
total 0
drwxrwxrwx. 2 100999 100999 27 Jun 19 09:38 config
drwxrwxrwx. 2 100999 100999 54 Jun 19 10:34 database
```

I can't change the permissions of the directory mounted at /srv with UID 100999

**Comment by Guiorgy** [comment]
> on the host , i need use mode 766 or 777

There's no need to make them read-writable by everyone, just the user/group that the container runs with (`770`). By default the container now runs with `1000:1000`, if you are setting them to `100999:100999` am I right to assume you are running the container with `--user="100999:100999"` option (or `user: "100999:100999"` in a compose file)? If not then you need to either change the file ownership, or change what user the container runs with.

> ```
> 2025/06/20 15:33:13 Using database: /database/filebrowser.db
> 2025/06/20 15:33:13 Using config file: /config/settings.json
> 2025/06/20 15:33:13 Listening on [::]:80
> 2025/06/20 15:33:21 /: 403 172.20.0.1 open /srv: permission denied
> ```

As mentioned above, the user the container runs with also needs to be able to access the `/srv` directory.

> I can't change the permissions of the directory mounted at /srv with UID 100999

In that case, probably the simplest solution is to run the container with a user that does have permissions to that directory (and also modify the permissions of the database and config files). It wouldn't be perfect, but still a lot better than running as root as before. Alternatively, you can explicitly run the container as `root` (`--user="0:0"`), but I really don't recommend that.

**Comment by bassterror** [comment]
I'm struggling with the transition to the new way of mounting.

The error in the log is not exactly the same as above but close enough.
```
2025/07/01 12:20:05 Using database: /database/filebrowser.db
2025/07/01 12:20:05 Using config file: /config/settings.json
2025/07/01 12:20:05 listen tcp :80: bind: permission denied
```

docker-compose
```
services:
  files:
    image: filebrowser/filebrowser:latest
    container_name: files
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8082:80
    user: 1026:100
    volumes:
      - ./appdata/db:/database
      - ./appdata/config:/config
      - ./appdata/theme:/branding
      - /volume1:/srv
```

ownership:  uid=1026(bassterror) gid=100(users)
```
-rwxrwxrwx+ 1 bassterror users 143 Jul  1 12:00 settings.json
```
```
-rwxrwxrwx+ 1 bassterror users 65536 Jul  1 15:09 filebrowser.db
```

**Comment by hacdias** [comment]
@bassterror if you read the error, you see that the user inside the image (1026?) does not have permission to open port 80. Since you're using Docker, I'd just change that in config.json and then change the port in the compose.

**Comment by Guiorgy** [comment]
> 2025/07/01 12:20:05 listen tcp :80: bind: permission denied

This is a different issue. Ports below `1024` are usually protected and it seems that the user inside the container can't bind to port 80. There are a few options you have:

- Run the container as root (`user: "0:0"`), which is allowed to bind to any port.
- As hacdias mentioned above, change the listening port inside the container through the configuration ~(in `settings.json` the line `"port": 80,`)~, for example, set it to `8080` (use something > `1024`) and then in the docker compose file change the binding port to the one you just changed to, for example `ports: - 8082:8080` ~(also set the `FB_PORT` to the correct value so the healthchecks work)~. Set the `FB_PORT` environmental variable to the desired value (e.g. `8080`) to change the listening port.
- Try to diagnose why the user inside can't bind to port `80` and/or give it explicit permission to do so. There are many ways to do so, just google it yourself.

The first option is the easiest, but it defeats the whole point of moving away from root, so the second option is the second best IMO.

@hacdias Might've been a good idea to also migrate the listening port inside the container away from port `80` with the move away from `root`. Would it be to late to change the default now?

We could add an environmental variable, lets say `HTTP_PORT` or `LISTEN_PORT`, that users can change in cli or compose file, and add code to the `init.sh` to replace the port inside `settings.json`, though, since they should have easy access to `settings.json` it might not be worth doing.

**Comment by hacdias** [comment]
@Guiorgy that's usually true, but if you just run it normally (`docker run filebrowser/filebrowser:latest`), you won't have the port 80 issue.

You can already use `FB_PORT` to change the port, or the port flag: `docker run filebrowser/filebrowser:latest --port 81`

**Comment by Guiorgy** [comment]
> You can already use `FB_PORT` to change the port, or the port flag: `docker run filebrowser/filebrowser:latest --port 81`

Correct me if I am wrong, but `FB_PORT` is only used for healthchecks? It doesn't actually change the listening port?

**Comment by hacdias** [comment]
It does:

```
$ docker run --env FB_PORT=1234 filebrowser/filebrowser:latest
2025/07/01 14:15:16 Warning: filebrowser.db can't be found. Initialing in /database/
2025/07/01 14:15:16 Using database: /database/filebrowser.db
2025/07/01 14:15:16 Using config file: /config/settings.json
2025/07/01 14:15:16 Randomly generated password for user 'admin': YSuYIt6O-Oeb0dim
2025/07/01 14:15:16 Listening on [::]:1234
```

**Comment by Guiorgy** [comment]
> It does:
> 
> ```
> $ docker run --env FB_PORT=1234 filebrowser/filebrowser:latest
> 2025/07/01 14:15:16 Warning: filebrowser.db can't be found. Initialing in /database/
> 2025/07/01 14:15:16 Using database: /database/filebrowser.db
> 2025/07/01 14:15:16 Using config file: /config/settings.json
> 2025/07/01 14:15:16 Randomly generated password for user 'admin': YSuYIt6O-Oeb0dim
> 2025/07/01 14:15:16 Listening on [::]:1234
> ```

Huh, good to know, thanks! Searching for `FB_PORT` in GitHub only shows the healthcheck script though :/

**Comment by hacdias** [comment]
If you run `filebrowser help`:

```
File Browser CLI lets you create the database to use with File Browser,
manage your users and all the configurations without accessing the
web interface.

If you've never run File Browser, you'll need to have a database for
it. Don't worry: you don't need to setup a separate database server.
We're using Bolt DB which is a single file database and all managed
by ourselves.

For this specific command, all the flags you have available (except
"config" for the configuration file), can be given either through
environment variables or configuration files.

If you don't set "config", it will look for a configuration file called
.filebrowser.{json, toml, yaml, yml} in the following directories:

- ./
- $HOME/
- /etc/filebrowser/

The precedence of the configuration values are as follows:

- flags
- environment variables
- configuration file
- database values
- defaults

The environment variables are prefixed by "FB_" followed by the option
name in caps. So to set "database" via an env variable, you should
set FB_DATABASE.

(...)

```

**Comment by izzaura** [comment]
Hello, figured I should ask for help here after trying the solutions that were listed. Since last update, I am getting `cp: can't stat '/config/settings.json': Permission denied`  even after doing  `chown 1000:1000 config/settings.json database/filebrowser.db` and the container is unable to start.

However, if I do `chmod 777 config/settings.json database/filebrowser.db` the container starts and runs without issue.

Running whoami in FB returns `user` and id returns `uid=1000(user) gid=1000(user) groups=1000(user)`

Any idea how can I fix this without giving permissions to everyone?

**Reply by hacdias** [reply]
Have you tried following the instructions here: https://github.com/filebrowser/filebrowser/releases/tag/v2.33.0? And just like I said in some other comment, have you made sure that the directory mounted on `/config` and `/database` are owned by user 1000? And that the same user can read and write?

**Reply by izzaura** [reply]
I did follow all the intstuctions. Probably something messed up with the permissions on my host. Fixed it by doing `chmod 700` after making sure user 1000 is owner of the directory.

**Comment by Fabian-C** [comment, marked as answer]
For me, using a docker-compose based deployment it's as easy as just mounting the directories for Database and Settings in the Host OS and then granting access to the user ID also running inside the Container.

volumes:
      # Filebrowser directories
      - ./filebrowser/database/:/database/:rw
      - ./filebrowser/config/:/config/:rw

**Comment by hacdias** [comment]
Okay, I am not changing the image, since it works as intended. The issue is about clarity of how Docker works with bind mounts. Therefore, I have:

- Updated the instructions at: https://filebrowser.org/installation.html#docker
- Updated the release notes from all latest minor versions to include information about the Docker image changes

**Comment by ManiMatter** [comment]
I also couldn't get it to work.
Tried for 30min to follow the release notes, the new installation instructions and play with docker settings.
Even deleted the entire image and container and tried a fresh install.
No chance.

Rolled back to 2.3.0.

Here is what works for me.
Any pointers how to change this would be welcome, so that it works with the latest version again.

```
  ## File Browser - Explorer
  filebrowser:
    <<: *common-keys-apps
    image: filebrowser/filebrowser:v2.3.0
    container_name: filebrowser
    command:
      - "--database=/config/database.db"
      - "--noauth"
    environment:
      PUID: 1000
      PGID: 1000
      FB_NOAUTH=noauth:
      FB_BRANDING.DISABLEEXTERNAL=true:
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $DATADIR:/srv
      - /dev/shm:/dev/shm
    healthcheck:
      disable: false
    labels:
      - "kuma.__docker"
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.filebrowser-rtr.tls=true"
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"

```

**Reply by hacdias** [reply]
You are using s6-image specific environment variables (e.g. `PUID` and `PGID`) with the normal **non-s6** image. You should start by reading the documentation, and deciding on which image you want: https://filebrowser.org/installation#docker

**Reply by ManiMatter** [reply]
I spent yet another 30min trying to do it. A bit frustrating that what worked well was changed, and it seems so difficult to get it to run.. but maybe that's my stupidity :)

I want to use the non-s6 image, and I stripped my docker-compose to the bare minimum, deleted all my filebrowser folders and launched again. no chance.

**filebrowser  | cp: can't create '/config/settings.json': Permission denied**

Maybe it has to do with what you wrote in your changelog "User: File Browser no longer runs as root, but as user with PID 1000 and GID 1000. You can still change this by using Docker's [--user flag](https://www.docker.com/blog/understanding-the-docker-user-instruction/)."

No idea what I have to change to get this to work.

```

  filebrowser:
    <<: *common-keys-apps
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    volumes:
      - $DATADIR:/srv
      - $DOCKERDIR/appdata/filebrowser/database:/database
      - $DOCKERDIR/appdata/filebrowser/config:/config

    labels:
      - "kuma.__docker"
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.filebrowser-rtr.tls=true"
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"
```

**Reply by Guiorgy** [reply]
First of all, you can read the [Docker compose file reference](https://docs.docker.com/reference/compose-file/services/#user) to see how to change the running user inside the container. TL;DR:

```yaml
services:
  filebrowser:
    ...
    user: “1234:1234“
    ...
```

Secondly, the error very clearly indicates that the user running inside the container has no write permissions to the mapped directory. As the release notes stated, you need to make sure that that user is allowed to read/write there **on the host**.

Either fix the permissions, or revert to using root as the user running filebrowser, though, you must understand that that comes with high risks!

Edit: Since you were not using the s6 image, the PUID/PGID environmental variables never did anything, you were always running filebrowser as **root**.

Edit:

> A bit frustrating that what worked well was changed

Yes, worked great at allowing others to run crypto miners on your system, how sad that criminals can no longer do that! 😂
