### ISSUE TITLE
Docker Compose / Variable Documentation

### ISSUE THREAD

**Issue by yllekz** [filebrowser/filebrowser#1017]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm going through the documentation for File Browser and want to deploy it as a Docker Container on my Raspberry Pi, however I am having trouble deploying it with custom options such as a custom port number, config folder location, etc., as I cannot find documentation on the environment variables or proper Docker compose syntax. Can this be added to the documentation?

**Describe alternatives you've considered**
I looked at the existing Docker deployment documentation, but it is inadequate for my workflow.

**Additional context**
n/a

**Comment by ugosan** [comment]
Hi @yllekz , this is a config that works for my raspberry pi:

```
version: "3.2"
services:

  filebrowser:
    image: filebrowser/filebrowser:v2.3.0-pi
    volumes:
        - /opt/torrent:/srv
        - /opt/filebrowser/filebrowser.db:/database.db
        - /opt/filebrowser/filebrowser.json:/.filebrowser.json
    ports:
        - 8080:80
```

Keep in mind that:
1-You need to specify the **full path** for files (like `/opt/filebrowser/filebrowser.db`)
2-The files need to exist **before** you start the container (a `touch /opt/filebrowser/filebrowser.db` would suffice)
