### ISSUE TITLE
Upload Folder isn't working.

### ISSUE THREAD

**Issue by nickchen120235** [filebrowser/filebrowser#1096]
Hi, I just started a server using the official docker image and docker-compose with an apache reverse proxy on Ubuntu 20.04.
I encounted errors when trying to upload the whole folder, while uploading single file works.
![image](https://user-images.githubusercontent.com/45678482/94264949-4061f800-ff6a-11ea-9c79-a2ae63682a19.png)
My `virtualhost.conf`
```conf
<VirtualHost *:443>
  ServerName my.server.com
  Protocols h2 http/1.1

  SSLEngine on
  SSLCertificateFile    /etc/letsencrypt/live/my.server.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/my.server.com/privkey.pem

  # SSLProxyEngine on
  ProxyPass "/" "http://localhost:8002/"
  ProxyPassReverse "/" "http://localhost:8002/"
  ProxyPreserveHost on
</VirtualHost>
```
My `docker-compose.yml`
```yaml
version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /etc/filebrowser/database.db:/database.db # database
      - ~/files:/srv                              # root
    restart: always
    ports:
      - '127.0.0.1:8002:80'
```
Using the default config file for docker.
