### ISSUE TITLE
Symbolic link is not reachable - v2.10.0 - Docker Compose

### ISSUE THREAD

**Issue by quentin-rey** [filebrowser/filebrowser#1197]
**Description**
I have data volume for my filebrowser container, in which I want to create symbolic links to my local files.
Is it possible?

**Expected behaviour**
I would like to go into theses folders to update/create/delete/etc.

**What is happening instead?**
I have the this error message : _**This location can't be reached.**_

**Additional context**
Container created with docker-compose:
```
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1001:1001"
    ports:
      - 10000:8080
    volumes:
      - /home/quentin/filebrowser/data:/data
      - /home/quentin/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
```

filebrowser version : **2.10.0**

Example of symbolic link into the folder `/home/quentin/filebrowser/data`:
`livres -> ../../ubooquity/books/`

**Comment by alexisLefebvre** [comment]
Can you mount the folders directly as volumes?

**Comment by quentin-rey** [comment]
How can I mount multiple folders in one volume?
Or maybe I can mount multiple volumes that filebrowser can understand ? Like this:
```
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1001:1001"
    ports:
      - 10000:8080
    volumes:
      - /home/quentin/filebrowser/data:/data
      - /home/quentin/filebrowser/data2:/data2
      - /home/quentin/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
```

**Comment by alexisLefebvre** [comment]
It should work by defining different folders in the container:

```yaml
version: "3"

services:
  filebrowser:
    # …
    volumes:
      - /home/quentin/filebrowser/data:/srv/main
      - /home/quentin/filebrowser/data2:/srv/other
      - /home/quentin/videos:/srv/videos
      - /home/quentin/filebrowser/config:/config
    # …
```

`/srv` is the path used by filebrowser to read files: https://filebrowser.org/installation#docker

**Comment by quentin-rey** [comment]
I tried something like this:

```
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1001:1001"
    ports:
      - 10000:8080
    volumes:
      - /home/quentin/filebrowser/books:/srv/books
      - /home/quentin/filebrowser/comics:/srv/comics
      - /home/quentin/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
      - FB_ROOT=/srv
    restart: always
```

But when I launch the app it's empty

**Comment by alexisLefebvre** [comment]
I use the `filebrowser/filebrowser` image than read files in `/srv`, you use [another image](https://github.com/hurlenko/filebrowser-docker#docker) that read files in `/data`.

So let's use their configuration:

```yml
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1001:1001"
    ports:
      - 10000:8080
    volumes:
      - /home/quentin/filebrowser/books:/data/books
      - /home/quentin/filebrowser/comics:/data/comics
      - /home/quentin/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
```

It should work :crossed_fingers:
