### ISSUE TITLE
Possible 2.12 breaking change

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#1308]
**Description**
I upgraded from 2.11 to 2.12

**Expected behaviour**
Works without change

**What is happening instead?**
Proxy got 502

**Additional context**
Adding `-a 0.0.0.0` fixes it

**Comment by thost96** [comment]
Hi, I have the same problem. Also, container is by default now listening on port 8080 instead of port 80 as before.... Config file also seems not to be loaded anymore the this is my container output : 

```
2021/03/04 13:47:04 Listening on 127.0.0.1:8080
2021/03/05 07:19:41 No config file used
2021/03/05 07:19:41 Listening on [::]:8080
2021/03/05 07:31:18 Caught signal terminated: shutting down.
2021/03/05 07:19:43 Caught signal terminated: shutting down.
2021/03/05 07:31:18 accept tcp [::]:8080: use of closed network connection
2021/03/05 07:31:14 No config file used
```

**Comment by muxi** [comment]
Same here. Falling back to 2.11 works.

**Comment by ramiresviana** [comment]
The default Filebrowser config file for docker images was removed on last release, with the default config it will listen on address 127.0.0.1 port 8080. The Dockerfile was the EXPOSE instruction with 80 as value, even though that default Filebrowser port is 8080. I think that is an unwanted behavior and will be fixed.

**Comment by princemaple** [comment]
Forced me to make my config more robust 😂  so I guess I don't mind at all.

**Comment by o1egl** [comment]
Fixed in v2.12.1

**Comment by st0rm3rd** [comment]
I have this issue on v2.28.0. See below output from log in container.
Configuration seems to be fine as I do get the webUI, but gives me an intermittent webUI connection as it keeps coming on and off again. What causes the signal terminated and how to resolve this?

2024/04/13 21:44:52 Listening on [::]:80
2024/04/13 21:45:13 Caught signal terminated: shutting down.
2024/04/13 21:45:13 accept tcp [::]:80: use of closed network connection
2024/04/13 21:45:22 Using database: /filebrowser.db
2024/04/13 21:45:22 Using config file: /.filebrowser.json
2024/04/13 21:45:22 Listening on [::]:80
2024/04/13 21:45:42 Caught signal terminated: shutting down.
2024/04/13 21:45:42 accept tcp [::]:80: use of closed network connection
2024/04/13 21:45:45 Using database: /filebrowser.db
2024/04/13 21:45:45 Using config file: /.filebrowser.json
2024/04/13 21:45:45 Listening on [::]:80
2024/04/13 21:46:06 Caught signal terminated: shutting down.
2024/04/13 21:46:06 accept tcp [::]:80: use of closed network connection
2024/04/13 21:46:08 Using database: /filebrowser.db
2024/04/13 21:46:08 Using config file: /.filebrowser.json
2024/04/13 21:46:08 Listening on [::]:80

```
version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: Filebrowser
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    ports:
      - 9191:80
    volumes:
      - /share/Docker/Filebrowser/filebrowser.db:/filebrowser.db
      - /share/Docker/Filebrowser/.filebrowser.json:/.filebrowser.json
      - /:/srv   
    restart: always
```
