### ISSUE TITLE
Better doc for docker compose

### ISSUE THREAD

**Issue by Whisper40** [filebrowser/filebrowser#1318]
I want to install this application under docker via docker compose, but the documentation of the tool is very incomplete.
For a user who has not followed the X versions you have deployed, it is really difficult.
There is no example of use with docker compose, the few docs that can be found indicate that you can modify the environment variables, but again it is very partial and not enough.

My need is simple though...
I want to remove the authentication of the tool using noauth.

This is what i did : 
```
  filebrowser_{{ user }}:
    image: filebrowser/filebrowser:latest
    user: ${MYUID}:${MYGID}
    container_name: filebrowser_{{ user }}
    command: "--noauth"
    restart: unless-stopped
    labels:
...
    volumes:
      - $DATA_DIR/{{ user }}/data:/srv
      - type: bind
        source: $DATA_DIR/{{ user }}/config/filebrowser/database.db
        target: /database.db
      # - type: bind
      #   source: $DATA_DIR/{{ user }}/config/filebrowser/.filebrowser.json
      #   target: /.filebrowser.json
    environment:
      - PUID=${MYUID}
      - PGID=${MYGID}
      - TZ=${TZ}
    networks:
      - proxy
```

I tried with the command and it works, but i see another post that said that now we cannot use many parameters in the command line..
So i would like to know how we can customize the projet with dockercompose.
( I don't understand your "quick setup".. )

Thanks for help !
