### ISSUE TITLE
In docker with UID:GID 1000:1000, fails with "panic: mkdir  : permission denied"

### ISSUE THREAD

**Issue by astraios** [filebrowser/filebrowser#1382]
**Description**
When running in docker with a UID:GID 1000:1000, it won't start and is giving me:
```
filebrowser_1  | panic: mkdir  : permission denied
filebrowser_1  |
filebrowser_1  | goroutine 1 [running]:
filebrowser_1  | github.com/filebrowser/filebrowser/v2/cmd.python.func1(0x238d260, 0xc000179d70, 0x0, 0x3)
filebrowser_1  |        /home/runner/work/filebrowser/filebrowser/cmd/utils.go:93 +0x3d0
filebrowser_1  | github.com/spf13/cobra.(*Command).execute(0x238d260, 0xc000030090, 0x3, 0x3, 0x238d260, 0xc000030090)
filebrowser_1  |        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
filebrowser_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x238d260, 0xc00016ff58, 0x4075f0, 0x239d0d8)
filebrowser_1  |        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
filebrowser_1  | github.com/spf13/cobra.(*Command).Execute(...)
filebrowser_1  |        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
filebrowser_1  | github.com/filebrowser/filebrowser/v2/cmd.Execute()
filebrowser_1  |        /home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x2d
filebrowser_1  | main.main()
filebrowser_1  |        /home/runner/work/filebrowser/filebrowser/main.go:11 +0x32
filebrowser_filebrowser_1 exited with code 2
```
**Expected behaviour**
It should work.

**What is happening instead?**
It's bombing out with a panic error, not telling me which path it can't create, so I can't even check
if something is wrong with my FS

**How to reproduce?**
Use this composition:
```
version: "3.7"
services: 
  filebrowser:
    image: filebrowser/filebrowser:v2.14.1
    user: "1000:1000"
    command:
      - "--cache-dir=/data/cache"
      - "-d /data/database.db"
    volumes:
      # Filebrowser cache and DB
      - "/var/opt/filebrowser:/data"
    ports:
      - "8088:80"
```

I triple checked my bind mount paths and the posix permissions are set correctly.
Also, If I decide to use a simpler composition is still fails, with a different error but still permission related:

```
version: "3.7"
services: 
  filebrowser:
    image: filebrowser/filebrowser:v2.14.1
    user: "1000:1000"
    ports:
      - "8088:80"
```
Failing with:
```
filebrowser_1  | 2021/04/22 06:03:19 open /database.db: permission denied
```

Thanks for your help

**Comment by ramiresviana** [comment]
Filebrowser does not handle system permissions, it will just use the privileges of the process owner. Can you check if that configuration allows the user/process to access the volume?

**Comment by astraios** [comment]
Yes it does, I checked that multiple times. It looks like if the process is not root, it won't be able to create a directory inside the container. This is not even about the volumes I try to bind mount.

Let me know if you want me to run commands or tests to provide more inputs

**Comment by ramiresviana** [comment]
The Filebrowser image uses port 80 and creates the database in the / directory by default, to make it work with unprevileged user you have to change the port to a high number and place the database in a accessible location. For the database location parameter you need to use `-d=/data/database.db` instead of `-d=/data/database.db`.

If your directory permissions are correct, you should be able to use this:

```dockerfile
version: "3.7"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.14.1
    user: "1000:1000"
    command:
      - "--cache-dir=/data/cache"
      - "-d=/data/database.db"
      - "-p=8088"
    volumes:
      # Filebrowser cache and DB
      - "/var/opt/filebrowser:/data"
    ports:
      - "8088:8088"
```

**Comment by astraios** [comment]
Oh I see, so me using `-d /some/path` was not correct way to use the parameters. I tried what you suggested and ended up with something working. 

Quite nice.

Thanks

**Comment by ramiresviana** [comment]
@o1egl we can make Filebrowser run on unprivileged container by having it's own directory for the installation, instead of using root, and increasing the listening port number.

**Comment by astraios** [comment]
Seems like a good idea to me

**Comment by o1egl** [comment]
I will try to play with this. But a user still must provide the correct uid/gid to the docker container.

**Comment by ramiresviana** [comment]
#1390

**Comment by luandro** [comment]
I've tried:

```
version: "2.1"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    user: "1000:1000"
    command:
      - "--cache-dir=/config/cache"
      - "-d=/config/database.db"
      - "-p=8088"
    volumes:
      - "/var/opt/filebrowser:/data"
    ports:
      - "8088:8088"
```

And this continues producing permission denied for the database file.
