### ISSUE TITLE
Public Folder

### ISSUE THREAD

**Issue by hesaba** [filebrowser/filebrowser#1397]
**I need to create a public folder for all logged in users**

*Is there any solution to make a public folder for all users to use as a temporary folder? They want to share their files without creating any link*

**Comment by ramiresviana** [comment]
The folders available to users are controlled by the rules and scope attribute. You can use scope to set the base path accessible to  users, and rules to deny and allow access to a specific path or pattern.

**Comment by hesaba** [comment]
Thank you, it works by setting scope and regex rules.

**Comment by mrsharps** [comment]
I'm having the same issue.  I can read, but not write.  And sadly, I'm a bit of a windows guy trying to get this to run on Ubuntu Server.  

Here is the error I am seeing when I try to move a file:
`2021/12/10 05:47:16 /cool.file: 403<ip address> open /srv/subDir/cool.file: permission denied`

I set it up through portainer.  Here is my docker compose
```

---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 49153:80
    volumes:
      - /media/coolDirectory/:/srv
      - /home/mrsharps/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

Thankful for any suggestions?
