### ISSUE TITLE
Filebrowser never loads when reverse proxied

### ISSUE THREAD

**Issue by AnchorHRG** [filebrowser/filebrowser#1440]
**Description**
File browser sits on 3 dot loading screen when accessing URL.

**Additional context**
Log is showing Filebrowser is running and listening to port 8088
2021/06/19 20:53:10 Listening on [::]:8088

I am using SWAG reverse proxy:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name files.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app filebrowser;
        set $upstream_port 8088;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
Here is my Docker-compose:
```
version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - proxy-tier
    user: "1000:1000"
    command:
      - "--cache-dir=/data/cache"
      - "-d=/data/database.db"
      - "-p=8088"
      - "-c=/data/.filebrowser.json"
      - "-b=files.anchorhrg.com"
    volumes:
      - ./data:/data
    environment:
      - FB_BASEURL=files.***.com
    restart: always

networks:
  proxy-tier:
    external:
      name: Swag
```
Here is my .filebrowser.json:
```
{
  "port": 8088,
  "baseURL": "files.***.com",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```
I assigned the appropriate system permissions to the filebrowser directory. Any guidance would be greatly appreciated!
