### ISSUE TITLE
Dedicated directory for config and database to mount via docker-compose

### ISSUE THREAD

**Issue by yatadev** [filebrowser/filebrowser#1471]
**Is your feature request related to a problem? Please describe.**

- I would like to mount the config file and the database to have persistent storage. But this 2 files are in the root directory of the container.

**Describe the solution you'd like**

Put both files in a directory and they can easily be mounted to the outside of the container.

**Describe alternatives you've considered**

docker-compose does not mount a file if it is not there, so i cant mount the database and config to the outside.
You can create an empty file or copy the files from the container before starting... but that is no clear solution.
You can also just mount the root directory of the app to the outside, but thats not cool at all.

**Additional context**

docker-compose does create a directory if i try to mount a file which is not there on the host.

docker-compose file:

```
version: '3.1'

services:

  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: unless-stopped

    environment:
      - "TZ=Europe/Berlin"

    volumes:
      # Data to work on
      - /data/docker:/srv

      # does not work
      #- ./database.db:/database.db
      #- ./filebrowser.json:/.filebrowser.json
      #- ${PWD}/database.db:/database.db
```
