### ISSUE TITLE
Recaptcha in docker

### ISSUE THREAD

**Issue by Soneji** [filebrowser/filebrowser#1491]
I'm trying to setup recaptcha with docker-compose. I have tried using the `filebrowser.json` file, but I have read it is not supported for recaptcha currently. I also tried running the command in the container like this, but I get this error and it does not work.

```
docker-compose exec filebrowser sh
/ # ./filebrowser config set --auth.method=json  --recaptcha.key xxx --recaptcha.secret xxx
2021/07/31 19:44:00 timeout
```

Below is my compose file:
```yml
version: '3.3'
services:
    filebrowser:
        volumes:
            - '/data:/srv'
            - './database.db:/database.db'
            - './filebrowser.json:/.filebrowser.json'
        ports:
            - '8080:80'
        image: filebrowser/filebrowser
```

My `filebrowser.json` is default, although I did try to add these options to it, obviously it did not work.
```js
{
 // default options...
 "auth": {
    "method": "json"
  },
  "recaptcha": {
    "key": "xxx",
    "secret": "xxx"
  }

}
```
