### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by gcraenen** [filebrowser/filebrowser#1551]
I'm trying to get filebrowser up from a larger docker-compose. The service starts ok, but when I go to the url I get the 404 error. It is behind a traefik reverse proxy.

This is the compose part:

filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    user: "${PUID}:${PGID}"
    # ports:
    #   - $FILEBROWSER_PORT:8080
    volumes:
      - $DATADIR:/data
      - $DOCKERDIR/appdata/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    labels:
      - "traefik.enable=true"
      #HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME0`)"
      #Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      #HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=8080"

**Comment by gcraenen** [comment]
Further research. It is not getting an IP and the log gives "open /database.db: permission denied"

I cannot exec -tie into the docker to look at this.

**Comment by gcraenen** [comment]
After changing the docker-compose to:

filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    user: 0:0
    # ports:
    #   - $FILEBROWSER_PORT:8080
    volumes:
      - $DATADIR:/data
      - $DOCKERDIR/appdata/filebrowser:/config
      - $DOCKERDIR/appdata/filebrowser/filebrowser.db:/config/database.db
      - $DOCKERDIR/appdata/filebrowser/.filebrowser.json:/config/.filebrowser.json
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      #HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME0`)"
      #Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      #HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=8080"

The log says:

2021/09/11 14:02:38 Using config file: /.filebrowser.json
2021/09/11 14:02:38 Listening on [::]:80

The error when trying to connect now says: Bad gateway

**Comment by o1egl** [comment]
You have an issue with your router configuration. You should probably check traefik docs.

**Comment by gcraenen** [comment]
Did that, but I have no clue what's going wrong. All other dockers (40+) in th docker-compose with the same set of traefik labels are working perfectly. Too bad it's not working. Going to look for another app.

**Comment by dotsoltecti** [comment]
For some reason that I cannot figure out, I'm hitting the same problem (and have been trying to fix for the better half of a day) where I cannot get traefik to proxy my filebrowser container.

Although the same traefik-labels work well with other containers, traefik seems to refuse to proxy the filebrowser-container, resulting in a 404 when trying to access `https://fbrowser.<mydomain>`.

I am begging to suspect that I need to modify the settings in my `filebrowser.json` file but I am unsure in what way (baseurl,...)?

My docker-compose file:
```
version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:113"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.fbrowser.rule: "Host(`fbrowser.<mydomain>`)"
      traefik.http.routers.fbrowser.entrypoints: "https"
      traefik.http.routers.fbrowser.tls: "true"
      traefik.http.routers.fbrowser.service: "fbrowser"
      traefik.http.services.fbrowser.loadbalancer.server.port: "33123"
    volumes:
      - /volume1/config/filebrowser/filebrowser.db:/database.db
      - /volume1/config/filebrowser/filebrowser.json:/.filebrowser.json
      - /volume1/data:/srv

networks:
  web:
    external: true
```
My filebrowser.json:
```
{ 
  "port": 33123,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}   
```
The log file of the filebrowser-container:
```
2021/11/15 13:38:41 Using config file: /.filebrowser.json,
2021/11/15 13:38:41 Listening on [::]:33123
```
FTR, when I set the port to 80 in `filebrowser.json` I'm getting a permission denied, which leads me to think that the container itself is somehow doing something funky on the network-side of the configuration?
```
2021/11/15 13:40:35 Using config file: /.filebrowser.json,
2021/11/15 13:40:35 listen tcp :80: bind: permission denied
```
