### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by hacdias** [filebrowser/filebrowser#156]
- [x] Prettier search results
- [x] Search suggestions

~Search for similar words - see [smetrics](https://github.com/xrash/smetrics)~ (one day, later, maybe).

**Comment by hacdias** [comment]
@ToyoDAdoubi I've got some more stuff for you to translate:

```
search:
  images: Images
  music: Music
  pdf: PDF
  types: Types
  video: Video
```

Thank you 😄
