### ISSUE TITLE
Env variable doesn't seem to work

### ISSUE THREAD

**Issue by agneevX** [filebrowser/filebrowser#1589]
**Description**

Env variables that don't have a value don't seem to work in a Docker install

**Expected behaviour**

For it to work

**What is happening instead?**

Doesn't seem to take effect

```yml
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    environment:
# Doesn't work
      - FB_DISABLE_EXEC #tried FB_DISABLE_EXEC=true
# Works
      - FB_ROOT=/files
      - FB_CONFIG=/srv/config.json
      - FB_DATABASE=/srv/filebrowser.db
```

**Additional context**

**How to reproduce?**

**Files**
