### ISSUE TITLE
Unable to use traefik as a proxy for filebrowser docker container 

### ISSUE THREAD

**Issue by dotsoltecti** [filebrowser/filebrowser#1667]
**Description**
Traefik will not serve as a proxy for my filebrowser container (the router configuration isn't even showing up in the Traefik dashboard). The same traefik-labels do work for other docker containers. 

**Expected behaviour**
Traefik being able to proxy

**What is happening instead?**
Traefik is serving a "404 Page not found"

**Additional context**
This bug seems related to #1551. I am starting to suspect that I need to modify the settings in my `filebrowser.json` file but I am unsure in what way (baseurl,...)?

My docker-compose file:
```
version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:113"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.fbrowser.rule: "Host(`fbrowser.<mydomain>`)"
      traefik.http.routers.fbrowser.entrypoints: "https"
      traefik.http.routers.fbrowser.tls: "true"
      traefik.http.routers.fbrowser.service: "fbrowser"
      traefik.http.services.fbrowser.loadbalancer.server.port: "33123"
    volumes:
      - /volume1/config/filebrowser/filebrowser.db:/database.db
      - /volume1/config/filebrowser/filebrowser.json:/.filebrowser.json
      - /volume1/data:/srv

networks:
  web:
    external: true
```
My filebrowser.json:
```
{ 
  "port": 33123,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}   
```
The log file of the filebrowser-container:
```
2021/11/15 13:38:41 Using config file: /.filebrowser.json,
2021/11/15 13:38:41 Listening on [::]:33123
```
FTR, when I set the port to 80 in `filebrowser.json` I'm getting a permission denied (same as #152?), which leads me to think that the container itself is somehow doing something funky on the network-side of the configuration?
```
2021/11/15 13:40:35 Using config file: /.filebrowser.json,
2021/11/15 13:40:35 listen tcp :80: bind: permission denied
```

**Comment by dotsoltecti** [comment]
After investigating further, I'm thinking traefik is having trouble with the failing healthcheck

The Dockerfile has a healthcheck defined:
```
HEALTHCHECK --start-period=2s --interval=5s --timeout=3s \
  CMD curl -f http://localhost/health || exit 1
```
This is however counting on the fact that filebrowser is running on the standard port 80. As referenced in #152 this is not an option when using a reverse proxy like Traefik. So when running filebrowser on a different port, the healthcheck fails resulting in an 'unhealthy' container.

To point Traefik to a non-standard port, we need to use a loadbalancer. The loadbalancer seems to expect [a healthy container](https://doc.traefik.io/traefik/routing/services/#health-check). I'm suspecting Traefik is ignoring the filebrowser-container since it failing it's healthchecks when running on a non-standard port.

To me the solution seems to be to remove the healthcheck from the dockerfile?

**Comment by dotsoltecti** [comment]
Seems that I was on the right path: solving the healthcheck-issue stopped traefik from ignoring the filebrowser-container. The solution was to modify the healthcheck in my docker-compose file by including:
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8234/health"]
      interval: 30s
      timeout: 20s
      retries: 3
```
I'm leaving this issue open for the time being so that the developers can decide if they want to follow-up on this issue.

To help others my full docker-compose file is now as follows:
```
version: "3"

services:
  fbrowser:
    image: filebrowser/filebrowser
    container_name: fbrowser
    restart: unless-stopped
    user: "1000:113"
    volumes:
      - /volume1/config/filebrowser/filebrowser.db:/database.db
      - /volume1/config/filebrowser/filebrowser.json:/.filebrowser.json
      - /volume1/data:/srv
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.fbrowser.rule=Host(`fbrowser.<mydomain>`)
      - traefik.http.routers.fbrowser.entrypoints=https
      - traefik.http.routers.fbrowser.tls=true
      - traefik.http.routers.fbrowser.service=fbrowser
      - traefik.http.services.fbrowser.loadbalancer.server.port=8234
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8234/health"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  web:
    external: true
   
```
