### ISSUE TITLE
Cannot Move Files Between Volumes

### ISSUE THREAD

**Issue by spencerthayer** [filebrowser/filebrowser#1688]
The issue #1177 shouldn't be closed because commit #58835b7e535cc96e1c8a5d85821c1545743ca757 did not fix the problem.

```
2021/11/28 21:43:59 /torrents/The Three-Body Problem/: 500 192.168.0.11 read /data/torrents/The Three-Body Problem: is a directory
```

```yaml
version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    container_name: filebrowser
    privileged: true
    ports:
      - 4444:8080 #443:8080
    volumes:
      - /appdata/filebrowser:/config
      - /appdata/:/data/appdata
      - /media/Crucial/Media:/data/media
      - /media/Crucial/Torrents:/data/torrents
    environment:
      - FB_BASEURL=/data
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    restart: always
```
