### ISSUE TITLE
Performance and sharing files from folders containing large numbers of files (~4000)

### ISSUE THREAD

**Issue by menasamuel** [filebrowser/filebrowser#1689]
**Description**

Performance and sharing files from folders containing large numbers of files (~4000)

- Navigating to a folder containing a large number of files 
- find one specific file using search 
- share that one file only 

**Expected behaviour**

- displaying the list of files is fast
- searching for a file (instead of scrolling) is fast
- sharing that single file is easy to do

**What is happening instead?**

- displaying a list of files takes 1 minute 
- sharing from the search results page is not possible 
- attempting to share from the search results actually just attempts to preview the file
- dismissing the file preview starts listing the folder's contents again so takes another minute 

**Additional context**

- using docker container on synology nas 
- every other operation and feature is working perfectly and very performantly

**How to reproduce?**

- spin up docker container 
- mount to /srv a folder containing subfolders containing a large number of files (several thousand) 
- log in and navigate to folder containing large number of files 
- observe the slowness 
- try to share a single file halfway down the list (requires searching) 

**Files**

**Comment by menasamuel** [comment]
Suggest the following:
- a local cache file which can be stored in the folder used for config and can be invalidated and rebuilt as needed by admins
- allowing sharing from the search results screen

If the two above are implemented, this would be super ideal!

**Comment by niubility000** [comment]
1. Use "--disable-type-detection-by-header", 
for example:  .\filebrowser.exe -d .\filebrowser.db --disable-preview-resize --disable-type-detection-by-header --cache-dir .\cache
No matter how large your folder is, it will show up in 2 seconds.
2. This current version is hard to scroll down fast.  You can test my modified version:   https://gitee.com/niubilitypdj/filebrowser/releases/, it's using virtual listing. It can scroll down to anyplace in a second.    If necessary, I can make a PR when I have time. 
3. I think  we need to add a "share" button in the preview page.

**Comment by menasamuel** [comment]
Thanks @niubility000 
I added those params to my docker run command and managed to improve the performance of listing files greatly. I also mounted the cache directory so I can see the cache being populated which is great.

If the share button in the preview page is implemented, then there's no need to scroll fast as it can be done via the search feature which feels more natural than scrolling to me. Perhaps this issue should be re-opened as a feature request. I will mark this bug as closed and create a new feature for the share button to the preview page.

**Comment by xingoxu** [comment]
I'm sorry but is this still valid in v2.23.0？
I used it in the latest docker image (filebrowser/filebrowser:v2.23.0) but looks like no effect.

This is my docker-compose.yml and any advice?
```
version: "2.3"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2.23.0
    container_name: filebrowser
    user: 1000:100
    volumes:
      # data
      - /mnt/user:/srv
      # config
      - ./config/filebrowser.db:/database/filebrowser.db
      - ./config/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
    entrypoint: ["/filebrowser","--disable-preview-resize","--disable-type-detection-by-header","--cache-dir","/tmp"]
```
