### ISSUE TITLE
`v2.20.0` not saving settings

### ISSUE THREAD

**Issue by flavorgold1** [filebrowser/filebrowser#1731]
Here's my `docker-compose.yml` file:

```
version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
#    user: '1000:1000'
    restart: unless-stopped
    volumes:
      - /home/username:/srv
      - /home/username/filebrowser_management/config/settings.json:/config/settings.json
      - /home/username/filebrowser_management/database/database.db:/database/database.db
      - /home/username/filebrowser_management/ssl_certificate:/ssl_certificate
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT
      - FB_BASEURL=/
      - VIRTUAL_PORT=39274
    network_mode: "host"
```

I login as `admin/admin` and then change the theme and add users.

But, the settings changes just don't survive a full `docker-compose down` and `docker-compose up -d` routine.

I wasn't facing this issue with the previous version.
