### ISSUE TITLE
File editor font size configurability

### ISSUE THREAD

**Issue by timlinux** [filebrowser/filebrowser#1749]
**Is your feature request related to a problem? Please describe.**

My vision is not so great and the editor default font size is really small.

**Describe the solution you'd like**

As a reference, here is the font size in github's editor:

![image](https://user-images.githubusercontent.com/178003/147846442-62e4ba68-6baa-47e1-82a9-1bd61bbed129.png)

Now for comparison the font size in filebrowser's editor:

![image](https://user-images.githubusercontent.com/178003/147846425-07c15073-acd5-4a00-bc4b-a07222c6a4a9.png)

I appreciate that not everyone needs large fonts, but having an option to set the default font to a larger size (either in the settings UI or as a command line option) would be really useful.

I find that the editor font size also aesthetically really diverges from the rest of the Filebrowser UI which uses large text and icons, which are very aesthetically pleasing and usable.

**Describe alternatives you've considered**

BTW I know about using zoom in the browser, but it is quite inconvenient to use browser zoom as it blows up everything on the page reducing the usable screen real estate.

**Additional context**
None

**Comment by timlinux** [comment]
Oh I see my screenshots above are not very representative since github renders them larger or smaller depending on available space on the page....

**Comment by timlinux** [comment]
Added ruler to screenshots for scale...

**Comment by hernandito** [comment]
If you have a bit of css knowledge, you can follow the “branding” instructions and then edit the css file to adjust the font sizes, colors, etc.

https://filebrowser.org/configuration/custom-branding

Let me know if the above is enough to get you started. I will help you further. Also let me know if you use the light or dark theme in FileBrowser.

**Comment by timlinux** [comment]
@hernandito thank you for your reply (and for filebrowser which is an amazing project). I should have mentioned I already tried the custom.css route but I think I probably am not using the correct selector or something as it makes no difference to the font size. This is what I have in my custom css:

```css
.ace_editor {
    position: relative;
    overflow: hidden;
    padding: 0;
    font: 26px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
    direction: ltr;
    text-align: left;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```
