### ISSUE TITLE
Problem opening first page - Unexpected token '<' error is reported by Chrome

### ISSUE THREAD

**Issue by taimish** [filebrowser/filebrowser#1792]
**Description**

I deployed the app in a kubernetes cluster with nginx ingress controller.

**Expected behaviour**

App opens and works.

**What is happening instead?**

Files are downloaded but only wait animation opens:
![image](https://user-images.githubusercontent.com/33576807/151758789-3a25ecc4-3961-4654-9a42-002ed467f6c1.png)
Chrome console says:
```
chunk-vendors.fdfc012d.js:1 Uncaught SyntaxError: Unexpected token '<'
app.3becc02d.js:1 Uncaught SyntaxError: Unexpected token '<'
blob:https://cpq-dev…b06a-8c38bab5a88a:1 Manifest: property 'start_url' ignored, should be same origin as document.
```

Actually `chunk-vendors.fdfc012d.js` file starts with
```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><title>File Browser</title><link rel="icon" type="image/png" sizes="32x32" href="perftestsfb/static/img/icons/favicon-32x32.png">...
```
![image](https://user-images.githubusercontent.com/33576807/151763988-1cf5622a-d183-41f8-bac0-a2fd8f67c923.png)
I'm not good in frontend but that seems to be an HTML file with included script but not a pure script.

**Additional context**

I use image `filebrowser/filebrowser` and tried tags `latest` and several tags with version specified like `v2.20.0-amd64`.
The start command for the k8s deployment:
```
'echo "{\"port\": $PORT, \"baseURL\": \"$BASE_URL\", \"address\": \"$ADDRESS\", \"log\": \"$LOG\", \"database\": \"$DATABASE\", \"root\": \"$ROOT\"}" > /.filebrowser.json; cat .filebrowser.json; if test -f $DATABASE; then echo No initialization is needed; else echo Initializing the app; mkdir database; ./filebrowser config init; ./filebrowser users add admin $ADMIN_PASS; fi; ./filebrowser;'
```
This is for the `latest` tag. For other tags `/usr/bin/` is added before the app name. All the env vars are provided (see app log below).

Here is the k8s ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perftests
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - <INGRESS_DOMAIN_NAME>
    secretName: aks-ingress-tls
  rules:
  - host: <INGRESS_DOMAIN_NAME>
    http:
      paths:
      - path: /perftestsfb
        pathType: Prefix
        backend:
          service:
            name: perftests-fb
            port:
              number: 80
```
K8s services exist, networking works. Example from the nginx ingress controller logs:
```
10.22.16.128 - - [31/Jan/2022:07:57:47 +0000] "GET /perftestsfb/static/css/chunk-vendors.c7045283.css HTTP/1.1" 200 4527 "https://***.com/perftestsfb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" 628 0.002 [default-perftests-fb-80] [] 10.22.16.12:80 4534 0.004 200 f81f7781560c67cc4b1276e35b608579
```

Also app logs shows that everything is set up well:
```
Defaults:
  Scope:         .
  Locale:        en
  View mode:     list
  Single Click:  false
  Commands:      
  Sorting:
    By:   name
    Asc:  false
  Permissions:
    Admin:     false
    Execute:   true
    Create:    true
    Rename:    true
    Modify:    true
    Delete:    true
    Share:     true
    Download:  true

Auther configuration (raw):

{
  "recaptcha": null
}

ID  Username  Scope  Locale  V. Mode  S.Click  Admin  Execute  Create  Rename  Modify  Delete  Share  Download  Pwd Lock
1   admin     .      en      list     false    false  true     true    true    true    true    true   true      false  
2022/01/31 08:14:03 Using config file: /.filebrowser.json
2022/01/31 08:14:03 Listening on [::]:80
```

One more interesting detail - the app worked after the first deployment. It opened, I authenticated, browsed files and so on. But after I tried to implement a PVC for the DB path I started seeing this error. I rolled all changes back (removed PVC - DB is initialized each container start) - but the error persists.

**How to reproduce?**

Make the same deployment in k8s.

**Files**
