### ISSUE TITLE
Admin Password keeps resetting

### ISSUE THREAD

**Issue by ken8521** [filebrowser/filebrowser#1838]
I installed Filebrowser in a container, and it works as expected.  The problem comes when the container updates, restarts, or the compose file is ran again for updates.. my admin password resets.  This is an issue because I reverse proxy file browser through my domain, and if watchtower pulls an update and I don't know it or even the container restarts... someone who comes across it could easily log in with the default credentials.  I'm assuming I'm missing something here... but I can't find what.

  version: "2"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser  
    volumes:
      - /path/to:/data
      - /path/to/data:/srv
    ports:
      - 8080:80
    restart: unless-stopped 

Oddly enough, I just noticed the data folder is never written to.. it's always empty, so I think that might be part of the problem (maybe my paths are wrong.. but that was the instructions I found online).  For now I've taken it off line until I can figure this out.

Thanks for any help you can offer.

**Comment by ramiresviana** [comment]
Filebrowser does not make use of /data directory. When the container is destroyed, all files on it are deleted. User credentials are stored on the database file, you want to ensure that this file is persisted on container changes. For more information, check the documentation (https://filebrowser.org/) and Dockerfile (https://github.com/filebrowser/filebrowser/blob/master/Dockerfile).

**Comment by mptpro** [comment]
I have the same problem, whenver the Docker container is updated the Admin user resets, and other users are destroyed. Other settings, such as file paths, are retained.  I am not using a /data directory.

**Comment by DCMarine** [comment]
Same problem here, plus all created user accounts are removed, and any customizations made. 

after doing some digging I found the problem.    the database is being mapped incorrectly (because we followed the instructions).    The below is my docker run command, as you can see I had to map the database to a different location.

```
docker run -d --init \
    --restart=unless-stopped \
    -p 80:80 \
    -e TZ=America/New_York \
    -v /opt/filebroswer/files:/srv \
    -v /opt/filebroswer/database.db:/database.db \
    -v /opt/filebroswer/settings.json:/config/settings.json \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    --name filebrowser \
    filebrowser/filebrowser:latest
```

**Comment by jame25** [comment]
I also have this issue. Service works as expected, until I restart the container, then all settings are lost.

Here is my docker compose:
```
  filebrowser:
    image: filebrowser/filebrowser:latest
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/hdd/Files:/srv
      - /home/plex/Docker/filebrwsr/database.db:/database/database.db
      - /home/plex/Docker/filebrwsr/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
```
