### ISSUE TITLE
Move Config and Database to singular folder for docker

### ISSUE THREAD

**Issue by newhinton** [filebrowser/filebrowser#1842]
**Is your feature request related to a problem? Please describe.**

Starting the dockercontainer requires preparations that are unexpected and non trivial.

**Describe the solution you'd like**
Both the config json and the database should be moved to a directory (eg. /data). This directory can then be exposed as a volume. The configfile should be created if nonexistent. For that the docker/root/defaults/settings.json need to reflect the new databasename, and the binary needs to try to read the config (or use none when no one is provided)

This way a lot of failuremodes are removed when using the docker image, and it gets quite a bit easier to use.

A docker-compose file could look like this then:
```
version: '3.3'
services:
    filebrowser:
        volumes:
            - '/srv:/srv'
            - '/data:/data'
        ports:
            - '8090:80'
```
