### ISSUE TITLE
Can't access to WebUI -- ERROR: Cannot assign requested address

### ISSUE THREAD

**Issue by thibaudbrg** [filebrowser/filebrowser#1858]
**Description**

I'm trying to implement the filebrowser compose file but without success... I cannot reach the web page.
My Server's IP is 192.168.1.2 and I've already tried to change the default port (80) of filebrowser with a bunch of others.

**My logs are:**

```
today at 22:53:29[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
today at 22:53:29[s6-init] ensuring user provided files have correct perms...exited 0.
today at 22:53:29[fix-attrs.d] applying ownership & permissions fixes...
today at 22:53:29[fix-attrs.d] done.
today at 22:53:29[cont-init.d] executing container initialization scripts...
today at 22:53:29[cont-init.d] 01-envfile: executing... 
today at 22:53:29[cont-init.d] 01-envfile: exited 0.
today at 22:53:29[cont-init.d] 02-tamper-check: executing... 
today at 22:53:29[cont-init.d] 02-tamper-check: exited 0.
today at 22:53:29[cont-init.d] 10-adduser: executing... 
today at 22:53:29
today at 22:53:29-------------------------------------
today at 22:53:29          _         ()
today at 22:53:29         | |  ___   _    __
today at 22:53:29         | | / __| | |  /  \
today at 22:53:29         | | \__ \ | | | () |
today at 22:53:29         |_| |___/ |_|  \__/
today at 22:53:29
today at 22:53:29
today at 22:53:29Brought to you by linuxserver.io
today at 22:53:29-------------------------------------
today at 22:53:29
today at 22:53:29To support LSIO projects visit:
today at 22:53:29https://www.linuxserver.io/donate/
today at 22:53:29-------------------------------------
today at 22:53:29GID/UID
today at 22:53:29-------------------------------------
today at 22:53:29
today at 22:53:29User uid:    1027
today at 22:53:29User gid:    100
today at 22:53:29-------------------------------------
today at 22:53:29
today at 22:53:29[cont-init.d] 10-adduser: exited 0.
today at 22:53:29[cont-init.d] 20-config: executing... 
today at 22:53:29[cont-init.d] 20-config: exited 0.
today at 22:53:29[cont-init.d] 90-custom-folders: executing... 
today at 22:53:29[cont-init.d] 90-custom-folders: exited 0.
today at 22:53:29[cont-init.d] 99-custom-files: executing... 
today at 22:53:29[custom-init] no custom files found exiting...
today at 22:53:29[cont-init.d] 99-custom-files: exited 0.
today at 22:53:29[cont-init.d] done.
today at 22:53:29[services.d] starting services
today at 22:53:29[services.d] done.
today at 22:53:302022/03/09 22:53:30 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:30 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:30 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:30 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:30 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:30 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:31 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:31 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:31 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:31 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:31 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:31 listen tcp 192.168.1.2:80: bind: cannot assign requested address
today at 22:53:302022/03/09 22:53:31 Using config file: /config/settings.json
today at 22:53:302022/03/09 22:53:31 listen tcp 192.168.1.2:80: bind: cannot assign requested address

```

**My settings.json file is:**

```
{
  "port": 80,
  "baseURL": "",
  "address": "192.168.1.2",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/volume1"
}
```

and my docker-compose.yml file is (`PGID`, `PUID`, `networks:t2_proxy`,`no-new-privilege:true`, `restart:unless_stopped` are in my common-keys and work correctly for other containers)

```
  # File Browser - Explorer
  filebrowser:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "$FILEBROWSER_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/filebrowser/settings.json:/config/settings.json
      - $DOCKERDIR/appdata/filebrowser/filebrowser.db:/config/filebrowser.db
      - /volume1/:/volume1
    environment:
      <<: *default-tz-puid-pgid
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`files.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"
```
