### ISSUE TITLE
Cannot see my folders

### ISSUE THREAD

**Issue by thibaudbrg** [filebrowser/filebrowser#1861]
Hello, 
I'm running filebrowser with a docker-compose on my DS920+ Synology and I cannot access to my folders..
Here's a picture of what I have:
![Screenshot 2022-03-10 221603](https://user-images.githubusercontent.com/73235385/157756283-d40b17d3-6331-4db6-9770-62ca04035841.png)
There are only two folders (and I don't know what they are), I cannot open them. Also I can't create any file or folder.
I just have access to the `run` file:
```
#!/usr/bin/with-contenv bash

exec s6-setuidgid abc filebrowser -c /config/settings.json -d /database/filebrowser.db;
```
See the logs when I want to create a folder/file:
```
today at 22:10:322022/03/10 22:10:32 Using config file: /config/settings.json
today at 22:10:322022/03/10 22:10:32 Listening on [::]:8234
today at 22:10:502022/03/10 22:10:50 /sdn/: 403 192.168.90.1 mkdir /run/s6/services/filebrowser/sdn: permission denied
today at 22:11:232022/03/10 22:11:23 /sdfbnb/: 403 192.168.90.1 mkdir /run/s6/services/filebrowser/sdfbnb: permission denied
today at 22:11:322022/03/10 22:11:32 /ezgzbn/: 403 192.168.90.1 mkdir /run/s6/services/filebrowser/ezgzbn: permission denied
```
Here is my` settings.json:`
```
{
  "port": 8234,
  "address": "",
  "database": "/etc/database.db",
  "scope": "/srv",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": []
}
```
My `docker-compose.yml`:
```
filebrowser:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    # Port needs to be open in local so that healthcheck (see below) works correctly for traefik instance
    ports:
      - "8234:8234"
    volumes:
      - $DOCKERDIR/appdata/filebrowser/:/config/
      - $DATADIR/:/data
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
```
(My `network `is definded in the `common-keys-core` section).

Does someone experienced the same behavior?
