### ISSUE TITLE
docker-compose don't save Usernames and Passwords

### ISSUE THREAD

**Issue by phillipunzen** [filebrowser/filebrowser#1898]
**Description**
I want to create a docker-compose Application.
The container should automatically restart the container with the new image via Watchtower when an update has come out. The container also restarts, it only does not keep the login data and always uses the admin/admin login data after a restart. The user data is not persistent. New users are also deleted.

**Expected behaviour**
I want to have the login data persistent.

**What is happening instead?**
No Error Message.
Filebrowser don't write any data in the filebrowser.db
But the File is mapped to the container

**Additional context**
Server: Debian 11
Docker and Docker-Compose latest Versions

**How to reproduce?**
1. Create the docker-compose file
```
version: '3.1'

networks:
  traefik:
    external: true
  mdb:
    external: true

services:
 filebrowser:
  container_name: filebrowser
  image: filebrowser/filebrowser:latest
  volumes:
    - ./file-data:/srv
    - ./filebrowser.db:/database/filebrowser.db
    - ./settings.json:/config/settings.json
  networks:
    - traefik
    - mdb
  restart: always
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.manuals.entrypoints=http"
    - "traefik.http.routers.manuals.rule=Host(`manuals.DOMAIN`)"
    - "traefik.http.middlewares.manuals-https-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.manuals.middlewares=manuals-https-redirect"
    - "traefik.http.routers.manuals-secure.entrypoints=https"
    - "traefik.http.routers.manuals-secure.rule=Host(`manuals.DOMAIN`)"
    - "traefik.http.routers.manuals-secure.tls=true"
    - "traefik.http.routers.manuals-secure.tls.certresolver=http"
    - "traefik.http.routers.manuals-secure.service=manuals"
    - "traefik.http.services.manuals.loadbalancer.server.port=80"
    - "traefik.docker.network=traefik"
    - "traefik.http.routers.manuals-secure.middlewares=secHeaders@file"
```
2. Create the settings.json
```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

Create the filebrowser.db
`touch filebrowser.db`

Start the docker container
`docker-compose up -d`

**Comment by ramiresviana** [comment]
I recommend you to check your server logs, it provides useful information. Looks like the settings file is not being read, Filebrowser will look for a file called `.filebrowser.{json, toml, yaml, yml}`, check the documentation at https://filebrowser.org/cli/filebrowser

**Comment by badi95** [comment]
I'm having the same issue. After changing the user from admin to my user I cat filebrowser.db and it doesn't have anything in it. Seems like my filebrowser.db file isn't getting updated.

**Comment by badi95** [comment]
```
docker logs filebrowser
2022/06/06 18:36:03 Using config file: /.filebrowser.json
2022/06/06 18:36:03 Listening on [::]:80
2022/06/06 18:36:06 /api/renew: 401 64.132.151.2 <nil>
```
Seem to be using /.filebrowser.json instead of my specified settings.json

**Comment by badi95** [comment]
For a workaround I ran
`docker exec filebrowser cp /config/settings.json /.filebrowser.json`
After restarting the container it starts to save to config/filebrowser.db
This will have to be reissued after each update, but at least it saves the usernames and passwords for now.

**Comment by sandros94** [comment]
As @ramiresviana sugested, a correct setup of the compose environment variables fixes the inconvinience.
```
    environment:
      FB_CONFIG: "/filebrowser.json"
      FB_DATABASE: "/database/filebrowser.db"
```

**Comment by badi95** [comment]
Hmm, I'm still having the issue after setting the environment variables
docker-compose file:
```
   environment:
      - PUID=1000
      - PGID=1000
      - FB_CONFIG="/config/settings.json"
      - FB_DATABASE="/database/filebrowser.db"
```
```
docker exec -it filebrowser env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5469e2658ea7
TERM=xterm
PUID=1000
PGID=1000
FB_CONFIG="/config/settings.json"
FB_DATABASE="/database/filebrowser.db"
HOME=/root
```
```
docker logs filebrowser
2022/07/05 19:31:05 Using config file: /.filebrowser.json
2022/07/05 19:31:06 Listening on [::]:80
2022/07/05 19:31:12 /api/renew: 401 64.132.151.2 <nil>
2022/07/05 19:31:17 /api/login: 403 64.132.151.2 <nil>
2022/07/05 19:36:29 Caught signal terminated: shutting down.
2022/07/05 19:36:29 accept tcp [::]:80: use of closed network connection
2022/07/05 19:36:30 Using config file: /.filebrowser.json
2022/07/05 19:36:30 Listening on [::]:80
```

**Comment by sandros94** [comment]
> Hmm, I'm still having the issue after setting the environment variables docker-compose file:
> 
> ```
>    environment:
>       - PUID=1000
>       - PGID=1000
>       - FB_CONFIG="/config/settings.json"
>       - FB_DATABASE="/database/filebrowser.db"
> ```
> 
> ```
> docker exec -it filebrowser env
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> HOSTNAME=5469e2658ea7
> TERM=xterm
> PUID=1000
> PGID=1000
> FB_CONFIG="/config/settings.json"
> FB_DATABASE="/database/filebrowser.db"
> HOME=/root
> ```
> 
> ```
> docker logs filebrowser
> 2022/07/05 19:31:05 Using config file: /.filebrowser.json
> 2022/07/05 19:31:06 Listening on [::]:80
> 2022/07/05 19:31:12 /api/renew: 401 64.132.151.2 <nil>
> 2022/07/05 19:31:17 /api/login: 403 64.132.151.2 <nil>
> 2022/07/05 19:36:29 Caught signal terminated: shutting down.
> 2022/07/05 19:36:29 accept tcp [::]:80: use of closed network connection
> 2022/07/05 19:36:30 Using config file: /.filebrowser.json
> 2022/07/05 19:36:30 Listening on [::]:80
> ```

Did you bind the volume for the  settings.json?
In my case, just as a precaution, I renamed the file to filebrowser.json since I wasn't using the filebrowser:s6 image, as per [doc](https://filebrowser.org/installation#docker)

**Comment by GitTworn** [comment]
Anyone found a solution to this yet?

**Comment by sandros94** [comment]
> Anyone found a solution to this yet?

As already documented in this issue, setting a bind to an existing config json is quite enough:

docker-compose.yml:
```
user: 1000:1000
environment:
  FB_CONFIG: "/filebrowser.json"
  FB_DATABASE: "/database/filebrowser.db"
volumes:
  - {PathOrVolumeToFileBrowserRoot}:/srv
  - {PathToFileBrowserRoot}/filebrowser.db:/database/filebrowser.db
  - {PathToFileBrowserRoot}/filebrowser.json:/filebrowser.json
```

filebrowser.json:
```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```
