### ISSUE TITLE
Double Click?

### ISSUE THREAD

**Issue by devilliersjohnny** [filebrowser/filebrowser#2020]
**Description**
Attempting to change from double clicks to single click under profile settings... however when "UPDATE"  is clicked get a "000 No connection" error in the bottom right corner

**Expected behaviour**
I expected the software to change from double clicks to single clicks 

**What is happening instead?**
"000 No connection"

**Additional context**

**How to reproduce?**
Install on Ubuntu 22.04 hosting docker... fresh install with SWAG webserver (NGINX) based reverse proxy. Install using
```
---
version: '3'
services:
# Filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./settings.json:/config/settings.json
    ports:
      - 8080:80
```
* open web browser ( localhost:8080 ) log in
* click settings
* enable checkbox ( Use single clicks to open files and directories )
* click update

**Files**
