### ISSUE TITLE
Download ERROR> write: connection reset by peer

### ISSUE THREAD

**Issue by aronmgv** [filebrowser/filebrowser#2027]
While downloading a folder (17GB) as zip containing multiple video/text files it never successfully completes the download. In the logs I see ` write: connection reset by peer`.. When similar folder is about 2GB size, it finishes fine.. It fails the same way when trying to download single large file (no compression, direct download of file)..

When trying to download same file (77GB) via nginx it finishes without problems..

Using as docker setup and latest version 2.22.3..

```yml
  filebrowser:
    container_name: media.filebrowser.52902
    image: filebrowser/filebrowser:latest
    restart: always
    ports:
      - 52902:80
    volumes:
      - $PWD/filebrowser/settings.json:/config/settings.json
      - $PWD/filebrowser/filebrowser.db:/database/filebrowser.db
      - /lvm/raid/private/media:/srv/media:ro
      - /lvm/raid/private/data:/srv/data:ro
    environment:
      - FB_NOAUTH=noauth
      - FB_CONFIG=/config/filebrowser.json
      - FB_DATABASE=/database/filebrowser.db
```

Any suggestions what it could be? Thanks a lot
