### ISSUE TITLE
Add theme select (dark CSS inside)

### ISSUE THREAD

**Issue by francislavoie** [filebrowser/filebrowser#208]
I love the default look, but I'd love a dark theme even more. Are there plans to make a few basic themes built-in? Or has someone already made a dark theme I could use? I'm not too sure where I should be looking.

Thanks!

**Comment by hacdias** [comment]
I don't know if someone had made a dark theme. However, if you're willing to, you can build your own theme and add the CSS on **Settings**.

**Comment by francislavoie** [comment]
I ended up tossing together a dark theme. Here's an example:

![](https://i.imgur.com/kElFKU0.png)

```css
body, #login {
  background-color: #303030;
}

header {
  background-color: #1b1b1b;
}

.action,
#breadcrumbs,
#breadcrumbs span,
.dashboard #nav,
#listing.mosaic h2,
#login h1 {
  color: rgba(255, 255, 255, 0.7);
}

#listing.list .item.header {
  color: rgba(255, 255, 255, 0.7);
  background: #616161;
}

#listing.list .item,
#listing.mosaic .item {
  background-color: #424242;
  color: rgba(255, 255, 255, 0.7);
}

.dashboard {
  background: #424242;
  color: rgba(255, 255, 255, 1.0);
}

select,
textarea,
input,
.dashboard textarea,
.dashboard #locale,
.dashboard input[type=password],
.dashboard input[type=text] {
  background: #212121;
  color: rgba(255, 255, 255, 0.9);
  border-color: #303030;
}

select,
.dashboard input[type=password],
.dashboard input[type=text],
.dashboard select {
  padding: 8px;
}

#search #input {
  background-color: #424242;
  color: rgba(255, 255, 255, 0.7);
}

#search.active #input>.action i,
#search.active input,
#search.active #input,
#login input[type=password], #login input[type=text] {
  background-color: #303030;
  color: rgba(255, 255, 255, 0.7);
}

#search #result {
  background-color: #212121;
  color: rgba(255, 255, 255, 0.7);
}

#search #result .boxes,
.card {
  background-color: #424242;
  padding: 0 15px 15px 15px;
}

#search #result .boxes h3,
.card h2,
.card h3,
.card p,
.card-content {
  color: rgba(255, 255, 255, 0.7);
}

#nav li {
  padding-top: 1em !important;
}

nav.active, #dropdown.active {
    background-color: rgb(51, 51, 51);
}

#file-selection {
    background: #303030;
}
```

@hacdias if you look at the spots I added padding, I'd suggest considering using those in your base theme, to give a few of the elements a bit more room to breathe. The rest is just color changes.
