### ISSUE TITLE
Constant write disk activity of file browser docker container

### ISSUE THREAD

**Issue by lbalogh** [filebrowser/filebrowser#2094]
**Description**

I'm running File Browser in Docker on my Synology.

On the Synology, I noticed a constant write disk activity of about 300 KB/s, and after investigation, I've pin pointed the problem to the filebrowser container : as soon as I stop it, write activity on disk goes to near 0 KB/s, even with 10 other containers running. As soon as I restart the filebrowser container, constant write activity start again.

**Expected behaviour**

File Browser should not write constantly on disk. It should be "idle" when nothing happens.

**What is happening instead?**

When my file browser container is started, I have a constant write activity on my Synology (about 300 KB/s).

**Additional context**

![image](https://user-images.githubusercontent.com/6897141/185871372-b4e3ff8f-2fd5-4fe5-8bf8-db8e96ae3a11.png)

**How to reproduce?**

Here is my docker compose file:

```
version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./files:/srv
      - ./config/database.db:/database.db
    ports:
      - 8088:80
    logging:
      driver: 'none'

networks:
  net:
```

I started it with `docker compose up -d`.

I tried to comment the "logging driver : none" line but the logs show nothing interesting:

![image](https://user-images.githubusercontent.com/6897141/185871795-09cc84d9-dca5-4f42-a5ef-1882220ef003.png)
