### ISSUE TITLE
tls/ssl issue in docker container with certbot

### ISSUE THREAD

**Issue by martinmiglio** [filebrowser/filebrowser#2120]
I am trying to host filebrowser over https through the linuxserver docker container using docker-compose.
After setting a bind to my cert and key, then specifying their locations in the environment variables, I am met with `open /ssl/cert.pem: no such file or directory`.

I would like to use this bind so I can use my keys generated by certbot.

My docker-compose file:
```
services:
  filebrowser:
    image: filebrowser/filebrowser:s6  
    ports:
      - 40405:8080
    restart: unless-stopped
    environment:
      FB_CERT: /ssl/cert.pem
      FB_KEY: /ssl/privkey.pem
    volumes:
      - /mnt/bay1/atm/data:/srv
      - type: bind
        source: /etc/letsencrypt/live/MY.DOMAIN.HERE
        target: /ssl
      - type: bind
        source: /mnt/bay1/filebrowser/db/atm.db
        target: /database/filebrowser.db
      - type: bind
        source: /mnt/bay1/filebrowser/settings/atm.json
        target: /config/settings.json

```
Attaching to the container and running `ls /ssl`:
```
root@2bdb4a75e668:/# ls -n /ssl
-rw-r--r-- 1 0 0  692 Mar  5  2022 README
lrwxrwxrwx 1 0 0   44 Sep  2 03:37 cert.pem -> ../../archive/MY.DOMAIN.HERE/cert5.pem
lrwxrwxrwx 1 0 0   45 Sep  2 03:37 chain.pem -> ../../archive/MY.DOMAIN.HERE/chain5.pem
lrwxrwxrwx 1 0 0   49 Sep  2 03:37 fullchain.pem -> ../../archive/MY.DOMAIN.HERE/fullchain5.pem
lrwxrwxrwx 1 0 0   47 Sep  2 03:37 privkey.pem -> ../../archive/MY.DOMAIN.HERE/privkey5.pem
```
My filebrowser settings.json:
```
root@2bdb4a75e668:/# cat config/settings.json 
{
  "port": 8080,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

I suspect this issue has to deal with the symbolic link or permissions but I am unable to resolve it.
