### ISSUE TITLE
"auth.method=noauth" in Docker Compose

### ISSUE THREAD

**Issue by spencerthayer** [filebrowser/filebrowser#2359]
I would like to request that File Browser be configurable via the docker compose file. Right now one has to run `filebrowser config set --auth.method=noauth` after every update of filebrowser.  It would be better and more in line with the spirit of docker compose to allow configuration to be passed via the compose file.

**Comment by jacksgt** [comment]
Hey there, 
I was thinking exactly the same!

It turns out that you can already do this by simply setting the `FB_NOAUTH=true` environment variable.

This is not documented in the authentication section, but in the command-line options page:

> The environment variables are prefixed by "FB_" followed by the option name in caps. So to set "database" via an env variable, you should set FB_DATABASE.

https://filebrowser.org/cli/filebrowser

**Comment by spencerthayer** [comment]
So @jacksgt it would look like the following?

```
---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    ## privileged: true
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /<FILEPATH>/filebrowser.db:/database.db
      - /<DISKPATH>/srv/<DISK>
    environment:
      - FB_NOAUTH=true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```
