### ISSUE TITLE
listen tcp :80: bind: permission denied

### ISSUE THREAD

**Issue by Pingblue** [filebrowser/filebrowser#2424]
I'm running the Linuxserver s6 Docker image but after every build I receive the bind to port error.

```
2023/04/21 18:26:20 listen tcp :80: bind: permission denied
```

Is CAP_NET_BIND_SERVICE not required in the Dockerfile for binding to ports below 1024?

```
RUN apk add libcap && setcap 'cap_net_bind_service=+ep' /usr/bin/filebrowser
```

**Comment by longestmt** [comment]
I'm having the same issue. I've changed every configuration of the internal/external ports and it insists on listening to port 80 for some reason.

**Comment by zorbaTheRainy** [comment]
This is closed but I suffered the same problem and found an answer.
I'll leave it here, hoping it helps someone else.

The needed command in the container to allow port 80 to be bound is: 
`apk add libcap && setcap 'cap_net_bind_service=+ep' /usr/bin/filebrowser`

You can log into the container and run this manually, but that doesn't help much as it is a 1 time solution.

For those of you using the S6-overlay docker file, the startup script is located at `/etc/cont-init.d/20-config` and any files located in `/etc/cont-init.d` will be executed.  No need for `Entrypoint` in the compose.yaml.
See the [S6-Overlay documentation](https://github.com/just-containers/s6-overlay?tab=readme-ov-file#init-stages)

I create a file named `19-fix_80_bind` in my local/host filesystem and added the needed line.  Then I mount the `19-fix_80_bind` file into the container.

The `19-fix_80_bind` file looks like:
```
#!/usr/bin/with-contenv bash

# fix bind 80 issue
apk add libcap && setcap 'cap_net_bind_service=+ep' /usr/bin/filebrowser
```

And the docker compose.yaml file looks like
```
---
version: "2.1"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2.30.0-s6
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - PUID=1027
      - PGID=100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/filebrowser/settings.json:/config/settings.json
      - /docker/filebrowser/filebrowser.db:/database/filebrowser.db 
      - /docker/filebrowser/19-fix_80_bind:/etc/cont-init.d/19-fix_80_bind # this fixes the port 80 non-bind issue
      - /my_files_to_serve:/srv
    ports:
      - 8080:80
```
