### ISSUE TITLE
Container not starting up when using non-root user

### ISSUE THREAD

**Issue by PmNz8** [filebrowser/filebrowser#2435]
**Description**
When trying to run docker container as non-root user, the container logs info:
**2023/04/28 12:34:39 open /database.db: permission denied**
and shuts down.

**Expected behaviour**
Expect container being able to run using non-root user.

**What is happening instead?**
Container does not start up properly and shuts down.

**Additional context**
Running Docker on QNAP NAS TS-233 using Container Station.
My docker-compose.yml is as follows:
```
version: '3.3'
services:
    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        volumes:
            - /share/CACHEDEV1_DATA/Kontenery/filebrowser/srv:/srv
            - /share/CACHEDEV1_DATA/Kontenery/filebrowser/filebrowser.db:/database/filebrowser.db
            - /share/CACHEDEV1_DATA/Kontenery/filebrowser/settings.json:/config/settings.json
        environment:
            - PUID=1003
            - PGID=100
        user: 1003:100
        ports:
            - '18080:80'
```
User 1003 is non-root user and has write/read permission to whole /share/CACHEDEV1_DATA/Kontenery/ directory (and child folders/files) and is the owner of filebrowser directory and its child files/folders.
All file uploaded when running container without 
`user: 1003:100 `
are uploaded as admin (root user).

**How to reproduce?**
Run container using non-root user.
