### ISSUE TITLE
Filebrowser error when starting - operation not permitted

### ISSUE THREAD

**Issue by Surgical17** [filebrowser/filebrowser#2458]
**Description**
Filebrowser container not running correctly with the following error:

**Expected behaviour**

**What is happening instead?**
/filebrowser: operation not permitted

**Additional context**
I have used this container before. SO I am aware that I have to manually create the db. So I did use "sudo touch database.db" in teh correct location. I also used chmod -R 777 on both the source folder locations and the db file locations to ensure it does have the permissions. I also did try the root permissions and my user permissions

**How to reproduce?**
Docker Compose:
---
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 0:0
    ports:
      - 8099:80
    volumes:
      - /home/myuser/DockerCompose/:/srv
      - /home/myuser/DockerCompose/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

**Comment by Glareascum** [comment]
I'm not very into rootless docker, but I assume that specifying user: 0:0 in your compose file you are trying to run the container rootless, so by creating the db with sudo it results with no permissions.

**Comment by Surgical17** [comment]
> I'm not very into rootless docker, but I assume that specifying user: 0:0 in your compose file you are trying to run the container rootless, so by creating the db with sudo it results with no permissions.

To add to this. Setting the Perms to 0:0 does allow Filebrowser to access everything as root (It works on other Ubuntu systems that I have deployed it on) But does not work in this case. If I change the perms to 1000:1000 as an example its the same issue. I have deployed Filebrowser on 5 other systems. First time I am running into this issue and looking for advice

**Comment by JamesonWelch** [comment]
I'm having the same issue and have had it in past build attempts.

All attempts are producing the log output:
```bash
exec /filebrowser: operation not permitted
```

My docker-compose.yaml file:
```yaml
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /path/to/filebrowser/srv:/srv
      - /path/to/filebrowser/filebrowser.db:/database.db
      - /path/to/filebrowser/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

The user and group ID's are the same as the user I'm building the container with. I have it running in a Ubuntu Server VM hosted on Proxmox. 

I've tried creating the files `filebrowser.db`, `.filebrowser.json` and `srv/` under root and non-root. I've tried the `docker run` command from the documentation, running the docker-compose commands on root and non-root, all getting the same result. 

Is there a certain protocol on what files to create under root/non-root? Or do I need to run docker under root to get it to work?

I have a good amount of experience with Docker and sometimes mounted volumes take me a bit to connect but I've tried everything I can think of and always getting the same error.
