### ISSUE TITLE
Docker volume created has an erroneous name instead of human-friendly like other containers

### ISSUE THREAD

**Issue by mackonsti** [filebrowser/filebrowser#2505]
**Description**
I am using OpenMediaVault `6.4.4-1 (Shaitan)` with Docker `docker-ce 5:24.0.2-1~debian.11~bullseye` installed and running just fine.

I have installed `filebrowser:latest` image and then created container via a YML file.

I have set some parameters and launched container successfully.

Upon first launch, the Filebrowser code creates a Docker Volume with a name that is not human-readable like other containers e.g. Portainer.

&nbsp;
**Expected behaviour**
The **Volume** name created should show something like `filebrowser_data` as its name, just like `portainer_data` did.

&nbsp;
**What is happening instead?**
Instead, I get this volume name:
`d09c2d6fa9fbb5a9fcd44257f020a25422d22f0d8d3c99e2422f80a9deb5704a`
With this mount point:
`/var/lib/docker/volumes/d09c2d6fa9fbb5a9fcd44257f020a25422d22f0d8d3c99e2422f80a9deb5704a/_data`

I have re-installed many times the container and deleted any volume, but it keeps getting created like that (I understand the need, just that the name of the Filebrowser volume is not identifiable...)

&nbsp;
**Additional context**
Declaring a `volume:` path for `/data` in the YML file or not, has no change to this behavior. **Should its declaration (to a physical path on disk) _not_ avoid creating the container volume, anyway?**

Not sure why this volume is created, but I think it is hosting-containing any files/folders uploaded by the user on the Filebrowser interface.

I also tried to **name** this volume via some naming parameter in the compose file, but without success e.g. adding  `--name named_dir` to the volume mount line (on the very right).

(source of tip: https://stackoverflow.com/questions/35841241/docker-compose-named-mounted-volume)

&nbsp;
**How to reproduce?**
On my system, I use this compose file:

```
version: "2.1"
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - FB_BASEURL=/
      - TZ=Europe/City
      - UMASK_SET=022
    ports:
      - 8080:80/tcp
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/dockeruser/filebrowser/config/database.db:/database.db
      - /home/dockeruser/filebrowser/config/.filebrowser.json:/.filebrowser.json
      - /srv/dev-disk-by-uuid-a0c79179-a915-3215-a614-a5ccf051ba1e/Syncthing/data:/Shares/Syncthing:or
```
In the above fixed path, my `.filebrowser.json` looks like this:

```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/Shares/Syncthing"
}
```
P.S. I was forced to use a direct declaration of both `database.db` and `.filebrowser.json` because if I only declare the `/data` and `/config` parameters with a local path, the container fails to run for some reason, i.e.

```
     - /home/dockeruser/filebrowser/config:/config
     - /home/dockeruser/filebrowser/data:/data
```

P.S. Declaring a user in either `environment:` section or via the `user` parameter (as found in some compose guides for Filebrowser) has no change to this issue i.e.

```
    environment:
      - PUID=1000  # i.e. root
      - PGID=100   # i.e. users

...or...
     user: "1001:100"
but
    user: "${UID}:${GID}"
doesn't work (container throws an error -- this was found in some on-line YML guides...)
```

&nbsp;
**Files**
Not applicable, no files to provide.

&nbsp;
**Comment**
I hope you understand the issue.
Moreover, your guide may need to offer more details for a compose YML file as many people start using Portaient or similar and I had to find other guides and experiment with a healthy setup, instead of using your Wiki as guide 😞 

Many thanks for your consideration.

**Comment by agneevX** [comment]
This issue isn't related to filebrowser, but to your understanding of Docker.
 
Anonymous volumes with randomized characters are automatically generated for any exposed volumes that are not mapped to a defined volume or bind mount.

To work with your compose file, this would do what you want:

```yml
version: "2.1"

volumes:
  filebrowser_data:

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - FB_BASEURL=/
      - TZ=Europe/City
      - UMASK_SET=022
    ports:
      - 8080:80/tcp
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - filebrowser_data:/data
      - /home/dockeruser/filebrowser/config/database.db:/database.db
      - /home/dockeruser/filebrowser/config/.filebrowser.json:/.filebrowser.json
      - /srv/dev-disk-by-uuid-a0c79179-a915-3215-a614-a5ccf051ba1e/Syncthing/data:/Shares/Syncthing:or
```

**Comment by mackonsti** [comment]
Thank you very much @agneevX for your time and explaining this.
I did not know that FileBrowser container would use anonymous volume.
I appreciate your explanation.
I will come back with a confirmation of your compose-fix and close the ticket ASAP.
Many thanks!

**Comment by mackonsti** [comment]
Hello @agneevX but I am sorry that your solution doesn't seem to work. Now I get double volumes created 🤯

Again, whatever path I assign in the main `volumes:` as `/data` if not respected by Filebrowser container.

I have tried the below, to no avail:
```
    volumes:
      - /home/dockeruser/filebrowser/data:/data
      - /home/dockeruser/filebrowser/config/filebrowser.db:/database.db
      - /home/dockeruser/filebrowser/config/filebrowser.json:/.filebrowser.json
```
Are we sure the `/data` is being read/considered during the launch/run of the compose file and container later? Just wondering. Many thanks.

![Result](https://github.com/filebrowser/filebrowser/assets/1313613/e389bb84-9684-4810-85c2-54c277b2b2ab)

**EDIT:** As I wrote above, I was forced to use a direct declaration of both **database.db** and **.filebrowser.json** because if I only declare the **/data** and **/config** parameters with a local existing path, **the container fails to run for some reason**, i.e.
```
     - /home/dockeruser/filebrowser/config:/config
     - /home/dockeruser/filebrowser/data:/data
```
...where it seems these are not considered/respected. Do we need to add something to the filebrowser.json file? Is it a matter of setting the user to root in either:
```
    environment:
      - PUID=1000  # i.e. root
      - PGID=100   # i.e. users
```
...or...
```
     user: "1001:100"
as
     user: "${UID}:${GID}"
...doesn't seem to work?
```

**Comment by agneevX** [comment]
Yeah, again that is simply how Docker compose works. It uses `<current_folder_name>/<volume_name>`, unless overridden.

You can modify the compose file:

```yml
volumes:
  filebrowser_data:
    name: filebrowser_data
...
```

I will admit the way filebrowser initializes and the file mappings aren't 

The best way would be to initialize a database and the config in a bind mounted `/config`.

This is my compose:

```yml
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: 1001:1001
    healthcheck:
      disable: true
    environment:
      FB_DATABASE: /config/database.db
      FB_DISABLE-EXEC: true
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
    volumes:
      - /opt/appdata/filebrowser:/config
      - ~/:/srv/home
      - /opt/storage:/srv/storage
      - /opt/appdata:/srv/appdata
      - /mnt:/srv/mnt
```

As you can see, I modify the `user` spec to set the user. I don't modify `config.json` so it's read as is from the container.

Do not use PUID/PGID/UID/GID, as they're used by certain containers from LSIO and some others and only apply to those specific containers; the container still has root privileges... it simply drops them and runs the main app process as the user.

**Comment by mackonsti** [comment]
Thank you for your sample. I am sorry but I am getting frustrated to get Filebrowser work correctly. There are many compose files floating around and I do kindly suggest you add a working example in your README, because as I wrote, without explicit declaration of the database and config file, something is happening and I do not get the container to start:

```
2023/06/24 12:00:28 open /database.db: permission denied
2023/06/24 12:00:32 open /database.db: permission denied
```
...despite the fact that the paths are declared and user being also declared (with quotes because Docker complained):
```
    volumes:
      - /home/dockeruser/filebrowser/config:/config
      - /home/dockeruser/filebrowser/data:/data
    user: "1000:100"
```
Moreover, each time I stop and restart/recreate the compose file (as I have been trying to make it work due to various errors) a new volume is created. Not sure why you require a random one created, but I ended up with... 10 empty ones, for example.

Without a preset config.json and an empty database file (0 bytes, via touch) there is no way to get your nice service up and running.

This is not how other containers work, perhaps you are doing something special on some special Docker release.

**I am forced to give up**, despite liking your File Browser work.
Thanks for your time.

**Comment by mackonsti** [comment]
Thank you for your sample @agneevX . I am sorry but I am getting frustrated to get FileBrowser work correctly. There are many compose sample files floating around, and I do kindly suggest you add a working example in your README, because as I wrote, without explicit **declaration of the database and config files,** something is happening and I do not get the container to start:
```
2023/06/24 12:00:28 open /database.db: permission denied
2023/06/24 12:00:32 open /database.db: permission denied
```
So after many attempts, when I changed the `user:` variable, eventually the container could start (as your user ID and group ID were a little misleading to me, obviously different on your OS, so root is like 0:0 on my OMV installation):
```
user: "root:users"
```
However, **your /data and /config mapping is not working**, sorry to report. Despite declaring them explicitly, the files are found elsewhere and each time I down/up the YML file, I get a new volume created. This, to my knowledge, is not normal in my eyes (I could be wrong):
```
    volumes:
      - /home/dockeruser/filebrowser/config:/config
      - /home/dockeruser/filebrowser/data:/data
```
The configuration and database were nowhere to be found, except when I did a `find` across the whole NAS, they were here:
```
./var/lib/docker/overlay2/bc15468d4fb9befdaeafb1f36517844e5a72c0b4976f255fa225f145e82e3cea/merged/database.db
./var/lib/docker/overlay2/bc15468d4fb9befdaeafb1f36517844e5a72c0b4976f255fa225f145e82e3cea/diff/database.db
./var/lib/docker/overlay2/0a54cd5aad954f8305dfcbf4170e6f86a7a2f876ea8e927b8fa0e43a1c2138d3/diff/.filebrowser.json
./var/lib/docker/overlay2/bc15468d4fb9befdaeafb1f36517844e5a72c0b4976f255fa225f145e82e3cea/merged/.filebrowser.json
```

I am sorry but I spent much more time than anticipated, so **I am forced to give up**, despite liking your interface for my simple needs.

It would be great if you could create a page (or on your README) with not only a sample working but also a list of variables (and defaults), whether they are true boolean or strings (compose complained and I was forced to put them all in double quotes) etc.

Thanks for your time.

**Comment by B0F1B0** [comment]
@mackonsti 

i also have OMV with appuser and had problems to run filebrowser. But with the following docker-compose.yml file i could run it. 

The main problem, why we get: `open /database.db: permission denied ` is, because docker create the folder `filebrowser` as root. But we use in the docker-compose `user: 1001:100` wich has no root access. To solve this issue, you have to create the folder `filebrowser` with your user: `appuser`. 

In your case:

`
ssh root@openmediavault
`
```
su appuser
cd /home/dockeruser/
mkdir filebrowser
cd filebrowser
nano docker-compose.yml
```

```
---
version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: 1001:100
    healthcheck:
      disable: true
    environment:
      FB_DATABASE: /config/database.db			#THE FB_XXXX Environment-Variables are not Docker Environment-Variables, they are filebrowser-environment variables
      FB_DISABLE-EXEC: true						
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
    volumes:
     - /home/dockeruser/filebrowser:/config		#The Database in the config folder is also the "Config File" because the newer Version of filebrowser does not need/have a config File. 
     - /DATA:/srv					#this is the "root folder" , means the content of this folder will shown you in Filebrowser 
    ports:
     - '8081:80'
```

Save the file and run:

```
docker-compose up -d
```


> 

--__THERE WE HAVE THE SALAD__--
--__B0F1B0__--
