### ISSUE TITLE
Unable to find the correct port

### ISSUE THREAD

**Issue by topmask** [filebrowser/filebrowser#2517]
CONTAINER ID   IMAGE                     COMMAND          CREATED         STATUS                                  PORTS     NAMES
92d86d0ff53c   filebrowser/filebrowser   "/filebrowser"   6 seconds ago   Restarting (1) Less than a second ago             file-browser

```
version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: root:root
    ports:
      - 8888:80
    volumes:
      - /usr/share/download:/srv
      - /usr/share/filebrowser/filebrowser.db:/database.db
    restart: always

```

Unable to find the correct port
