### ISSUE TITLE
add docker compose example to documentation

### ISSUE THREAD

**Issue by rodhfr** [filebrowser/filebrowser#2547]
**Is your feature request related to a problem? Please describe.**
There is no sample example of docker compose yml please add to documentation for ease of use.

**Describe the solution you'd like**
https://filebrowser.org/installation
```yml
version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8035:80
    volumes:
      - C:\Users\user\Docker-Data\fileserver:/srv
```
