### ISSUE TITLE
Filebrowser docker always show 0KB used from total available storage

### ISSUE THREAD

**Issue by PmNz8** [filebrowser/filebrowser#2557]
**Description**
I have filebrowser setup on Windows 10 x64 Docker via docker compose. For every user Filebrowser always show 0 KB used from available space:
![image](https://github.com/filebrowser/filebrowser/assets/86913474/28ae6143-e518-4ed4-a332-526ffc69e92f)
Where 465 GB is my total C:\ capacity. 

**Expected behaviour**
Show available space on drive where filebrowser path is located (C:\). 

**What is happening instead?**
FB show 0 KB used from 465 GB.

**Additional context**
I use cloudflare with proxy if that is important. I have disabled user command execution but with command enabled it changes nothing. 0 KB used is shown in admin account and users account. 
My docker-compose setup:
```
version: "2.0"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    hostname: FILEBROWSER
    container_name: filebrowser
    ports:
    - 12345:80
    volumes:
    - .\srv:/srv
    - .\filebrowser.db:/database/filebrowser.db
    - .\settings.json:/config/settings.json
    entrypoint: /filebrowser --config /config/settings.json
    restart: always
```

**How to reproduce?**
It is hard to tell for me how to reproduce, maybe just copying my docker compose is enough.
