### ISSUE TITLE
Unique classes or id for each element (buttons) for more flexible settings via custom.css

### ISSUE THREAD

**Issue by baur** [filebrowser/filebrowser#2604]
First of all, thanks for this work, best file browser I have seen, good job 👍

I'd like to hide some elements, for example, "create file", "multi-select" and so on. But elements haven't unique classes. I can select by nth, but element counts changes in depends on the user's role.

Current frontend UI elements haven't unique classes ((( 

Unique class or id for each element for more flexible settings via custom.css

**Describe alternatives you've considered**
or add a feature where we can hide any elements

now I'm using this selector, it is very sensitive to any future HTML changes

```css
#download > div.card-content > button:nth-child(n + 3):nth-child(-n + 9) {
	display: none
}
```
