### ISSUE TITLE
Messing folder ownership after container creation

### ISSUE THREAD

**Issue by Jurrer** [filebrowser/filebrowser#2736]
**Description**

When recreating or creating container, filebrowser acknowledges UID and GID values, but does not apply them to /srv(root dir in settings) and /database directories.
Every time when recreating or creating the container it changes ownership of my data folder to 911:1001, while clearly set to 1000:1000

**Expected behaviour**

It should not change ownership of mounted folders or respect UID and GID env variables.

**What is happening instead?**

Every first container creation filebrowser changes /srv(root dir in settings) and /database directories

**Additional context**

It never happens when restarting already existing container.
Setting user parameter (user: 1000:1000) in docker compose breaks application. It never launches.
Logs always say the correct values assigned in environmental variables.
I am using linuxserver s6 overlay version.

```
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${HOMEPATH}/filebrowser_cfg/filebrowser.db:/database/filebrowser.db
      - ${HOMEPATH}/filebrowser_cfg/settings.json:/config/settings.json
      - ${DATAPATH}:/srv
    restart: unless-stopped
```
settings.json
``` 
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

A very bad solution I have is to `chown -R 1000:1000` my data folder every time this container is created.

**How to reproduce?**
Stop and remove existing filebrowser containers.
Launch filebrowser with UID environment variable other than 911, GID other than 1001, preferably 1000, and root set to `/srv`.
Exec `ls -ln /` command in the container and check ownership of `/srv` and `/database`

**Files**

**Edit**
1. Corrected GID at fault. Was 1000 where it should be 1001 + some formatting

**Comment by dpeachey** [comment]
Same issue for me.

**Comment by MHM98** [comment]
same here.

**Comment by meminens** [comment]
Any updates or workarounds on this issue? Having the same problem.

**Comment by kdb424** [comment]
Other than manually forcing correct permissions after every bringup, I have not found another workaround. This is indeed incorrect behavior.

**Comment by meminens** [comment]
Thanks for the response!

**Comment by Original-Gekko** [comment]
Same problem here. Thanks for your help

**Comment by cgarnier** [comment]
you can start with `- ${DATAPATH}:/srv:ro` to be sure it dont mess with your files. But you will be no more able to modify files from the container.

https://github.com/filebrowser/filebrowser/blob/04e03a83b4db4a9e8bda5ae47b203bd785f93ca4/docker/root/etc/cont-init.d/20-config#L15C6-L15C6

Please remove this line.

**Comment by rluetzner** [comment]
This issue is specific to the _Linuxserver_ container. If you use the _Alpine_ container (i.e. **not** the `s6` tag) the permissions stay as they are.

**Comment by Original-Gekko** [comment]
Thanks for you answers @cgarnier @rluetzner 
So I'll give it a shot with Alpine container :)

**Comment by Jurrer** [comment]
I can confirm, alpine based container works as intended.
I think the fix is on Linuxserver side now.
I can consider the issue as solved.

Thanks for support @rluetzner

**Comment by cgarnier** [comment]
@rluetzner I dont like the alpine based one. It s not easy to volume the config and the database because i have to mount a file. on the s6 we can mount `/config` and `/database`. It s easier to use.

**Comment by Jurrer** [comment]
correct @cgarnier, a downside is that you can't use a volume for `config` and you have to bind mount at least `/.filebrowser.json` file.
As long as you mount it and specify correct db location, you can use the `/database` (or any other) directory.

I'll try to raise this issue on lsio forums.

Edit:
linuxserver.io does not maintain this container, it's only their base image.

**Comment by Original-Gekko** [comment]
I tried the alpine container and it works well.
 Here is my docker compose I use in portainer :
`
---
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - /path/to/root/folder:/srv
      - /path/to/additional/folder1:/srv/folder1
      - /path/to/additional/folder2:/srv/folder2
      - /path/to/filebrowser/db/database.db:/database.db
    ports:
      - 8080:80
    restart: unless-stopped
`
I don't need to change the default settings of .filebrowser.json so I didn't mount it.

I tried to stay as close as possible of the docker run you can find here
https://filebrowser.org/installation

**Comment by nApucco** [comment]
There seems to already be a pull request in the works to fix this. 
https://github.com/filebrowser/filebrowser/pull/2876

Let's hope it gets merged soon.

---

Until then, I also switched to the regular alpine docker image.

In case someone needs an example:
```yaml
filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    user: 1000:1000
    environment:
      - FB_DATABASE=/config/filebrowser.db
      - FB_PORT=8080
      - FB_ROOT=/srv
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fs http://localhost:8080/health || exit 1
    security_opt:
      - no-new-privileges:true
    restart: always    
    volumes:
      - $DOCKERDIR/appdata/filebrowser:/config
      - $STORAGEDIR/data/shares:/srv
```

**Comment by BakasuraRCE** [comment]
Algo can change the script mounting your own without chown line:

```
filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    user: 1000:1000
...
    volumes:
...
      - ./20-config:/etc/cont-init.d/20-config:ro
```

```
#!/usr/bin/with-contenv bash

# make folders
mkdir -p /database

# copy config
if [ ! -f "/config/settings.json" ]; then
  cp -a /defaults/settings.json /config/settings.json
fi

```
