### ISSUE TITLE
Config options are ignored when using docker.

### ISSUE THREAD

**Issue by Etuldan** [filebrowser/filebrowser#2745]
**Description**
Deploying on docker, with a link to an existing config file .json , we are unable to use some config parameters (as initial/default configuration) like Branding or AuthMethod.

**Expected behaviour**
When specifying a filebrowser.json config file
```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv",
  "branding.name": "Test",
  "branding":{
	"name": "Test1"
  }
}
```
we expect that the Branding Name should be set to Test (or Test1, I tried 2 tests)

**What is happening instead?**
The branding config seems to be ignored.

**Additional context**
Doc about branding : https://filebrowser.org/configuration/custom-branding
Default config file : https://github.com/filebrowser/filebrowser/blob/master/docker/root/defaults/settings.json
Same issue for AuthMethod related configs : https://filebrowser.org/configuration/authentication-method

**How to reproduce?**
Create a filebrowser.json with this content above.
Use a docker-compose.yml file with this service:
```
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ./downloads:/srv
      - type: bind
        source: ./filebrowser.json
        target: /.filebrowser.json
```

**Comment by kloon15** [comment]
Generate filebrowser.db from the json using the cmdline and use that instead.

**Comment by Etuldan** [comment]
How can we generate the DB if the processed is already launched (and locked) ?
I already tried to execute command on my docker compose (or on the docker container itself), but I got a timeout, and from my research, it's because the process is launched.

**Comment by kloon15** [comment]
Download the executable, use it to create the db file and just mount it like the json file (make sure its writeable tho).

**Comment by clabnet** [comment]
@kloon15 Sorry, could you please explain yourself better? 
What executable ? I using filebrowser in docker. 
Thank's in advance.

**Comment by RomainLG** [comment]
Hi @Etuldan @clabnet , I'm in the same boat as you are. Did you find a solution ?
I want users to not be able to delete, so trying to set --perm.delete=false
All I get are timeouts...

**Comment by ecker00** [comment]
Also have this issue, if I try to use the /filebrowser cli from inside the docker container, and change any config I get wither error `timeout` or `database.db already exists`.

```sh
~ $ ./filebrowser config init --auth.method=noauth
2024/01/25 19:44:54 /database.db already exists
~ $ ./filebrowser config set --auth.method=noauth
2024/01/25 19:44:59 timeout
```

# Workaround

Guess it's because it's already running.  So my workaround was to temporaily change the entrypoint of the docker-compose to not start the filebrowser only the container.

```yml
services:
  filebrowser:
    image: filebrowser/filebrowser
    # Add this part temporarily to do config changes, makes it no longer timeout
    entrypoint: tail -f /dev/null
```

Then I can run inside the container my config changes:
```sh
docker compose exec -it filebrowser /bin/sh
./filebrowser config set --auth.method=noauth
```

The proper solution here would be to have a default config.json file with all options available, that are easy to modify and bind mount to the container (i mean `.filebrowser.json` as it's called in the container).

**Comment by agung2001** [comment]
this is due to the way filebrowser handles it, the branding is set via a flag, 
which we can find the implementation here [config_set.go#L54-L55](https://github.com/filebrowser/filebrowser/blob/ae0af1f996e9c855ccd1bf4af90f03787f52d301/cmd/config_set.go#L54-L55)

## Workaround
another workaround for this is to create a custom entry point for the docker-compose file
Path : `binary/entrypoint.sh`
```shell
#!/bin/sh

/filebrowser config set --branding.name "My Name" \
    --branding.files "/abs/path/to/my/dir" \
    --branding.disableExternal
/filebrowser
```

then we can modify our `docker-compose.yml` file as follow 
```yml
version: '3'
services:

  file-browser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 80:80
    entrypoint: /binary/entrypoint.sh
    volumes:
      - ./binary:/binary
      - ./data/database.db:/database.db
      - ./data/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped
```

by doing this we can configure the flag as we like 👍
