### ISSUE TITLE
Defining scope of a user to a symlink does not work

### ISSUE THREAD

**Issue by Senya247** [filebrowser/filebrowser#2790]
**Description**

When the scope of a user is set to be a folder that is symlinked to another folder, whether that folder is in the global scope or not, results in a "this location can't be reached" error.

**Expected behaviour**

The symlink to be followed, and the files to be shown

**What is happening instead?**

"this location can't be reached" error

**Additional context**

Running docker, docker-compose.yml:
```
version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8000:8080
    volumes:
      - /home/user/:/data
      - /home/user/.config/filebrowser/:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

```

![image](https://github.com/filebrowser/filebrowser/assets/65822218/c9e09670-f3c6-4017-bee2-829d42730c7c)

**How to reproduce?**

Start filebrowser in `~/`
```
mkdir ~/test
ln -s ~/test ~/link
```
Set user1's scope to /test: no error
Set user2's scope to /link: error
![image](https://github.com/filebrowser/filebrowser/assets/65822218/93871b85-f3b6-4a38-afe7-45d3cad7104f)

**Files**
