### ISSUE TITLE
cant delete the admin user

### ISSUE THREAD

**Issue by IIIdefconIII** [filebrowser/filebrowser#2809]
**Description**
When i change the username admin to something i want, with my own password. after a few hours its back to admin/admin
This time i made a new user which i want seperatly with a password and login with that new users, but cant delete the account admin.

**Expected behaviour**
admin account to be removed.

**What is happening instead?**
Getting a 403 forbidden warning

**Additional context**
Im not sure why the docker container is keep renaming the admin account back to admin after i renamed it and successfully logged in with the new username/passwords

**How to reproduce?**
keep the default settings, changing the username + pwd from within the interface

**Files**
```
# filebrowser__________________________
  filebrowser:
    container_name: filebrowser
    image:  filebrowser/filebrowser
#    image:  filebrowser/filebrowser:s6
    restart: always
#    security_opt:
#    user: "$PUID:$PGID"
#      - no-new-privileges:true
    ports:
      - 5045:80
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
      TZ: Europe/Amsterdam
#    HOST: 10.3.1.5
    volumes:
      - /:/srv
      - $DOCKERDIR/filebrowser:/data
      - $DOCKERDIR/filebrowser:/config
#http://10.3.1.5:9000/if/flow/initial-setup/      
    labels:
      ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"
      org.hotio.pullio.discord.webhook: https://discord.com/api/webhooks/1162866048576524358/U7YzTZMETvwrUJ416bm3igfRuF1BbzVvA5m_gdy8BczPxr0PDkIqnKD1vqKyI8zexcDW
      org.hotio.pullio.author.avatar: https://raw.githubusercontent.com/walkxcode/Dashboard-Icons/main/png/filebrowser.png
```

**Comment by o1egl** [comment]
Looks like you recreate a container and it creates a new db every time. You should persist the db file between container recreations

**Comment by IIIdefconIII** [comment]
> Looks like you recreate a container and it creates a new db every time. You should persist the db file between container recreations

The container doesnt create any data in the - $DOCKERDIR/filebrowser folder.  the same puid an guid works on like 15 containers

EDIT: Change the dockercompose config to:
```
# filebrowser__________________________
  filebrowser:
    container_name: filebrowser
    image:  filebrowser/filebrowser
#    image:  filebrowser/filebrowser:s6
    restart: always
#    security_opt:
#    user: "$PUID:$PGID"
#      - no-new-privileges:true
    ports:
      - 5045:80
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
      TZ: Europe/Amsterdam
#    HOST: 10.3.1.5
    volumes:
      - /:/srv
      - $DOCKERDIR/filebrowser/filebrowser.db:/database/filebrowser.db
      - $DOCKERDIR/filebrowser/settings.json:/config/settings.json
```      
Created the files manually, do i need to chown those files too?

EIDT 2: those file i created stays 0kb.

**Comment by o1egl** [comment]
You're mounting files to the wrong paths. Check the docs on https://filebrowser.org/installation#docker
It should be `/database.db` and `/.filebrowser.json`

**Comment by o1egl** [comment]
Either create the config manually or leave it as is - it won't be overwritten by the app.

**Comment by IIIdefconIII** [comment]
Thanks I will try that out, is the . here a typo cause the documentation doesn’t shows a .

/.filebrowser.json

got this atm:
```
  filebrowser:
    container_name: filebrowser
    image:  filebrowser/filebrowser
#    image:  filebrowser/filebrowser:s6
    restart: always
#    security_opt:
#    user: "$PUID:$PGID"
#      - no-new-privileges:true
    ports:
      - 5045:80
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
      TZ: Europe/Amsterdam
#    HOST: 10.3.1.5
    volumes:
      - /:/srv
      - $DOCKERDIR/filebrowser/filebrowser.db:/.filebrowser.json
      - $DOCKERDIR/filebrowser/settings.json:/config/settings.json
```

**Comment by IIIdefconIII** [comment]
the log also show this:
2023/11/07 21:16:39 open /database/filebrowser.db: permission denied
so i think the paths you gave me are not ok

**Comment by IIIdefconIII** [comment]
this worked, @o1egl thanks for the headsup and breaing with me
in settings.yaml i have putm also changed de PUID and GUID to 0 otherwise im getting some strange permission errors.

```
{
  "port": 5045,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```
```
  filebrowser:
    container_name: filebrowser
    image:  filebrowser/filebrowser:s6
#    image:  filebrowser/filebrowser:s6
    restart: always
#    security_opt:
#    user: "$PUID:$PGID"
#      - no-new-privileges:true
    ports:
      - 5045:5045
    environment:
      PUID: 0
      PGID: 0
      UMASK: $UMASK
      TZ: Europe/Amsterdam
#    HOST: 10.3.1.5
    volumes:
      - /:/srv
      - $DOCKERDIR/filebrowser/filebrowser.db:/database/filebrowser.db
      - $DOCKERDIR/filebrowser/settings.json:/config/settings.json
```
