### ISSUE TITLE
Unlhealthy: crontab: can't open 'abc': No such file or directory

### ISSUE THREAD

**Issue by IIIdefconIII** [filebrowser/filebrowser#2832]
**Description**
Gettin unhealthy status warning in portainer

**Expected behaviour**
No warnings like this and no unhealthy status

**What is happening instead?**
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
[custom-init] No custom files found, skipping...
crontab: can't open 'abc': No such file or directory
[ls.io-init] done.
2023/11/16 10:31:16 Using config file: /config/settings.json
2023/11/16 10:31:16 Listening on [::]:5045
```

**Additional context**
im not sure where that abc comes from cause it isnt in my compose file
```
# filebrowser__________________________
  filebrowser:
    container_name: filebrowser
    image:  filebrowser/filebrowser:s6
#    image:  filebrowser/filebrowser:s6
    restart: always
#    security_opt:
#    user: "$PUID:$PGID"
#      - no-new-privileges:true
    ports:
      - 5045:5045
    environment:
      PUID: 0
      PGID: 0
      UMASK: $UMASK
      TZ: Europe/Amsterdam
#    HOST: 10.3.1.5
    volumes:
      - /:/srv
      - $DOCKERDIR/filebrowser/filebrowser.db:/database/filebrowser.db
      - $DOCKERDIR/filebrowser/settings.json:/config/settings.json
 ```

**How to reproduce?**

**Files**
