### ISSUE TITLE
persisting db with kubernetes, cannot boot - no locks available

### ISSUE THREAD

**Issue by Azazel666** [filebrowser/filebrowser#2874]
**Description**
I'm trying to setup a container running **filebrowser** in my home kubernetes cluster, however i cannot manage to persist the actual database. When running it not mapping the database to a persistent volume it boots up without issues however as soon as i try to persist it so it does not reset on container reboots i cannot get it working and always gets the error: no locks available

I have tried experimented with PUID & PGUID (not supplying and supplying), tried setting SecurityContext _fsGroup_, _runAsUser_, _runAsGroup_ also but either i get permission denied on **_/database/filebrowser.db_** or **_no locks available_**.

**Expected behaviour**
Generate my database as set in the settings on the persistent volume mounted

**What is happening instead?**
Error: no locks available

**How to reproduce?**
My setup consists of running a cluster out of a VM on a ESXi virtual server on premise. The cluster exists of one control plane node, three worker nodes. Then i got another server running as a nfs server for persistent storage of data volumes.

**Files**
This is my k8s setyp:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-browser-main
  namespace: foundry-vtt
  labels:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-browser-main
    app.kubernetes.io/version: "v2.26.0"
    app.kubernetes.io/component: file-browser
    app.kubernetes.io/part-of: foundry-vtt
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foundry-vtt
      app.kubernetes.io/instance: foundry-browser-main
      app.kubernetes.io/component: file-browser
      app.kubernetes.io/part-of: foundry-vtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundry-vtt
        app.kubernetes.io/instance: foundry-browser-main
        app.kubernetes.io/component: file-browser
        app.kubernetes.io/part-of: foundry-vtt
    spec:
      containers:
      - name: browser
        image: filebrowser/filebrowser:v2.26.0
        imagePullPolicy: IfNotPresent
        securityContext:
          fsGroup: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: foundry-data-persistent-storage
          mountPath: /srv
          subPath: data/Data
        - name: foundry-data-persistent-storage
          mountPath: /.filebrowser.json
          subPath: filebrowser/.filebrowser.json
        - name: foundry-data-persistent-storage
          mountPath: /database
          subPath: filebrowser/database
      volumes:
      - name: foundry-data-persistent-storage
        persistentVolumeClaim:
          claimName: foundry-main-data-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: foundry-browser-main-svc
  namespace: foundry-vtt
  labels:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-browser-main
    app.kubernetes.io/component: file-browser
    app.kubernetes.io/part-of: foundry-vtt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-browser-main
    app.kubernetes.io/component: file-browser
    app.kubernetes.io/part-of: foundry-vtt
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foundry-browser-main-ingress
  namespace: foundry-vtt
  labels:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-browser-main
    app.kubernetes.io/component: file-browser
    app.kubernetes.io/part-of: foundry-vtt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vtt-files.example.com
    secretName: foundry-files-main-tls
  rules:
  - host: vtt-files.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foundry-browser-main-svc
            port:
              name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-main-data-pv-claim
  namespace: foundry-vtt
  labels:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-vtt-main
    app.kubernetes.io/component: game-system
    app.kubernetes.io/part-of: foundry-vtt
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-main-data-pv
  namespace: foundry-vtt
  labels:
    app.kubernetes.io/name: foundry-vtt
    app.kubernetes.io/instance: foundry-vtt-main
    app.kubernetes.io/component: game-system
    app.kubernetes.io/part-of: foundry-vtt
spec:
  storageClassName: nfs
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.10.10.10 # NFS ip
    path: /mnt/storage/k8s/clusters/K8s-prime/apps/foundry/main # base path to where app persistent data is stored
```
Created a .filebrowser.json file and place it in my persistent volume to be served as **_/.filebrowser.json_** in the container. Content as below.
```
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```
