### ISSUE TITLE
Outdated docker instructions

### ISSUE THREAD

**Issue by KhaaL** [filebrowser/filebrowser#2883]
**Description**
The instructions for docker and docker compose at https://filebrowser.org/installation/ should be changed. The current instructions bind the following volumes:
```
    -v /path/to/root:/srv \
    -v /path/filebrowser.db:/database.db \
    -v /path/.filebrowser.json:/.filebrowser.json \
```
are binding the wrong files / locations in the container. The database.db exists in the folder /database in the container, and the .json settings file exists in the /config folder in the container.

**Expected behaviour**
docker running filebrowser successfully. 

**What is happening instead?**
Docker creates the image, but stops with:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-22.04/" to rootfs at "/.filebrowser.json": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-22.04/.filebrowser.json (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Additional context**
This happened with both standard and linux-server images. 

**Suggested solution**
Bind the volumes between the host and the container according to the following binds instead:
```
      - ./files:/srv
      - ./database:/database
      - ./config:/config
```

**Comment by kesumin** [comment]
Had a similar issue. This is what worked for me:

```
            - /:/srv
            - /path/to/config/:/host/path
```

It seems you're also using Docker Compose. 
For future users that want a copy n paste Compose solution, here's my current:

```
name: filebrowser
services:
    filebrowser:
        volumes:
            - /:/srv
            - /path/to/config/:/host/path
        ports:
            - 12345:80
        image: filebrowser/filebrowser:latest
```

The /:/srv volume mounts my root directory to File Browser's working dir. This works for me. If you're new to Docker, all you have to do is change the first / in `- /:/srv` to your desired working directory. e.g: `- /home/user/files:/srv`

**Comment by asad-awadia** [comment]
Another variant that has worked well for me
```
  fbrowser:
    image: filebrowser/filebrowser
    container_name: fbrowser
    restart: unless-stopped
    volumes:
      - ./fbfiles/data:/srv
      - ./fbfiles/config/filebrowser.db:/database.db
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80
```

**Comment by k4j8** [comment]
For `database.db` to be mounted, the path must exist. To fix this, I ran `touch database.db` before running Docker Compose. You could also use an absolute path instead. The instructions mention this as well, although I missed it the first time.

For the Alpine version:
```yaml
---
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database.db:/database.db  # must run `touch database.db` first or use absolute path instead
      - /path/to/your/files:/srv
    ports:
      - 80:80
    restart: unless-stopped
```

There is discussion of updating the instructions in the File Browser docs repo here: https://github.com/filebrowser/docs/pull/44. I suggest closing this issue and following the discussion there.
