### ISSUE TITLE
Environment variables for better Kubernetes Support

### ISSUE THREAD

**Issue by stevelaclasse** [filebrowser/filebrowser#2913]
Hi and Thank you very much for this amazing Application to explore files

Will it be possible to use env variables, as there are easy to configure for Docker or Kubernetes ?
For example set admin username or password, set the Port number, ... and many others parameters. 

Alternative, could you provide a complete settings.json (filebrowser.json) file with all (or most of) the parameters and theidefault values ?

Thank you

**Comment by rluetzner** [comment]
I agree that this would make filebrowser easier to use with any containerization engine.

I'd be willing to look into it and provide a pull request if it's wanted. 🙂 

Edit: I see that Cobra and Viper are already used in `go.mod`, so it should be pretty easy to parse everything from env variables. I'd need to check, but it's possible that it already works out of the box if you know which env variables to set. 🙂

**Comment by stevelaclasse** [comment]
Great and thanks for the answer, we are waiting for the update.

[Out of the Context] I am seeing that this FileBrowser is being used by the company **Hostinger** .  Good Work

**Comment by rluetzner** [comment]
I experimented a bit, but it seems like only a few environment variables work as expected and I haven't been able to figure out why (yet).

For example

```bash
FB_PORT=9999 FB_USERNAME=stuff ./filebrowser -r /path/to/serve
```

works fine. `FB_PASSWORD` seems to do something, but at least it doesn't accept a password as plain text. I've tried hashing the password, but it's possible that I used the wrong algorithm.

Then again

```bash
FB_SIGNUP=true ./filebrowser -r /path/to/serve
```

does **not** work and doesn't set the value of `signup`. Neither does

```bash
FB_BRANDING_NAME=stuff ./filebrowser -r /path/to/serve
```

. So, while I've learned _something_ I haven't really figured out yet which config values can be configured in a file or via env variables.

I at least confirmed that the config doesn't actually need to be a JSON file. It can be YAML instead, because the Viper framework can parse that as well.

The config values are persisted in the database, so between each test the filebrowser.db file must be deleted to reset the values to their defaults.

**Comment by arcastro** [comment]
> Will it be possible to use env variables, as there are easy to configure for Docker or Kubernetes ?
> For example set admin username or password, set the Port number, ... and many others parameters.

As a workaround, you can use the filebrowser CLI to configure the database. 

You could set up an [Init Container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), that mounts the filebrowser database and uses the CLI to configure any values you want, prior to your main container startup.

```
/filebrowser config set --<setting> <value>;
```

Or, if you don't want a separate init container, you could update your main deployment's command to run any setup script you want before starting the main `/filebrowser` web server.

Here's a sample kubernetes deployment yaml that allows you to leverage the CLI to configure filebrowser from environment variables.

```
spec:
  containers:
    - image: filebrowser/filebrowser
      env:
        - name: ADMIN_PASSWORD
          value: <password-env-variable-from-kubernetes-secret>
        - name: LISTENING_PORT
          value: 8081
      command:
        - /bin/sh
      args:
        - '-c'
        - >-
          /filebrowser users update admin --password "${ADMIN_PASSWORD}";  # configure the admin password, from env var
          /filebrowser config set --port "${LISTENING_PORT}";  # configure the port, using the env variable above
          /filebrowser # start the web server
      
```

The CLI is pretty well documented:
* ./filebrowser --help
* ./filebrowser users --help
* ./filebrowser config --help
