### ISSUE TITLE
error: /auth/renew 403 Forbidden

### ISSUE THREAD

**Issue by NanerLee** [filebrowser/filebrowser#292]
1. version
filemanager: 1.3.11
ubuntu: 16.04.3
chrome: 62
2. filemanager configure
```yaml
address: 127.0.0.1
baseURL:
noAuth: false
database: "/home/filemanager/filemanager.db"
log: "/home/filemanager/error.log"
port: 5000
reCaptchaKey: ''
reCaptchaSecret: ''
plugin: ''
scope: "/home/downloads"
allowCommands: true
allowEdit: true
allowNew: true
commands:
        - git
        - ls
```
3. What are you trying to do?
 visit my filemanager webpage

4. What did you expect to see?
no error

5. What did you see instead (give full error messages and/or log)?
In f12, there is a error: `Failed to load resource: the server responded with a status of 403 ()       api/auth/renew`
In my server terminal stdout, there is a error: `2017/12/06 20:43:56 /auth/renew: 403 Forbidden`

This error always happen when I visit login webpage.
It seems that there is a error about `auth` in configure ?
