### ISSUE TITLE
Change admin login

### ISSUE THREAD

**Issue by MarvBob** [filebrowser/filebrowser#293]
I installed filemanager using the docker latest image.
More an enhancement proposal than an issue but I would like to change the "admin" login to another name, but when I try to edit the admin user I am redirected to the "new user" form.
Maybe I just did not find the way to do it, but I feel like it is not a good practice to force the admin login to be "admin".

**Comment by NanerLee** [comment]
You can add a new admin account and delete the "admin" account.

**Comment by MarvBob** [comment]
I tried but there is not button to delete the "admin" account, even if I log out of it and log into the "new" admin account.

**Comment by hacdias** [comment]
You used docker so I think the problem might be the same as this one:

https://github.com/hacdias/filemanager/issues/277#issuecomment-346124183

**Comment by MarvBob** [comment]
Yes, it is exactly the same problem (sorry for creating a new issue), I get redirected to `/users/new` when trying to edit the admin user.
But I did mount the 3 volumes `(config.json,` `database.db` and `/srv`). My filemanager is runnning in a stack, here is my docker-compose file (without my network and backend rules) if it can help:
```yaml
filemanager:
    image: hacdias/filemanager:latest
    volumes:
      - ./data:/srv
      - ./filemanager/config.json:/config.json
      - ./filemanager/database.db:/database.db
```
Also here is my config.json, which is almost the default one:
```json
{
        "port": 80,
        "address": "",
        "database": "/etc/database.db",
        "scope": "/srv",
        "allowCommands": false,
        "allowEdit": true,
        "allowNew": true,
        "commands": []
} 
```                               
I don't really understand how the `database.db` file is supposed to be used though, mine remains empty. Maybe my configuration is wrong somewhere ?

Also, is there a way to get an access into the container? The bash executable is not found. (Maybe that's another issue/enhancement).

**Comment by hacdias** [comment]
Try changing

```
filemanager:
    image: hacdias/filemanager:latest
    volumes:
      - ./data:/srv
      - ./filemanager/config.json:/config.json
      - ./filemanager/database.db:/database.db
```

to

```
filemanager:
    image: hacdias/filemanager:latest
    volumes:
      - ./data:/srv
      - ./filemanager/config.json:/config.json
      - ./filemanager/database.db:/etc/database.db
```

To set the database.db path to the specified on config.json.
