### ISSUE TITLE
[Docker] Some weird problems when started in docker

### ISSUE THREAD

**Issue by AloneRUS** [filebrowser/filebrowser#3063]
I tried to add reCaptcha but got some weird problem. 

I tried to use:
`filebrowser config set  --recaptcha.key site-key  --recaptcha.secret private-key`

And got:

`./filebrowser.db does not exist. Please run 'filebrowser config init' first.`

And it's weird because all working and I can use filebrowser.

Than I tried to init config with `filebrowser config init`

And I got that: `open ./filebrowser.db: permission denied`

That I can see in docker container logs
![image](https://github.com/filebrowser/filebrowser/assets/7943675/7bd96de3-f8aa-4b13-91f5-94087779cb44)

Docker compose example:

```
version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    volumes:
      - /disk/path/:/srv
      - /disk/filebrowser/database/filebrowser.db:/database/filebrowser.db
      - /disk/filebrowser/config/settings.json:/config/settings.json
    environment:
      PUID: ${USER_ID}
      PGID: ${GROUP_ID}
```

Now I can use filebrowser with some issues but can't add reCaptcha and use `filebrowser config` features
