### ISSUE TITLE
Traefik proxy not proxying the container after latest update [v2.28.0]

### ISSUE THREAD

**Issue by just5ky** [filebrowser/filebrowser#3092]
**Description**

After the latest update, Traefik proxy is not proxying the container.

> Traefik is exposing it properly when i rollback to `v2.27.0`

**Expected behavior**
Traefik proxy should detect the container to forward it to a Domain.

**What is happening instead?**
When I check from Traefik dashboard, it's not listing the container.

**Additional context**
### Docker Compose
```yml
services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    networks:
      - proxy # rename this to your custom docker network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - 8080:8080 # Dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # ro = read-only access to the docker.sock
      - $DOCKERDIR/traefik/:/etc/traefik/
    environment:
      CF_DNS_API_TOKEN: $CLOUDFLARE_API_TOKEN
      TZ: $TZ
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      traefik.http.routers.api.rule: Host(`traefik.$DOMAINNAME`) # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal # Enable Traefik API.
      traefik.http.routers.api.middlewares: auth@file
      traefik.enable: true # Enable Traefik reverse proxy for the Traefik dashboard.

  filebrowser:
    image: filebrowser/filebrowser   #v2.27.0
    container_name: filebrowser
    volumes:
      - "/:/srv"
      - $DOCKERDIR/filebrowser/filebrowser.db:/database.db
      - $DOCKERDIR/filebrowser/settings.json:/config/settings.json
    networks:
      - proxy
    ports:
      - "80:80"
    environment:
      - PUID=$PUID
      - PGID=$PGID
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.rule: Host(`file.$DOMAINNAME`)
      traefik.http.services.filebrowser.loadbalancer.server.port: 80
      traefik.http.routers.filebrowser.entryPoints: https
      traefik.http.routers.filebrowser.middlewares: auth@file
```

**How to reproduce?**
Use the latest version of filebrowser container with traefik proxy.
