### ISSUE TITLE
Health check fails on v2.28.0

### ISSUE THREAD

**Issue by gowtham1337** [filebrowser/filebrowser#3119]
**Description**
The latest image (v2.28.0) of filebrowser from docker hub reports an unhealthy status even though there are no errors and the container is working as expected.

**Expected behaviour**
Container should report healthy

**What is happening instead?**
Container is reporting unhealthy

**Additional context**
Because the container is reporting unhealthy, errors are thrown and several other things fail. For example, a reverse proxy might think this service is unavailable and failover.

**How to reproduce?**
Docker compose:
```
filebrowser:
    image: filebrowser/filebrowser:v2.27.0 #this version works
    #image: filebrowser/filebrowser:latest - throws unhealthy check
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - $DOCKERDIR/filebrowser/filebrowser.db:/filebrowser.db
      - $DOCKERDIR/filebrowser/.filebrowser.json:/.filebrowser.json
      - /:/srv
```
See that the health check for the container is reported as unhealthy in portainer. There is no difference in logs and functionality. App is working perfectly as expected but still shows unhealthy.

**Comment by ferdinandmehlan** [comment]
There is already a fix for that: https://github.com/filebrowser/filebrowser/pull/3087 
Unfortunately it's still awaiting approval.
In the mean time you could just override the host in the healthcheck:
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:80/health"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
```

Or whatever interface your container is listening to
