### ISSUE TITLE
[docker] 2.30.0 On upload, the replace/rename modal self-dismisses before the user can click

### ISSUE THREAD

**Issue by working-name** [filebrowser/filebrowser#3303]
**Description**
If you try to upload a file that already exists, the modal self-dismisses before you get to pick rename or replace. The upload does not happen either.

This is with delete perm set to false, the rest is fairly vanilla options.

**Expected behaviour**
Modal should stay up until the user picks something.

**What is happening instead?**
No errors in the console, no network requests gone unanswered or answered with anything but a status 200. Uploads work otherwise, so not an nginx proxy manager issue.

Note: there are no network requests made since this is a pure UX javascript bug.

**Additional context**
```javascript
"perm": { ... "delete": false ... }
```

FileBrowser: 2.30.0
Docker Compose version v2.24.2
Docker CE 25.0.1
Debian 12
Client browser: brave, but seems irrelevant happens in others as well.

```yaml
version: "3.9"
services:
  holygrail:
    image: filebrowser/filebrowser
    user: 1001:1001
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1g"
    ports:
      - "172.17.0.1:18202:80"
    restart: unless-stopped
    volumes:
      - "./drive:/srv"
      - "./filebrowser.db:/database.db"
      - "./settings.json:/config/filebrowser.json"
```

**How to reproduce?**
Just run a docker version of this and try to upload the same file you just did before to check on the modal. I don't know if pertinent but "delete" perm is set to false.

**Files**

https://github.com/filebrowser/filebrowser/assets/16505052/9236edf7-0941-4e5e-87ba-cbfba333ff6d
