### ISSUE TITLE
Create a docker with an initial admin username and password

### ISSUE THREAD

**Issue by EnricoBeltramo** [filebrowser/filebrowser#3306]
**Is your feature request related to a problem? Please describe.**
I would create a custom docker with a initial user and password different from admin / admin

**Describe the solution you'd like**
FROM filebrowser/filebrowser:latest

-- some command to create a user and password ---

**Describe alternatives you've considered**
I tried to copy database.db, but no effect,
I tried to run command line commands during docker creation, like: 
./filebrowser users add <username> <password> [flags]
but I have timeout error

**Additional context**

**Comment by ruedigerp** [comment]
your database.db is locked by filebrowser process. 

```
# lsof /srv/config/database.db
1	/filebrowser	0	/dev/null
1	/filebrowser	1	pipe:[1570994990]
1	/filebrowser	2	pipe:[1570994991]
1	/filebrowser	3	/srv/config/database.db
1	/filebrowser	4	anon_inode:[eventpoll]
1	/filebrowser	5	pipe:[1570995019]
1	/filebrowser	6	pipe:[1570995019]
1	/filebrowser	7	socket:[1570995023]
14	/bin/busybox	0	/dev/pts/0
14	/bin/busybox	1	/dev/pts/0
14	/bin/busybox	2	/dev/pts/0
14	/bin/busybox	10	/dev/tty

```
you can user our own entrypoint.sh: 
```
/filebrowser users add alice secret1234 --perm.admin
/filebrowser users update admin --perm.admin false
/filebrowser -r /srv/ -c /.filebrowser.json
```
Or delete the admin user. 
Or create the user and database.db locally with the filebrowser binary and mount the database.db in the container. 

I have filebrowser running in Kubernetes and simply have an admin deployment next to the filebrowser deployment. I edit the users in this admin deployment because the DB is not locked there. The file browser is stopped briefly and I can then quickly import the user.yaml in the admin pod. 
This is always the same for installations and via: 

```
cat <<EOF > user.yaml
- id: 1
  benutzername: alice
  passwort: $2a$10$QsIdFNpyqHW12WGBxs6xQ.UjU1qsA5JuuVXyrgqYyYgWFb.053vLO
  Geltungsbereich: .
  Gebietsschema: de
  Sperrkennwort: false
  Ansichtsmodus: mosaik
  Einzelklick: falsch
  perm:
    admin: false
    ausführen: false
    erstellen: wahr
    umbenennen: wahr
    ändern: wahr
    löschen: wahr
    freigeben: wahr
    Herunterladen: wahr
  Befehle: []
  Sortierung:
    nach: Name
    aufsteigend: falsch
  Regeln: []
  hidedotfiles: falsch
  Datumsformat: falsch
- id: 2
  username: bob
  password: $2a$10$tqOB4Pcyi8I0BIVDhnfQl.PE7TVWtBtsi6BLNXRc.YcZN8K/nLXGO
  scope: /
  locale: de
  lockpassword: false
  viewmode: list
  singleclick: false
  perm:
    admin: true
    execute: true
    create: true
    rename: true
    modify: true
    delete: true
    share: true
    download: true
  commands: []
  sorting:
    by: name
    asc: false
  rules: []
  hidedotfiles: false
  dateformat: false
EOF
```

quickly inserted and imported. 
`filebrowser users import user.yaml`

The filebrowser deployment scale 1 and the new users are included. 
If users have been added, deleted or edited via the web interface, they are briefly scaled to 0 and the isers are quickly exported, scale 1, edited, scale to 0, imported and scale to 1. 

If you do it via an entrypoint.sh you can easily run it the first time and simply put the database.db in a volume with Docker or Kubernetes. Then simply put an init.lock file next to it and check whether the file exists the next time you start it. 
With k8s, you can create a configmap containing the init.lock file after the first start. If this is found in entrypoint.sh, no user.yaml is imported. Only if the lock is not there.
