### ISSUE TITLE
docker db and config not work

### ISSUE THREAD

**Issue by mangomatrix** [filebrowser/filebrowser#3413]
**Description**
deploy with docker,  db file can not mout from container.
my compose file:
```yaml
version: '3.2'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    volumes:
      - /mnt/hanwei/filebrowser/test/data:/srv
      - /mnt/hanwei/filebrowser/test/config/setting_new.json:/config/settings.json
      - /mnt/hanwei/filebrowser/test/db_file/filebrowser.db:/database/filebrowser.db
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
```

/mnt/hanwei/filebrowser/test/db_file/filebrowser.db is an empty file:
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/2b15ac5d-d181-47bc-8d34-35c609d76d21">

/mnt/hanwei/filebrowser/test/config/setting_new.json file is:
```json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database/filebrowser.db",
  "root": "/srv"
}
```

**Expected behaviour**
persistently store passwords.

**What is happening instead?**
logs:

<img width="742" alt="image" src="https://github.com/user-attachments/assets/f3643d69-9026-4678-854d-3df06c591d46">

**Additional context**
docker version:
<img width="312" alt="image" src="https://github.com/user-attachments/assets/fdff7382-c388-439f-ac53-2a3633886192">

**How to reproduce?**

```shell
docker compose up 
```
docker-compsoe.yml
```yaml
version: '3.2'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    volumes:
      - /mnt/hanwei/filebrowser/test/data:/srv
      - /mnt/hanwei/filebrowser/test/config/setting_new.json:/config/settings.json
      - /mnt/hanwei/filebrowser/test/db_file/filebrowser.db:/database/filebrowser.db
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
```

**Files**

no

If i do not mount db, it worked. But can not persistently store passwords.
