### ISSUE TITLE
Docker error with v2.31.0 : s6-supervise filebrowser: warning: unable to spawn ./run (waiting 60 seconds): Permission denied

### ISSUE THREAD

**Issue by romainsi** [filebrowser/filebrowser#3442]
**Description**
With last update (v2.31.0) of FileBrowser on Docker (filebrowser-s6) container failed to start with error :
`s6-supervise filebrowser: warning: unable to spawn ./run (waiting 60 seconds): Permission denied`

Example of my docker-compose.yml :
```
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: always
    volumes:
      - /home/example:/srv
      - /opt/filebrowser/filebrowser.db:/database/filebrowser.db
      - /opt/filebrowser/settings.json:/config/settings.json
      - /opt/filebrowser/filebrowser.log:/config/filebrowser.log
      - /opt/filebrowser/custom:/config/custom
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 127.0.0.1:8888:80 # HTTP port
```

This configuration working before update.

So I switched back to an old version  :
`image: filebrowser/filebrowser:v2.30.0-s6`

But settings.json does not seem to have the correct rights after installation in the container.
I solved the problem temporarily by opening a bash in the container and restoring rights with the command: 
`chown abc:users /config/settings.json`.

I use Docker version 27.2.0 and AlmaLinux release 9.4.

Thanks in advance.
