### ISSUE TITLE
oauth not uploading with filebrowser

### ISSUE THREAD

**Issue by jkoestner** [filebrowser/filebrowser#3479]
**Description**
When using oauth behind reverse proxy the files are not uploading to the server. The files are only uploaded with 0B. Just helps with security.

**Expected behaviour**
Files to be uploaded similarly when not using oauth.

**What is happening instead?**
I'm receiving a status 500 from the server when using oauth.

**Additional context**
I was able to try this with the proxy method however that did not make a difference as that was only authenticating but did not change the behavior of oauth.

**How to reproduce?**
```
  filebrowser:
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "$FILEBROWSER_PORT:80"
    volumes:
      - $DOCKERDIR/filebrowser/config:/config
      - $DOCKERDIR/filebrowser/database:/database
      - $STORAGEDIR:/srv
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=websecure"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=80"
  ```

this is the middleware auth
```
http:
  middlewares:
    middlewares-oauth:
      forwardAuth:
        address: "http://oauth:port"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
```
