### ISSUE TITLE
Admin password resetting after docker container is restarted

### ISSUE THREAD

**Issue by alechouse97** [filebrowser/filebrowser#3507]
**Description**
I am using docker-compose to start filebrowser. I can change the admin password, logout, and log back in using the updated password. However, running `docker compose down` followed by `docker compose up` will reset the password back to admin/admin.

It looks like all configuration settings are removed after the 

**Expected behaviour**
Admin password and configurations do not reset.

**What is happening instead?**
Admin password being reset when docker container is restarted.

**Additional context**
Here's the filebrowser section of my docker-compose.yaml

```yaml
filebrowser:
  image: filebrowser/filebrowser
  container_name: filebrowser
  volumes:
    - /home/xxx/mnt/drive1:/srv #Change to match your directory
    - /home/xxx/docker/filebrowser/filebrowser.db:/database/filebrowser.db
    - /home/xxx/docker/filebrowser/settings.json:/config/settings.json
  environment:
    - PUID=$(id -u)
    - PGID=$(id -g)
  ports:
    - 8080:80
```

Interestingly, swapping to the `filebrowser/filebrowser:s6` image fixes the problem. However, this image creates and leaves behind two docker volumes, which is not desirable.

**Comment by eiqnepm** [comment]
It looks like your mounting the config to the wrong location, the docs example uses `/.filebrowser.json`, not `/config/settings.json`. I'm using the latest tag and I'm **not** having this issue.
<details><summary>compose.yaml</summary>
<p>

```yaml
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    networks:
      - filebrowser
    user: 1000:1000
    volumes:
      - ./filebrowser/srv:/srv
      - ./filebrowser/database.db:/database.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ./filebrowser/logs:/logs

networks:
  filebrowser:
    name: filebrowser
```

</p>
</details>
<details><summary>.filebrowser.json</summary>
<p>

```json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "/logs/filebrowser.log",
  "database": "/database.db",
  "root": "/srv"
}
```

</p>
</details>

Remember to `touch ./filebrowser/database.db` on the host, otherwise Docker will try to mount it as a directory.
