### ISSUE TITLE
I don't understand the docker tag system

### ISSUE THREAD

**Issue by garyo** [filebrowser/filebrowser#3581]
**Is your feature request related to a problem? Please describe.**
When following the installation instructions, I get errors because the image I'm using doesn't have the database in the same place as the install instructions. I was able to fix it using this config:
```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - /mnt/storage:/srv  # Mount the storage directory as the root directory to browse
      - ./database.db:/database.db  # Persist users and settings
      # - ./filebrowser.json:/.filebrowser.json  # Custom settings file
    environment:
      - PUID=1000  # Set user ID
      - PGID=1000  # Set group ID
    security_opt:
      - no-new-privileges:true
```
but it got me wondering if `image: filebrowser/filebrowser:latest` actually is the correct image. On docker hub there is `v2-s6` (and other aliases) as well as `v2` (and aliases) but I don't see anywhere in the docs saying which to use. And I'm not sure which one `latest` points to.

Looking carefully at the install docs (docker section) I now think "-s6" maybe uses a different base linux image which mounts the db and settings files in different locations. Is that right? In that case `latest` is kind of ambiguous.

**Describe the solution you'd like**
Docker install instructions could mention which tag `latest` refers to, specifically `v2`, `v2-s6` or `s6`. Or better yet, say "don't use `latest` because you won't know which config dir it will use."

Also it would be really nice to have a docker-compose.yml file in the docs.
