### ISSUE TITLE
Can't edit config file

### ISSUE THREAD

**Issue by wazoo** [filebrowser/filebrowser#36]
I am having the same issue as #35 except that my config file is in YAML not TOML.  The error is:

```
07/Jan/2016:12:36:21 -0700 [PANIC /admin/edit/config.yaml] go/src/github.com/hacdias/caddy-hugo/frontmatter/frontmatter.go:56 - interface conversion: interface is map[interface {}]interface {}, not map[string]interface {}
```

This is the sanitized version of my config file:

``` yaml

---
baseurl: http://www.domain.com"
languageCode: en-us
title: Site Title
disqusShortname: "user"
paginate: 10 # optional
editor: "atom"
paginatePath: "page"
preservetaxonomynames: true
MetaDataFormat: yaml

params:
  twitter: "user"
  instagram: "user"
  facebook: "user"
  gplus: ""
  linkedin: ""
  pinterest: "user"
  googleAnalyticsUserID: ""
  rss_link: "https://www.domain.com/index.xml"
  avatar_link: "http://placehold.it/140x140"
  copyright: "Content Copyright"
  sb_widget_about: true
  sb_widget_search: false
  sb_widget_topics: true
  sb_widget_tags: true
  sb_widget_twitter: false
  sb_widget_recient_comments: false
  f_widgets: false
  f_widget_archives: true
  f_widget_meta: true
  f_widget_twitter: true
  f_widget_subscribe: true

permalinks:
  post: "/:year/:month/:slug/" # optional
  page: "/:title/"

taxonomies:
    tag: "tags"
    topic: "topics"
```

This config works fine with hugo and I don't have trouble parsing the fontmatter for the content (also in YAML) so I am not sure whats up.  The things under params: are mostly just re-usable items, the sb_ and f_ turn on and off widgets on the site.
