### ISSUE TITLE
Ability to specify external URL for shared links?

### ISSUE THREAD

**Issue by FlorentLM** [filebrowser/filebrowser#3658]
I have a reverse proxy (Traefik) to access filebrowser internally on `https://filebrowser.internal.mysite.com` but I would like to allow friends to download stuff from the outside at, say `https://mysite.com/share/r4nD0m`

The only way I managed to make this work is by doing so:

`./filebrowser/filebrowser.json`:
```json
{
  "port": 80,
  "baseURL": "/something",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/a/path/to/files"
}
```

`./traefik/dynamic/filebrowser-specific.yaml`:
```yaml
http:
  routers:
    filebrowser-share:
      rule: "Host(`mysite.com`) && PathPrefix(`/something`)"
      entryPoints:
        - websecure
      service: filebrowser-share
      tls:
        certResolver: letsencrypt
        options: modern@file

  services:
    filebrowser-share:
      loadBalancer:
        servers:
          - url: "http://filebrowser:80"
```
Adding the `/something` prefix to the the URL is required, since without it (`"baseURL": ""`) the /static files can't be loaded and the page does not display.

The problem is that even when restricting the access from the outside to https://mysite.com/something/share/{.+} and rejecting everything else, it is possible to click on the "Login" link there, and it'll redirect the user to https://mysite.com/login, which I don't want.

Would it be possible to support this feature a bit more officially? 

Ideally it would also be cool to specify the external url somewhere in the config so when I creating share links, it would automatically create and copy them with the external url.

Thanks
