### ISSUE TITLE
filebrowser.db always stays at 0 KB

### ISSUE THREAD

**Issue by Vexz00** [filebrowser/filebrowser#3668]
I just started using File Browser and I run it in Docker on my NAS. The `filebrowser.db` always stays at 0 KB, which is very weird, because I think it shouldn't. From my research it never stayed at 0 KB for other users. Everything seems to work fine so far but I haven't tested all features of File Browser yet.

Here's the compose script I used:
```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: File-Browser
    volumes:
      - /mnt/Tank:/srv
      - /mnt/Tank/Docker/File-Browser/filebrowser.db:/database.db
      - /mnt/Tank/Docker/File-Browser/filebrowser.json:/.filebrowser.json
    environment:
      - PUID=0
      - PGID=0
    ports:
      - 8147:80
    restart: always
```

This is the container's log:
```
2025/01/11 19:44:25 Warning: filebrowser.db can't be found. Initialing in /database/
2025/01/11 19:44:25 Using database: /database/filebrowser.db
2025/01/11 19:44:26 Using config file: /.filebrowser.json
2025/01/11 19:44:26 Listening on [::]:80
2025/01/11 19:44:39 /api/renew: 401 10.0.0.4 <nil>
2025/01/11 19:44:39 /api/renew: 401 10.0.0.4 <nil>
```

Apparently it can't find the `filebrowser.db`, but it's there and definitely a file, not a folder (which I heard docker likes to create when the file doesn't exist).

I used this [video tutorial](https://youtu.be/V6kHXWKwzn8?si=EubonCOrMGxp1IaI&t=370) to set it up. In the moment of the timestamp you can see that the guy created an empty file called `filebrowser.db`, and so did I. Is this even a "good" or "the right way"?
