### ISSUE TITLE
Help with deploying to coolify

### ISSUE THREAD

**Issue by nilsbtr** [filebrowser/filebrowser#3706]
```yaml
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER_80
    volumes:
      - type: bind
        source: /data/coolify/services/aw08ksso48sos0sogc8ooo4c/data
        target: /srv/vanilla
        isDirectory: true
      - type: bind
        source: /data/coolify/services/cgg4848cwoos8wwwg04ws0kg/data
        target: /srv/stoneblock
        isDirectory: true
      - type: bind
        source: ./database.db
        target: /database.db
        isDirectory: false
        content: ''
      - type: bind
        source: ./filebrowser.json
        target: /.filebrowser.json
        read_only: true
        content: "{\n  \"address\": \"0.0.0.0\",\n  \"port\": 8080\n}" 
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 2s
      timeout: 10s
      retries: 15
```

Hi tried deploying filebrowser to my coolify server for browsing minecraft server files. But for me it still shows all server root files and not only the coolify service files. Used the coolify template for the compose file and edited it you see it above.
