### ISSUE TITLE
filebrowser.db doesnt initialize properly

### ISSUE THREAD

**Issue by nilsbtr** [filebrowser/filebrowser#3707]
Logs:

```
2025-01-28T21:46:22.460029579Z 2025/01/28 21:46:22 Warning: filebrowser.db can't be found. Initialing in /.
2025-01-28T21:46:22.460052533Z 2025/01/28 21:46:22 Using database: /.filebrowser.db
2025-01-28T21:46:22.505365551Z 2025/01/28 21:46:22 Using config file: /.filebrowser.json
2025-01-28T21:46:22.593658423Z 2025/01/28 21:46:22 Listening on [::]:8080
```

This is my compose: 
```yaml
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER_80
    volumes:
      -
        type: bind
        source: /data/coolify/services/aw08ksso48sos0sogc8ooo4c/data
        target: /srv/vanilla
        isDirectory: true
      -
        type: bind
        source: /data/coolify/services/cgg4848cwoos8wwwg04ws0kg/data
        target: /srv/stoneblock
        isDirectory: true
      -
        type: bind
        source: ./filebrowser.db
        target: /.filebrowser.db
        content: ''
      -
        type: bind
        source: ./filebrowser.json
        target: /.filebrowser.json
        read_only: true
        content: |-
          {
            "address": "0.0.0.0",
            "port": 8080,
            "database": "/.filebrowser.db",
            "root": "/srv"
          }
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 2s
      timeout: 10s
      retries: 15
```
