### ISSUE TITLE
Merge the database and the configuration into a single config file

### ISSUE THREAD

**Issue by Encrypt** [filebrowser/filebrowser#371]
Hello,

As requested by @hacdias after a discussion on IRC, I am opening this issue to consider the possibility to merge:
- The configuration that is stored in the configuration file ; with
- The configuration stored in the database

Having a single "entry point" to configure filebrowser would be handier.

**Comment by hacdias** [comment]
Yeah, I really want to do this. Thanks for opening the issue.

Right now, the database contains:
- The users
- The configuration
- Share links

The good thing about having a database with BoltDB is that everything is really flawless and really easy to use. We could move users and configuration to the config file, but despite that being a good idea, it could also bring some problems:

- Multiple processes trying to edit the file
- If the user wanted to set the password via the config file they would need to encrypt it with the right algorithm (we won't store them in plain text!)
- Were would we put the share links?

So, my **tl;dr** is: I agree we have to change the mechanics of the configuration+database, but we need to define really well how are we going to do this 😄 

/cc @Equim-chan?

**Comment by Equim-chan** [comment]
### Using only one variable file
> Having a single "entry point" to configure filebrowser would be handier.

The db file is more than just configs (as hacdias mentioned, the share links don't belong to config). I don't really agree that we should merge the db into config file or vice versa. Plus, config file is not always writable (e.g. when used in Caddy as a plugin).

### Using two (current status) but they can be merged
Though I don't really agree that db should be handled by the user by hand, we can still make an extra feature to dump/merge the db. 

> Multiple processes trying to edit the file

The instance locks the db file, so it's unlikely that we can achieve writing online from external side. If we need to do that online, this feature should be embed in the application itself.

> If the user wanted to set the password via the config file they would need to encrypt it with the right algorithm (we won't store them in plain text!)

It's not allowed by design. Force overriding the password is a fault responsible to the user.

> Where would we put the share links?

Same as above.

### Notes
The current design of the config file is a bit confusing. Basically like `--allow-commands`, they are meant for the default value for new users but the words doesn't really tell and it looks like it applies globally.

**Comment by hacdias** [comment]
### About the Users & Passwords

What if we store the user information in the config file and the password in the database? Then, if a user was in the database and it didn't have a password, it would ask to set one on the first time. This way, there wouldn't be default passwords at all and it would be set at login time 😄 What do you think?

Example config file:

```yaml
port: 80
address: 127.0.0.1
baseURL: /admin
prefixURL: ''
noAuth: false
database: /path/to/database.db
log: stdout
plugin: ''
alternativeReCaptcha: false
reCaptchaKey: ''
reCaptchaSecret: ''

users:
  default:
    scope: /path/to/my/files
    allowCommands: true
    allowEdit: true
    allowNew: true
    commands:
      - git
      - svn
  admin:
    scope: /path/to/my/files
    allowCommands: true
    allowEdit: true
    allowNew: true
    commands:
      - git
      - svn
```

We could also add sort mode to the options (see #326).

The only problem I can find here is: what to do with the custom CSS?

### Add Event Handlers to Config file

See #246.

**Comment by Encrypt** [comment]
Hello @hacdias / @Equim-chan!

I have been thinking about this and I may have found a solution.
The idea would be to drop the configuration file and keep the database only.

When Filebrowser would start for the first time, you could interactively prompt the administrator to enter the different "key" parameters (baseURL, port, address...) via:
- The command line (after typing "filebrowser --config" for instance)
- Directly via the web interface (in that case, you would use a port by default on which the user could directly connect and set it up)

That way, the general configuration would also be in the database and any modification would be done directly via the interface.

That said, I'm not sure that is the best idea :stuck_out_tongue:

**Comment by maran** [comment]
Just dropping my two cents here as I see things from a different perspective, one you might want to ignore but I wanted to give it regardless 😛

So I'm looking to do unattended installations of Filebrowser for my users. They simply click "Install app" and select "Filebrowser". They pick a password and that should it be for them. Having passwords in the database for me would be a bit annoying since my software would need to write to the boltdb database to get the password in as I can't (or rather prefer not to need any) have any console input. 

Perhaps users could be bootstrapped from the config file?

```yaml
bootstrap:
  users:
    admin:
      password: sha1#707e663f6af05f7cce3fa9c8009e3817f991c821
      scope: /path/to/my/files
      allowCommands: true
      allowEdit: true
      allowNew: true
      commands:
        - git
        - svn
```

If on boot the bootstrap config is detected it imports this data into the database and removes it from the config file. Perhaps have some limitation as to when a bootstrap config will be imported for added security.
