### ISSUE TITLE
Make filebrowser works behind nginx-proxy with Docker

### ISSUE THREAD

**Issue by razaborg** [filebrowser/filebrowser#372]
Hi,
I'm trying to use filebrowser with an nginx-proxy frontend. Evrything dockerized.
The nginx-proxy is the [jwilder's nginx-proxy container](https://hub.docker.com/r/jwilder/nginx-proxy/) .

Usually the nginx-proxy is quite intelligent and only needs the backend container to run a webserver (apache, nginx, caddy or whatever) with the VIRTUAL_HOST environment variable defined, to be able to automatically redirect the user to the right container according to its VIRTUAL_HOST.

The only thing I get in my web browser is "connexion failed" when I try to load files.mydoma.in. 
Whereas running filebrowser (docker) with port forwarding on the host works fine !! But I don't want to expose a port on the internet, I want filebrowser beeing accessible through a vhost :(

EDIT: I succeed to access the filebrowser container through nginx, but now I'm stuck with a page which keeps loading

Here is my docker-compose file:
```

version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - '/mnt2/root/certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    ports:
      - 443:443
    networks:
      - web
  filebrowser:
    image: hacdias/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    ports:
      - 8080:80
    volumes:
      - /mnt2/data:/srv
      - /root/dockerstuff/filebrowser/config.json:/config.json
    environment:
      - VIRTUAL_HOST=files.mydoma.in
    networks:
      - web
networks:
  web:
    driver: bridge
```

And here is my config.json:

```
{
  "port": 80,
  "address": "0.0.0.0",
  "baseURL": "/files",
  "database": "/etc/database.db",
  "scope": "/srv",
  "log": "stdout",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": []
}
```

I really don't understand why this configuration does not work, so maybe you could give me some clues ?

**Comment by razaborg** [comment]
UPDATE

With this configuration I got something better. Filebrowser is now accessible through nginx-proxy, but only in HTTP, I've not yet figured out why.
```
version: '2.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    hostname: nginx-proxy
    volumes:
      - '/mnt2/root/certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    ports:
      - 80:80
      - 443:443
    networks:
      - web

  filebrowser:
    image: hacdias/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    volumes:
      - /mnt2/data:/srv
      - /tmp/filebrowser:/config
    environment:
      - VIRTUAL_HOST=files.mydoma.in
      - VIRTUAL_PROTO=http
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    command: "-p 80 -s /srv -d /config/database.db"
    user: "1002:50"
    networks:
      - web

networks:
  web:
    driver: bridge
```

**Comment by UnAfraid** [comment]
Works fine for me

**Comment by hacdias** [comment]
Could you share your config @UnAfraid ?

**Comment by UnAfraid** [comment]
docker-compose.yml
```yml
version: "2.1"

services:
 server:
    image: hacdias/filebrowser
    container_name: filebrowser
    ports:
      - 7080:80
    volumes:
      - ./data:/srv
      - ./config:/config
    restart: unless-stopped
    entrypoint: /filebrowser --config /config/config.json
```

config/config.json
```json
{
  "port": 80,
  "address": "",
  "baseurl": "https://files.mydomain.org",
  "database": "/config/database.db",
  "logfile": "/config/filemanager.log",
  "scope": "/srv",
  "viewMode": "list",
  "allowCommands": false,
  "allowEdit": false,
  "allowNew": true,
  "commands": []
}
```

nginx/sites-enabled/files.mydomain.org.conf
```nginx
server {
        listen                                          80;
        server_name                                     files.mydomain.org;
        # enforce https
        return                                          301     https://$server_name$request_uri;
}

server {
        server_name                                     files.mydomain.org;
        # General SSL Configuration
        include                                         snippets/ssl.conf;
        ssl_certificate_key                             ssl/files.mydomain.org.key;
        ssl_certificate                                 ssl/files.mydomain.org.crt;
        client_max_body_size                            0;

        location / {
                proxy_pass                              http://localhost:7080;
                proxy_set_header                        X-Forwarded-Host $host;
                proxy_set_header                        X-Forwarded-Server $host;
                proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version                      1.1;
                proxy_set_header                        Upgrade $http_upgrade;
                proxy_set_header                        Connection "upgrade";
        }

        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
}
```

ngins/snippets/ssl.conf
```nginx
listen                                  443 ssl;
listen                                  [::]:443 ssl;
keepalive_timeout                       70;
access_log                              /var/log/nginx/$server_name-access.log;

ssl                                     on;
ssl_protocols                           TLSv1.2;
ssl_ciphers                             'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_prefer_server_ciphers               on;
ssl_session_cache                       shared:SSL:10m;
ssl_session_timeout                     24h;
ssl_buffer_size                         4k;
ssl_session_tickets                     off;
ssl_ecdh_curve                          secp384r1;

# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
ssl_dhparam                             ssl/dhparam.pem;

# enable ocsp stapling (mechanism by which a site can convey certificate revocation information to visitors in a privacy-preserving, scalable manner)
# http://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/
resolver                                8.8.4.4 8.8.8.8 valid=300s;
resolver_timeout                        10;
ssl_stapling                            on;
ssl_stapling_verify                     on;
ssl_trusted_certificate                 /etc/ssl/certs/DST_Root_CA_X3.pem;

# Disable gzip to avoid the removal of the ETag header
gzip off;

# Disable requests by non handled ssl vhosts
if ($host != $server_name) {
        return 444;
}

add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```
