### ISSUE TITLE
Implement Locking Mechanism for High Availability

### ISSUE THREAD

**Issue by YourSandwich** [filebrowser/filebrowser#3741]
Hi,

I'm running Filebrowser on Kubernetes with 3 replicas using a shared persistent volume for the database. 
The issue: when sharing the database between pods, only one pod boots up while the others time out accessing it. If I run without sharing the database, HA works, but any user changes vanish on redeployment.

It'd be nice if a locking mechanism or similar coordination was added so that multiple replicas can safely share a persistent database without blocking each other.

Current deployment setup:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: filebrowser
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data-pvc
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-deployment
  namespace: filebrowser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2
        args:
          - "--database"
          - "/config/database.db"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: filebrowser-data
            mountPath: /srv
            subPath: srv
          - name: filebrowser-data
            mountPath: /config
            subPath: config
      volumes:
        - name: filebrowser-data
          persistentVolumeClaim:
            claimName: filebrowser-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  namespace: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-ingress
  namespace: filebrowser
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
    - host: files.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser-service
                port:
                  number: 80
```

Thanks
