### ISSUE TITLE
Problem while instaling on ubuntu lts with docker compose

### ISSUE THREAD

**Issue by szszl0** [filebrowser/filebrowser#3784]
So im trying to install filebrowser on my freshly installed ubuntu lts with nothing but docker and docker compose on it.
Im creating directory in with i created srv folder, empty filebrowser.db, filebrowser.json with config from filebrowser page and docker-compose.yml.

docker-compose.yml:

```
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - "8080:80"
    volumes:
      - ./srv:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    restart: always
```

and i get this in my console:

```
filebrowser  | goroutine 1 [running]:
filebrowser  | github.com/filebrowser/filebrowser/v2/cmd.init.python.func35(0x1438540, {0x1467be0, 0x0, 0x0})
filebrowser  |  /home/runner/work/filebrowser/filebrowser/cmd/utils.go:97 +0x35e
filebrowser  | github.com/spf13/cobra.(*Command).execute(0x1438540, {0xc000104040, 0x0, 0x0})
filebrowser  |  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
filebrowser  | github.com/spf13/cobra.(*Command).ExecuteC(0x1438540)
filebrowser  |  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
filebrowser  | github.com/spf13/cobra.(*Command).Execute(...)
filebrowser  |  /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
filebrowser  | github.com/filebrowser/filebrowser/v2/cmd.Execute()
filebrowser  |  /home/runner/work/filebrowser/filebrowser/cmd/cmd.go:9 +0x1a
filebrowser  | main.main()
filebrowser  |  /home/runner/work/filebrowser/filebrowser/main.go:8 +0xf
filebrowser  | panic: mkdir /database: permission denied
```
sometimes instead of panic line there is: filebrowser exited with code 2

Any idea what am i doing wrong?
