### ISSUE TITLE
Support for password changing via command line or config

### ISSUE THREAD

**Issue by maran** [filebrowser/filebrowser#381]
I'm trying to add support for Filebrowser to my one-click-install hosting platform.

Ideally I would love some way to change the password before the first login so that I can install and configure the application for my end-user without having to give everybody the admin/admin details. (they might be lazy and not change it leading to security issues).

Would you be open to accepting a PR that implements some form of setting the initial password via a config or command line option? Is there a better way you can think of to do this?

**Comment by Equim-chan** [comment]
For a further goal, I think a full featured HTTP API can be implemented to help.

**Comment by hacdias** [comment]
Hello @maran and @Equim-chan,

Here are my two cents: I think we have too much command line flags. When I say this, I mean: we don't have all of the possible features withing command line flags and we don't have all the possible configuration in a configuration file.

I think we should invest on creating a better configuration file. See #371.

**Comment by ghost** [comment]
I also vote for this issue. The current solution with a default admin/admin user makes automated deployments impossible or unsafe. There is always a manual step required.

I am deploying with Docker in Kubernetes and it's common to specify such information in a secret, which is then used to populate environment variables for the container.

**Comment by bcardiff** [comment]
Now that #360 is in master I can vote for this also :-). I was also interested in a one-click-install, in my case for rancher, but without admin password config option is not a good fit for public usage.

**Comment by eine** [comment]
Indeed, with #506 we removed possible inconsistencies between the config file, flags and envvars. Also a placeholder for database related CLI (sub)commands was added.

Therefore, it is relatively straightforward to add default `user` and `password` fields to the config file, flags and envvars at the same time. The user is not a problem, but as commented by @hacdias in [371-issuecomment-370157182](https://github.com/filebrowser/filebrowser/issues/371#issuecomment-370157182) it is not desirable at all to store passwords in plain text.

---

We might add several subcommands to `filebrowser db`:

- `filebrowser db init` would initialize a db file (i.e. execute func `Setup`) without starting the server (i.e. do not execute func `http.Serve`).
- `filebrowser db set pass <user>` could prompt for a password (twice) and update the database. 
- `filebrowser db hash` would take a string and execute `HashPassword`. Then, the user would use the hash in the config/flag/envvar when executing `filebrowser serve`. However, I don't know if this is secure enough.

---

Moreover, a very demanded feature is to allow programmatically adding/removing/editing user entries in the database. A possible approach is to use a YAML file to define users and groups. E.g.:

``` yaml
- &g-admin
  scope: "/srv"
  allowCommands: true
  commands:
    - git
    - svn
    - wget
- <<: *g-admin
  name: admin
  passwd: <hash>
- <<: *g-admin
  name: otheradmin
  passwd: <hash>
- &g-agroup
  allowCommands: true
  commands:
    - ls
- <<: *g-agroup
  name: auser
  passwd: <hash>
  scope: "/srv/auser"
- <<: *g-agroup
  name: anotheruser
  passwd: <hash>
  scope: "/srv/anotheruser"
- name: otheruser
  passwd: <hash>
```

In this context, a single flag/envvar/config field would be required, which would point to the yaml file. Note that the admin or admins would be just entries in this file. Furthermore, the file could be automatically edited/removed by the backend after the content is used to init/sync the database. Also, this file would be provided to either `filebrowser serve`, `filebrowser db init` or to both of them.

Nevertheless, equivalent JSON or TOML versions of the YAML can be supported, although I think that those formats are much more verbose in this context.

But, I don't know how this scheme fits with Docker and Kubernetes secrets, as commented by @Jens-vd. Maybe `--admin.user` and `--admin.pass` can be optional flags for `filebrowser db init` only?
