### ISSUE TITLE
Failed authentication logs

### ISSUE THREAD

**Issue by kieferlam** [filebrowser/filebrowser#3822]
Are there logs for when a user fails an attempt to log in? I want to use fail2ban to ban ips that fail to log in after some amount of tries.

I am running through docker but I cannot find the log files

**Comment by gtsteffaniak** [comment]
I don't believe api event logs happen on this repo. I have a [fork](https://github.com/gtsteffaniak/filebrowser) that includes advanced logging. By default, it logs API actions which include failed logins from a remote IP.

<img width="932" alt="Image" src="https://github.com/user-attachments/assets/48ee62aa-4e25-48a6-8dde-181d2aef0353" />

It includes options to route certain logs to files as well, you can view the [configuration wiki](https://github.com/gtsteffaniak/filebrowser/wiki/Logging) here if you're interested in trying it out.

for example to have default std out logging and log API errors to file, you could even run a script to fail2ban over the output file:

```
server:
  logging:
    - output: "api-events.log"
      levels: disabled
      noColors: true
      apiLevels: "warning|error"
```
