### ISSUE TITLE
Redeployed Image Results in Database being Reset?

### ISSUE THREAD

**Issue by W1BTR** [filebrowser/filebrowser#3867]
Just re-pulled the image to update filebrowser and found that all accounts, shares, etc are gone. Volume hasnt changed, so Im unsure why that would be. Id like to avoid this in the future, so is there a better config you recommend? Are credentials not stored in `/config`?

Just upgraded to 2.32.0.

```
services:
    filebrowser:
        image: filebrowser/filebrowser
        restart: always
        volumes:
            - 'filebrowser-config:/config'
            - '/newnas/shares:/srv'
        ports:
            - '8082:80'
volumes:
 filebrowser-config:
```

**Comment by Anndres47** [comment]
Same problem here, happened two times now.

**Comment by W1BTR** [comment]
> Same problem here, happened two times now.

Just to confirm, does restarting to container also cause this issue with this update?

**Comment by hematic** [comment]
Can confirm i have this same issue.

Restarting the container alone does not do this. However each time the image upgrades i lose my user and it sets back to the default admin/admin which is terrifying.

```
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - ${NETWORK}
    volumes:
      - /mnt:/srv
      - ${ROOT_PATH}/filebrowser/filebrowser.db:/database/filebrowser.db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 4444:80
    labels:
      #Routers
      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.rule=Host(`files.apps.,redacted.net`)"
      - "traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect"
      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.rule=Host(`files.apps.redacted.net`)"
      - "traefik.http.routers.filebrowser-secure.tls=true"
      - "traefik.http.routers.filebrowser-secure.service=filebrowser"
      #Service Definition
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      #Middleware Definitions
      - "traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https"
      #Other Labels
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK}"
```
