### ISSUE TITLE
Docker Latest Broken

### ISSUE THREAD

**Issue by juan11perez** [filebrowser/filebrowser#518]
Running docker image in Ubuntu 18.04

watchtower updated to latest and container is producing these errors:

```
panic: unknown command "c" for "filebrowser serve"
goroutine 1 [running]:
github.com/filebrowser/filebrowser/cli/cmd.Execute()
	/go/src/github.com/filebrowser/filebrowser/cli/cmd/root.go:36 +0x5f
main.main()
	/go/src/github.com/filebrowser/filebrowser/cli/main.go:6 +0x20
```
downgraded to image v1.10.0 and it's working again with no errors

**Comment by eine** [comment]
Hi @juan11perez! Thanks for reporting. Please, could you let us know the exact command you are using to start the container? I just tried it and it works as expected:

``` bash
$ docker pull filebrowser/filebrowser:latest
$ docker run --rm -itv $(pwd)/srv:/srv -p 5566:80 filebrowser/filebrowser:latest -c /config.json
2018/08/22 11:15:35 Using config file: /config.json
2018/08/22 11:15:35 Listening on [::]:80
```

**Comment by juan11perez** [comment]
thank you for your response. Im using docker-compose:

```
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser #:v1.10.0
    restart: unless-stopped
    volumes:
    - /srv/docker/filebrowser/config.json:/etc/config.json
    - /srv/docker/filebrowser/database.db:/etc/database.db
    - /:/srv
    environment:
    - PGID=1000
    - PUID=1000
    ports:
    - "1580:80"
    command: -- c
```

I believe my last line (command: --c) is incorrect and is creating the problem. I removed it and the container  is running.

**Comment by eine** [comment]
Indeed, `-c` is the shorthand for `--config` and it requires an argument behind, which should be a configuration file. `c` (without a hyphen) is not a flag, but interpreted as either a subcommand or a positional argument. Since positional arguments are not accepted/required, and no `c` subcommand exists, it shows the error.

What were you trying to achieve with `-- c`?

**Comment by eine** [comment]
BTW, note that the entrypoint in the container is `filebrowser` (https://github.com/filebrowser/filebrowser/blob/master/Dockerfile), and the default config file (https://github.com/filebrowser/filebrowser/blob/master/Docker.json) is `/.filebrowser.json`. Therefore, unless you set your own config file, flags or environment variables, the database is created in `/database.db` and the default config file is used.

So, in the docker-compose file above, this won't work:

```
    - /srv/docker/filebrowser/config.json:/etc/config.json
    - /srv/docker/filebrowser/database.db:/etc/database.db
```

You should set `/srv/docker/filebrowser/config.json:/.filebrowser.json` and ensure that database is set to `/etc/database.db` in your `config.json`.

Alternatively, you can keep the volumes untouched, and use command `-c /etc/config.json`.

**Comment by juan11perez** [comment]
thank you very much for your time and guidance. the use of the -c argument was poor understanding from my side. I understood that it had to be added as a command to "activate" the config file.

I modified my compose in line wit your above feedback as such:

 ```
 filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser #:v1.10.0
    restart: unless-stopped
    volumes:
    - /srv/docker/filebrowser/database.db:/etc/database.db
    - /srv/docker/filebrowser/config.json:/.filebrowser.json
    - /:/srv
    environment:
    - PGID=1000
    - PUID=1000
    ports:
    - "1580:80"
```

but it wont start and it's producing this error:


```
goroutine 1 [running]:
github.com/filebrowser/filebrowser/cli/cmd.initConfig()
	/go/src/github.com/filebrowser/filebrowser/cli/cmd/root.go:71 +0x2ef
github.com/spf13/cobra.(*Command).preRun(0x192f5e0)
	/go/src/github.com/spf13/cobra/command.go:792 +0x49
github.com/spf13/cobra.(*Command).execute(0x192f5e0, 0x19600f0, 0x0, 0x0, 0x192f5e0, 0x19600f0)
	/go/src/github.com/spf13/cobra/command.go:728 +0x147
github.com/spf13/cobra.(*Command).ExecuteC(0x192f120, 0x0, 0x0, 0x0)
	/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x192f120, 0x0, 0xb5521b)
	/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/filebrowser/filebrowser/cli/cmd.Execute()
	/go/src/github.com/filebrowser/filebrowser/cli/cmd/root.go:36 +0x32
main.main()
	/go/src/github.com/filebrowser/filebrowser/cli/main.go:6 +0x20
```

**Comment by eine** [comment]
In order to bind `database.db` and `config.json` inside the container, these must exists in the host:

``` bash
$ mkdir tmp-fb
$ cd tmp-fb
$ touch database.db
$ vim config.json
# see content below
$ vim docker-compose.yml
# see content below
$ docker-compose up
Starting filebrowser ... done
Attaching to filebrowser
filebrowser    | 2018/08/29 13:47:59 Listening on [::]:80
filebrowser    | 2018/08/29 13:47:59 Using config file: /.filebrowser.json
```

``` json
{
  "port": 80,
  "address": "",
  "database": "/etc/database.db",
  "defaults": {
    "scope": "/srv",
    "allowCommands": true,
    "allowEdit": true,
    "allowNew": true,
    "commands": []
  }
}
```

``` yml
filebrowser:
   container_name: filebrowser
   image: filebrowser/filebrowser #:v1.10.0
   restart: unless-stopped
   volumes:
   - ./database.db:/etc/database.db
   - ./config.json:/.filebrowser.json
   - /:/srv
   environment:
   - PGID=1000
   - PUID=1000
   ports:
   - "1580:80"
```

However, I would not recommend exposing all the system with `/:/srv`.
