### ISSUE TITLE
--auth.method='none' gets ignored

### ISSUE THREAD

**Issue by FlorianWendelborn** [filebrowser/filebrowser#534]
**Description**
I’m trying to mount filebrowser behind a caddy `proxy /files/ http://filebrowser`. I don’t need any authentication, so I passed `command: "--auth.method='none' --baseurl /files"` in my `docker-compose.yml`.

**Expected behaviour**
filebrowser should not ask for any username or password

**What is happening instead?**
filebrowser asks for username + password

**How to reproduce?**
```yml
version: '3.5'
services:
  filebrowser:
    image: filebrowser/filebrowser
    command: "--auth.method='none' --baseurl /files"
    depends_on:
      - proxy
  proxy:
    image: abiosoft/caddy
    ports:
      - '80:80'
    volumes:
      - './Caddyfile:/etc/Caddyfile'
```

```Caddyfile
http://0.0.0.0:80 {
    proxy /files http://filebrowser
}
```

**Comment by eine** [comment]
Hi @dodekeract! Can you please tell us which version of filebrowser are you using? It'd be great if you could also paste the log of filebrowser.

**Comment by FlorianWendelborn** [comment]
@1138-4EB latest version that’s published to Docker.

Where do I find the log files?

**Comment by eine** [comment]
If you do start the container as a daemon, you can get the log with `docker log <container_name>`. Also, I think that `docker-compose --verbose up` might show it.

**Comment by alx** [comment]
Same issue here, I'm using `File Browser version (dae992d4)`

I was not able to identify the issue with this auth flag, I had to revert to previous version `v1.10.0` in `docker-compose.yml` `image` parameters

```
  filebrowser:
    container_name: eris_filebrowser
    image: filebrowser/filebrowser:v1.10.0
    volumes:
      - /opt/platform:/srv
      - ./config/tmp_filebrowser/database.db:/etc/database.db
      - ./config/tmp_filebrowser/config.json:/config.json
```

**Comment by rhjmoore** [comment]
Sorry to piggy back on this issue, but I'm trying to debug an issue i have with access to one particular folder. How can turn I up the verbosity of the log, either using the config.json file or in a command line option?

**Comment by eine** [comment]
@alx I just tried:

``` bash
docker pull filebrowser/filebrowser
docker run --rm -it -p 5555:80 filebrowser/filebrowser --auth.method='none'
```
and it works as expected. Can you provide more info about your context? How are you setting the authentication method?

@rhjmoore, AFAIK there is no verbosity option for the log. What info do you expect to be logged which is not?

**Comment by alx** [comment]
Hi @1138-4EB 

Thanks for your feedback.

I'm using this `docker-compose` config (various paths might be uncorrect, I'm just copy/pasting the current working version without the v1.10.0 tag, but it's was setup more or less like this):

```
  filebrowser:
    container_name: eris_filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /opt/platform:/srv
      - /opt/platform/filebrowser/database.db:/etc/database.db
      - ./config/filebrowser/config.json:/config.json
```

The `config.json` contains the `auth.method='none'` parameter:

```
{
  auth: {
    method: 'none'
    ...
```

I'll try to reproduce the complete setup of my defunc config when I've got time.
I remember trying to use the `command` parameter in `docker-compose` to force the `auth-method`, but I had the same issue.

**Comment by rhjmoore** [comment]
Hi,

I have a folder that filebrowser won't open, and nothing (beyond the fact that filebrowser is listening to the port) is recorded in the log. Otherwise it performs wonderfully. I'll file a separate issue for specific guidance on how to resolve.

Thanks,
Ross

**Comment by FlorianWendelborn** [comment]
@1138-4EB

```sh
fb ❯ vi docker-compose.yml
# copy-paste code from my repro
fb ❯ vi Caddyfile
# copy-paste code from my repo
fb ❯ docker-compose up
Creating network "fb_default" with the default driver
Pulling proxy (abiosoft/caddy:)...
latest: Pulling from abiosoft/caddy
8e3ba11ec2a2: Already exists
65e56e6ede27: Pull complete
acae7731bd69: Pull complete
38f2797390ad: Pull complete
e4a08ad5278d: Pull complete
9aa978fb5a6b: Pull complete
Digest: sha256:918431577452be0f3117fa056b1280f0ef0cd2f002473f405f375495eed168f4
Status: Downloaded newer image for abiosoft/caddy:latest
Pulling filebrowser (filebrowser/filebrowser:)...
latest: Pulling from filebrowser/filebrowser
65e0b2b1d200: Pull complete
eb25635ba1b5: Pull complete
5e7f38ec4625: Pull complete
Digest: sha256:2e7fa72db2cba55b1cd587152eeea65b9992b218906f23f1da2445ede5454abc
Status: Downloaded newer image for filebrowser/filebrowser:latest
Creating fb_proxy_1 ... done
Creating fb_filebrowser_1 ... done
Attaching to fb_proxy_1, fb_filebrowser_1
proxy_1        | Activating privacy features... done.
proxy_1        | http://0.0.0.0
filebrowser_1  | 2018/10/04 07:47:02 Using config file: /.filebrowser.json
proxy_1        | 2018/10/04 07:47:01 http://0.0.0.0
filebrowser_1  | 2018/10/04 07:47:02 Listening on [::]:80
proxy_1        | 2018/10/04 07:47:02 [WARNING] Sending telemetry (attempt 1): telemetry server returned status code 403 - backing off and retrying
proxy_1        | 2018/10/04 07:47:11 [NOTICE] Sending telemetry: we were too early; waiting 1h0m37.262646958s before trying again
```

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1133858/46460004-e4b96580-c7ba-11e8-96e5-b50c111715bf.png">

**Comment by eine** [comment]
@dodekeract, I think that your issue might be related to #522, because you are using a custom baseurl. Can you please try setting the auth.method but keeping the default baseurl? If that works for you, we can close this issue an focus on #522.

**Comment by alx** [comment]
Hi,

I had time to return on this issue today, and the `--auth.method='none'` flag configuration is indeed working fine.

But then I've got auth error in the frontend code, I'd go back to tag v1.10.0 until I've got more time to debug this one.

```
base64.js:153 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at atob (http://eris:18104/filebrowser/static/js/app.b5d324c0f51da18413a4.js:23:123879)
    at _decode (http://eris:18104/filebrowser/static/js/app.b5d324c0f51da18413a4.js:23:124223)
    at Object.decode (http://eris:18104/filebrowser/static/js/app.b5d324c0f51da18413a4.js:23:124259)
    at r (http://eris:18104/filebrowser/static/js/app.b5d324c0f51da18413a4.js:11:33648)
    at XMLHttpRequest.n.onload (http://eris:18104/filebrowser/static/js/app.b5d324c0f51da18413a4.js:11:33984)
```

It seems to come from this place:

https://github.com/filebrowser/frontend/blob/master/src/router/index.js#L127

where the route '/*' is `meta.requiresAuth = true`

Then it goes deeper and tries to parse a token that doesn't exist (it's parsing and html response): 

https://github.com/filebrowser/frontend/blob/master/src/utils/auth.js#L6

where the string, in the decode function, equals `jsonprovidesmetadatausedwhenyourwebappisaddedtothehomescreenonAndroid`

---

Not sure if it's related, of if I should open another ticket, but with the current config, I've got various types of path calling css/js files, somes contain with the `baseurl`, those in the `<head>` not 

```
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no"><meta name=base content=""><meta name=staticgen content=""><meta name=noauth content="false"><meta name=version content="(dae992d4)"><meta name=recaptcha content=""><title>File Browser</title><link rel=icon type=image/png sizes=32x32 href="/static/img/icons/favicon-32x32.png"><link rel=icon type=image/png sizes=16x16 href="/static/img/icons/favicon-16x16.png"><link rel=manifest href="/static/manifest.json"><meta name=theme-color content=#2979ff><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=apple-mobile-web-app-title content=assets><link rel=apple-touch-icon href="/static/img/icons/apple-touch-icon-152x152.png"><meta name=msapplication-TileImage content="/static/img/icons/msapplication-icon-144x144.png"><meta name=msapplication-TileColor content=#2979ff><script>CSS = ""</script><link rel=preload href="/static/js/app.b5d324c0f51da18413a4.js" as=script><link rel=preload href="/static/css/app.91cd8ef5071f98059455a4174cb732ed.css" as=style><link rel=preload href="/static/js/manifest.123220cb93b9d190f6f3.js" as=script>...<script type=text/javascript src="/filebrowser/static/js/manifest.123220cb93b9d190f6f3.js"></script><script type=text/javascript src="/filebrowser/static/js/app.b5d324c0f51da18413a4.js"></script></body></html>
```





---

Here is my config:

* docker-compose.yml

```
  filebrowser:
    container_name: dev_filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /opt/platform:/srv
      - /opt/platform/filebrowser/database.db:/database.db
      - ./config/filebrowser/config.json:/.filebrowser.json
```

* filebrowser.json

```
{
  "port": 80,
  "address": "",
  "database": "/database.db",
  "baseurl": "/filebrowser",
  "auth": {
    "method": "none"
  },
  "defaults": {
    "scope": "/srv/data",
    "allowCommands": false,
    "allowEdit": true,
    "allowNew": true,
    "commands": []
  }
}
```
