### ISSUE TITLE
[v2] Failing to start a container with the database file bind to the host

### ISSUE THREAD

**Issue by eine** [filebrowser/filebrowser#628]
**Description**

I am trying to start a container on Win10, with the database file bind to the host:

``` bash
# docker pull filebrowser/filebrowser
Using default tag: latest
latest: Pulling from filebrowser/filebrowser
ae234d35f46b: Pulling fs layer
f0acc2239527: Pulling fs layer
318cebe7593c: Pulling fs layer
f0acc2239527: Verifying Checksum
f0acc2239527: Download complete
ae234d35f46b: Verifying Checksum
ae234d35f46b: Download complete
ae234d35f46b: Pull complete
f0acc2239527: Pull complete
318cebe7593c: Verifying Checksum
318cebe7593c: Download complete
318cebe7593c: Pull complete
Digest: sha256:f85878397d63db346cf81c56f2b9a08e5c3b860891ef547fe393598c02c3463b
Status: Downloaded newer image for filebrowser/filebrowser:latest

# winpty docker run --rm -itv /$(pwd)/filebrowser.db://database.db filebrowser/filebrowser
2019/01/09 15:40:25 open /database.db: is a directory
# rm -rf filebrowser.db/
# touch filebrowser.db
# winpty docker run --rm -itv /$(pwd)/filebrowser.db://database.db filebrowser/filebrowser
2019/01/09 15:41:05 Using config file: /.filebrowser.json
2019/01/09 15:41:05 the resource does not exist
```

**Expected behaviour**
I'd expect the container to start and setup the database. This was the procedure with v1.

**What is happening instead?**
It seems that, because the database file exists, filebrowser does not initialize it. So, when trying to read content from it, it fails.

**Comment by hacdias** [comment]
@1138-4EB maybe we should add a little info to the DB telling if it's initialized or not. Maybe adding a "version" info. That way, when there are structural updates, we can upgrade the DB without user intervention. I can take care of that 😄

**Comment by eine** [comment]
For this specific case, where the size of the DB is 0, I think that we can consider it equivalent to an unexisting DB file. It is almost the same situation; we just avoid the creation of the file.

Nevertheless, I think that adding some "version" info is an interesting feature. I am just not sure about all the contexts:

- DB file does not exist
    - Create and quicksetup.
- DB file does exist but size is 0
    - quicksetup.
- DB file does exist, size is not 0, and there is a version field
    - Run normally
    - or update if version is old.
- DB file does exist, size is not 0, but there is no version field
    - Should we remove the existing content? Write our own while keeping the existing data? Ask the user?

**Comment by hacdias** [comment]
@1138-4EB we can say invalid database file for the last case.

**Comment by DarkPark** [comment]
not a new user to docker
but it was absolutely not clear that file `database.db` should be created manually beforehand with zero size
afters dozens of other projects it's the first time I had to do such things to start a container

**Comment by MYZ6** [comment]
I've just remembered how to create an empty file: `touch filebrowser.db`

**Comment by DarkPark** [comment]
@MYZ6 it's not a problem to create a file. The problem that it's not in the manual. Besides in general it's a strange solution.

**Comment by oonqt** [comment]
This issue is still a problem years later, both official & linuxserver docker images have this problem. Why has such a simple issue had nothing done to solve it yet?

**Comment by Mister-Prime** [comment]
> ... linuxserver docker images ...

Several months later and filebrowser has been dropped from linuxserver.io which is kinda telling.

**Comment by Owned67** [comment]
getting same problem... no solution? :x

` sudo docker run -v /home/owned67/filebrowser:/srv  -v /home/owned67/filebrowser/filebrowser.db:/database/filebrowser.db     -v /home/owned67i/filebrowser/settings.json:/config/settings.json     -e PUID=$(id -u)     -e PGID=$(id -g)     -p 8080:8080     filebrowser/filebrowser:s6` return:

> [migrations] started
> [migrations] no migrations found
> ───────────────────────────────────────
>   _____ __ __ _____ _____ _____ _____
>  |     |  |  |   __|_   _|     |     |
>  |   --|  |  |__   | | | |  |  | | | |
>  |_____|_____|_____| |_| |_____|_|_|_|
>        _____ __ __ _ __    ____
>       | __  |  |  | |  |  |    \
>       | __ -|  |  | |  |__|  |  |
>       |_____|_____|_|_____|____/
> 
>   Based on images from linuxserver.io
> ───────────────────────────────────────
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> 
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
> 2024/08/27 13:20:05 Using database: /database/filebrowser.db
> 2024/08/27 13:20:05 open /database/filebrowser.db: is a directory
> 2024/08/27 13:20:06 Using database: /database/filebrowser.db
> 2024/08/27 13:20:06 open /database/filebrowser.db: is a directory
> 2024/08/27 13:20:07 Using database: /database/filebrowser.db
> 2024/08/27 13:20:07 open /database/filebrowser.db: is a directory

**Comment by treverehrfurth** [comment]
Still no solution on this? Running into the same problem, the database file I created just remains untouched after docker compose up

**Comment by treverehrfurth** [comment]
I got it working, they changed their pointers, had to reference their new install docs:

```yaml
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mnt/share/treshare:/srv #Change to match your directory
      - ./filebrowser.db:/database.db #Change to match your directory
      - ./filebrowser.json:/filebrowser.json #Change to match your directory
      - ./branding:/branding
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 8095:80 #Change the port if needed
    restart: unless-stopped
```

Their Docker install pointers:
```yaml
docker run \
    -v /path/to/root:/srv \
    -v /path/filebrowser.db:/database.db \
    -v /path/.filebrowser.json:/.filebrowser.json \
    -u $(id -u):$(id -g) \
    -p 8080:80 \
    filebrowser/filebrowser
```

With this, I got mine working and persisting and the database file populated after the compose up.

**Comment by karst** [comment]
> services:
>   filebrowser:
>     image: filebrowser/filebrowser:latest
>     container_name: filebrowser
>     volumes:
>       - /mnt/share/treshare:/srv #Change to match your directory
>       - ./filebrowser.db:/database.db #Change to match your directory
>       - ./filebrowser.json:/filebrowser.json #Change to match your directory
>       - ./branding:/branding
>     environment:
>       - PUID=$(id -u)
>       - PGID=$(id -g)
>     ports:
>       - 8095:80 #Change the port if needed
>     restart: unless-stopped
> 


I tried this too but then I run into:

``` ERROR: for filebrowser  Cannot start service filebrowser: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/docker/filebrowser/filebrowser.db" to rootfs at "/database.db": mount /docker/filebrowser/filebrowser.db:/database.db (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type ```

This is what `/docker/filebrowser/` looks like 

![Image](https://github.com/user-attachments/assets/4809147c-34eb-4136-8af7-56b17fb1a1d9)

**Comment by sosnus** [comment]
Do not mount files .db directly
Instead this:
```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mnt/share/treshare:/srv #Change to match your directory
      - ./filebrowser.db:/database.db #Change to match your directory
      - ./filebrowser.json:/filebrowser.json #Change to match your directory
      - ./branding:/branding
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - 8095:80 #Change the port if needed
    restart: unless-stopped
```

do this:

```
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mnt/share/treshare:/srv #Change to match your directory
      - /<yourpath>/filebrowser/database/:/database # CHANGE: mount dir, not file
      - ./filebrowser.db:/database.db #Change to match your directory
      - ./filebrowser.json:/filebrowser.json #Change to match your directory
      - ./branding:/branding
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    command:
      - --database      # CHANGE: overwrite default file place
      - /database/filebrowser.db     # CHANGE: overwrite default file place
    ports:
      - 8095:80 #Change the port if needed
    restart: unless-stopped
```
