### ISSUE TITLE
Overriding favicon.ico doesn't seem to work

### ISSUE THREAD

**Issue by memotype** [filebrowser/filebrowser#636]
**Description**
I have a Docker image based off of the upstream filebrowser/filebrowser:latest image, and I'm adding a favicon.ico to /style/img/icons/favicon.ico and I have a db.yml file with settings.branding.files set to "/style" that I'm importing to the database, but the favicon isn't being used. I'm testing in Firefox private browsing mode to make sure caching isn't the problem. The file path is based on the example linked to from the docs [here](https://github.com/filebrowser/frontend/tree/master/public/img/icons). Adding a custom logo to /style/img/logo.svg works, just not the favicon.

**Expected behaviour**
favicon set to my logo.

**What is happening instead?**
Default favicon is being used.

**Additional context**
N/A

**How to reproduce?**
Add custom favicon.ico to img/icons/favicon.ico and set the base directory in YAML file to be imported to database.

**Files**

db.yml:

```
settings:
  signup: false
  defaults:
    scope: .
    locale: en
    viewmode: list
    sorting:
      by: name
      asc: false
    perm:
      admin: false
      execute: false
      create: false
      rename: false
      modify: false
      delete: false
      share: false
      download: true
    commands: []
  authmethod: json
  branding:
    name: "My File Portal"
    disableexternal: true
    files: "/style"
  commands:
    after_copy: []
    after_delete: []
    after_rename: []
    after_save: []
    after_upload: []
    before_copy: []
    before_delete: []
    before_rename: []
    before_save: []
    before_upload: []
  shell:
  - ""
  rules: []
server:
  root: .
  baseurl: ""
  tlskey: ""
  tlscert: ""
  port: "80"
  address: 0.0.0.0
  log: stdout
auther:
  recaptcha: null
```

Dockerfile:

```
FROM alpine AS builder

WORKDIR /
COPY --from=filebrowser/filebrowser /filebrowser filebrowser
ADD config.json config.json
ADD db.yml db.yml
RUN ./filebrowser -c config.json config import db.yml
ARG ADMIN_PASSWORD=testpassword
RUN ./filebrowser -c config.json users add admin $ADMIN_PASSWORD \
      --perm.admin=true


FROM filebrowser/filebrowser

WORKDIR /
ADD http://carolina.mydomain.com/infra/sdkportal/favicon.ico \
    ./style/img/icons/favicon.ico
ADD http://carolina.mydomain.com/infra/sdkportal/my_logo.svg \
    ./style/img/logo.svg
ADD config.json config.json
COPY --from=builder /database.db database.db

CMD ["-c", "config.json"]
```

(Sanitized to remove company host names, etc)
