### ISSUE TITLE
 /usr/bin/git: no such file or directory(apache reverse proxy, deploy via docker)

### ISSUE THREAD

**Issue by ZenWayne** [filebrowser/filebrowser#814]
I deploy the filebrowser via docker, and use apache reverse proxy filebrowser.
I cannot execute command in filebrowser.
OS:Centos
`/etc/httpd/conf/httpd.conf`reverse proxy snippet related to filebrowser
``` conf
<Location "/pan/">
ProxyPass http://127.0.0.1:8081/pan/
ProxyPassReverse http://127.0.0.1:8081/pan/
</Location>
<Location "/pan/api/command/">
ProxyPass ws://127.0.0.1:8081/pan/api/command/
ProxyPassReverse ws://127.0.0.1:8081/pan/api/command/
ProxyAddHeaders Off
ProxyPreserveHost On
RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s
</Location>

```
docker-compose.yml snippet
```
filebrowser:
    image: filebrowser/filebrowser
    deploy:
      replicas: 1
    ports:
      - "8081:80"
    environment:
      - PATH=/sbin:/bin:/usr/sbin:/usr/bin
    volumes:
      - "/usr:/usr"
      - "/usr/bin:/usr/bin"
      - "/usr/bin/git:/usr/bin/git"
      - "./filebrowser.db:/filebrowser.db"
      - "./filebrowser.json:/.filebrowser.json"
      - "./filebrowser.log:/filebrowser.log"
```
I can access filebrowser successfully, but cannot use the git command.
when I type `git --version`,  there is nothing output to the filebrowser terminal, the status code is 101, and there are no response for the request, but the filebrowser.log file show that `fork/exec /usr/bin/git: no such file or directory`.
