### ISSUE TITLE
this location can't be reached - docker

### ISSUE THREAD

**Issue by kamilmirza** [filebrowser/filebrowser#817]
**Description**
on the landing page (files/) it says "This location can't be reached"
on host filebrowser works fine with same configs 

**Expected behaviour**
it should show files given in root

docker logs shows:
`2019/07/17 09:46:35 Using config file: /.filebrowser.json
2019/07/17 09:46:35 Listening on [::]:8181
2019/07/17 09:46:39 /: 404 172.31.0.1:45706 stat /media/data: no such file or directory
2019/07/17 09:46:40 /: 404 172.31.0.1:45694 stat /media/data: no such file or directory`

here's my `docker-compose.yml`
```
version: "3"
services: 

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    user: 1000:1000
    volumes:
      - /media/data/:/srv/
      - /docker/filebrowser/database.db:/database.db
      - /docker/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 8181:8181
```

and here's my `.filebrowser.json`
```
{
  "port": 8181,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "./database.db",
  "root": "/media/data/"
}
```
