### ISSUE TITLE
git add not work

### ISSUE THREAD

**Issue by windzhu0514** [filebrowser/filebrowser#854]
**Description**
after modify the file,i want exec git add,commit,push command

filebrowser is run as system service

how to set the work directory

**Expected behaviour**
git add the changed file and commit

**What is happening instead?**
2019/09/03 16:54:52 [INFO] Blocking Command: "bash -c git add $FILE"
2019/09/03 16:54:52 [INFO] /
2019/09/03 16:54:52 [INFO] fatal: Not a git repository (or any of the parent directories): .git

**Additional context**
command is here

After Upload
```
pwd
git add $FILE
git commit -m"add or modify post"
git push
```

**How to reproduce?**
just do it

**Files**
.filebrowser.toml
```toml
database = "/etc/filebrowser/filebrowser.db"
address ="0.0.0.0"
port = 9000
root = "/var/filebrowser/mysite"
baseurl = "/manager"
```
