### ISSUE TITLE
unable to use the shell in filebrowser docker

### ISSUE THREAD

**Issue by StefVanG** [filebrowser/filebrowser#982]
I'm using the latest version in a docker container that run in a Debian 10 host, behind another container with nginx that act as a proxy and configured to be proxied in a subfolder of another domain.

After passing some simple unix shell commands to the admin user to test the shell behaviour (ls, cp, rm) my expectations are that those commands behave link in the terminal shell, so I could go forward and try to pass more complex command like docker and docker-compose to manage containers creation directly in that shell.

With the field "Execute on shell" empty the log tell me "exec: "bash": executable file not found in $PATH", while when I put "bash -c" in the "Execute on shell" field the log is "websocket: bad write message type".

Docker daemon is running with userns-remap and the user does't have root privileges but is in docker group because the Nginx-proxy's docker-gen container that manage the automatic proxy configuration needs access to the docker sock.

my compose file is:
```
version: "2.4"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    ports:
      - "13900:80"
    volumes:
      - /var/data/public/files/filebrowser/database.db:/database.db
      - /var/data/public:/srv
      - /var/data/public/files/filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      - proxy
    logging:
      driver: "json-file"
      options:
        mode: non-blocking
        max-buffer-size: 4m

networks:
  proxy:
    external: true
```
And the json is:

`{
  "port": 80,
  "baseURL": "/files",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}`
