### ISSUE TITLE
Docker database and config isn't saving on disk when binding

### ISSUE THREAD

**Issue by karlhayek** [filebrowser/filebrowser#996]
**Description**
When running filebrowser in Docker, and mounting `filebrowser.db` and `.filebrowser.json` from the host inside the container, changes to settings or users aren't persisted on the host.

**Expected behaviour**
I expect that changes are saved to `filebrowser.db` and `.filebrowser.json` on the host, so that when I run filebrowser again later, the added users and changed settings are present.

**What is happening instead?**
The host's files aren't being updated.

**How to reproduce?**
`docker-compose.yml`:
```
filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 80:80
    volumes:
        - ./data:/srv
        - ./database.db:/database.db \
        - ./.filebrowser.json:/.filebrowser.json \
```
`.filebrowser.json`:
```
{
    "port": 80,
    "baseURL": "/filebrowser",
    "address": "",
    "log": "stdout",
    "database": "./database.db",
    "root": "/srv",
    "locale": "fr",
    "commands": []
}
```
And run with `docker-compose up --force-recreate` (recreating the containers prevents using the previous cached image).

**Comment by o1egl** [comment]
I don't think that this issue might be related to the filebrowser. It might be an issue with your docker setup. For instance this docker-compose.yaml works as expected.
```yaml
version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "8080:80"
    volumes:
      - ./database.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
```
